export const SRC = {
  makeitfrom: { name: 'MakeItFrom material properties', url: 'https://www.makeitfrom.com/material-properties/' },
  covestro: { name: 'Covestro Makrolon 2405 datasheet', url: 'https://solutions.covestro.com/en/products/makrolon/makrolon-2405_00945088-00009643' },
  iec62368: { name: 'IEC 62368-1 TS1 touch-temperature limits (UL tech brief)', url: 'https://japan.ul.com/wp-content/uploads/sites/27/2014/06/1_techbrief_touchtemp.pdf' },
  wearable: { name: 'Electronics Cooling: thermal design for worn electronics', url: 'https://www.electronics-cooling.com/2025/07/thermal-design-for-externally-worn-wearable-electronics/' },
  swellApple: { name: 'Apple patent: 8% cell swell budget', url: 'https://image-ppubs.uspto.gov/dirsearch-public/print/downloadPdf/8513919' },
  swellQnovo: { name: 'Qnovo: OEMs allow 10–15% or up to 0.7 mm swell', url: 'https://qnovo.com/lets-talk-about-the-waist' },
  usbc: { name: 'USB Type-C receptacle opening 8.34 × 2.56 mm', url: 'https://en.wikipedia.org/wiki/USB-C' },
  ltpo: { name: 'Samsung variable refresh: up to 22% display power saving', url: 'https://oled-info.com/samsung-announces-new-variable-refresh-rate-technology-its-latest-amoled' },
  utg: { name: 'Schott Xensation Flex UTG 30–100 µm', url: 'https://www.schott.com/en-au/products/xensation-flex-p1000743' },
  iec60529: { name: 'IEC 60529 degrees of protection (IP code)', url: 'https://webstore.iec.ch/en/publication/2452' },
  heat: { name: 'Natural convection + radiation from a flat plate (Incropera, Fundamentals of Heat and Mass Transfer, ch. 9 and 12)', url: 'https://www.wiley.com/en-us/Fundamentals+of+Heat+and+Mass+Transfer%2C+8th+Edition-p-9781119353881' },
  gorilla: { name: 'Corning Gorilla Glass Victus 2 datasheet (density 2.42 g/cm³)', url: 'https://www.corning.com/gorillaglass/worldwide/en/glass-types/gorilla-glass-victus-2.html' },
  fr4: { name: 'FR-4 laminate density ≈ 1.85 g/cm³ (Isola 370HR datasheet)', url: 'https://www.isola-group.com/pcb-laminates-prepreg/370hr-laminate-and-prepreg/' },
  roark: { name: 'Roark’s Formulas for Stress and Strain, Table 11.4: uniformly loaded rectangular plate, simply supported, σ = β·p·b²/t²', url: 'https://www.mheducation.com/highered/product/roark-s-formulas-stress-strain-young-budynas-sadegh/M9781260453751.html' },
  corningStrength: { name: 'Corning Gorilla Glass: chemically strengthened cover glass, ring-on-ring strength well above 600 MPa; 250 MPa used as a ⅓ design allowable', url: 'https://www.corning.com/gorillaglass/worldwide/en/glass-types/gorilla-glass-victus-2.html' },
  stereo: { name: 'Stereo depth error δZ ≈ Z²·δd/(f·B) (Hartley & Zisserman; Intel RealSense depth-accuracy note)', url: 'https://dev.intelrealsense.com/docs/tuning-depth-cameras-for-best-performance' },
  akoun: { name: 'Akoun & Yonnet, 3D analytical calculation of the forces exerted between two cuboidal magnets, IEEE Trans. Magn. 20(5), 1984', url: 'https://doi.org/10.1109/TMAG.1984.1063554' },
  dipole: { name: 'Magnetic dipole field B = μ0/4π · (3r̂(m·r̂) − m)/r³ (Jackson, Classical Electrodynamics §5.6)', url: 'https://en.wikipedia.org/wiki/Magnetic_dipole' },
  ndfeb: { name: 'Sintered NdFeB grade table: N52 Br 1.43–1.48 T, max 80 °C; N48SH Br 1.37–1.42 T, max 150 °C (Arnold Magnetic Technologies)', url: 'https://www.arnoldmagnetics.com/products/neodymium-iron-boron-magnets/' },
  ipc2223: { name: 'JLCPCB flex capabilities: dynamic bending needs a bend radius ≥ 10–15× total flex thickness (IPC-2223-style ratio; 15× used)', url: 'https://jlcpcb.com/capabilities/flex-pcb-capabilities' },
  bmm350: { name: 'Bosch BMM350 handling guide: hard magnets offset the compass; keep soft-magnetic parts (martensitic steel pins) away; use 304/316 or titanium', url: 'https://www.bosch-sensortec.com/media/boschsensortec/downloads/handling_soldering_mounting_instructions/bst-bmm350-hs000.pdf' },
  steel: { name: 'Stainless 17-4PH H900 (σy 1170 MPa) and 304 (σy 215 MPa), MakeItFrom', url: 'https://www.makeitfrom.com/material-properties/H900-17-4PH-Stainless-Steel' },
};
export const MATERIALS = {
  al6061: { name: 'Aluminium 6061-T6 (CNC)', rho: 2.7, E: 69, sy: 270, k: 170, metal: true, cost: 'cnc', src: 'makeitfrom' },
  al7075: { name: 'Aluminium 7075-T6 (CNC)', rho: 2.8, E: 70, sy: 480, k: 130, metal: true, cost: 'cnc', src: 'makeitfrom' },
  ti5: { name: 'Titanium Grade 5 (CNC)', rho: 4.4, E: 110, sy: 910, k: 6.8, metal: true, cost: 'cnc-ti', src: 'makeitfrom' },
  pc: { name: 'Polycarbonate (Makrolon 2405, molded)', rho: 1.2, E: 2.4, sy: 65, k: 0.2, metal: false, cost: 'mold', src: 'covestro' },
  pa12: { name: 'Nylon PA12 (MJF 3D print)', rho: 1.01, E: 1.8, sy: 48, k: 0.25, metal: false, cost: 'mjf', src: 'makeitfrom' },
  resin: { name: 'Tough SLA resin (prototype)', rho: 1.15, E: 2.0, sy: 45, k: 0.2, metal: false, cost: 'sla', src: 'makeitfrom' },
};
export const LEAF_MATS = {
  ss174: { name: '17-4PH stainless H900 (MIM or CNC, magnetic)', rho: 7.8, sy: 1170, src: 'steel', magnetic: true },
  ss304: { name: '304 stainless (CNC / laser-cut, non-magnetic)', rho: 8.0, sy: 215, src: 'steel' },
  ss316h: { name: '316 stainless, cold-worked ½-hard (non-magnetic)', rho: 8.0, sy: 515, src: 'steel' },
  ti5: { name: 'Titanium Grade 5 (CNC)', rho: 4.43, sy: 880, src: 'makeitfrom' },
};
export const BACKS = {
  unibody: { name: 'Unibody floor (same material as frame)', t: 0.9, rho: null, bonded: false },
  glass: { name: 'Bonded glass back', t: 0.55, rho: 2.42, bonded: true },
  pc: { name: 'Bonded polycarbonate back', t: 0.8, rho: 1.2, bonded: true },
};
export const K = {
  hConv: 11, tAmb: 25, skinComfort: 43, skinTs1: 48, perfExp: 0.45, holdFactor: 0.9, bridge: 0.3,
  swellFrac: 0.08, swellMin: 0.3, swellSide: 0.5, clear: 0.2, wallClear: 0.3, gapDisplay: 0.25,
  bgaRing: 1.2, seamGap: 1.2, pinMargin: 0.5, pinEngage: 3, swingStep: 2, swingClear: 0.15, magFrac: 0.5, magDelta: 50, magCoil: 5, magNfc: 3, magSpk: 3, holdMax: 15, holdK: 2, shock: 30, flexRmul: 15, flexT: 0.11, dsiBpp: 24, dsiOver: 1.25,
  boardT: 0.8, boardRho: 1.9, glassRho: 2.42, adhesiveT: 0.15, antKeep: 3, usable: 0.95,
  usbW: 8.34, usbH: 2.56, usbCut: [9.4, 3.6],
  estDensity: { module: 2.2, passive: 1.6, cell: 2.6, display: 2.4, mech: 3.5 },
};
export const EST = {
  displayW: { basis: 'Placeholder: OLED ≈ 0.35 W for a 6.5 in panel at ~200 nits mixed content (panel listing gives no power figure)', perIn2: 0.0083 },
  cameraW: { basis: 'Estimate: MIPI camera module ≈ 0.25 W streaming (no datasheet figure)', w: 0.25 },
  baseW: { basis: 'Estimate: sensors, audio, PMIC losses ≈ 0.2 W screen-on', w: 0.2 },
  idleMW: { basis: 'Estimate: background + leakage ≈ 25 mW', mw: 25 },
};
export const PROFILE = [
  { id: 'web', name: 'Web and social', share: 0.5, soc: 0.35, disp: 1, radio: 0.6, cam: 0, gnss: 0 },
  { id: 'video', name: 'Video', share: 0.25, soc: 0.25, disp: 1.1, radio: 0.5, cam: 0, gnss: 0 },
  { id: 'camera', short: 'Cameras', name: 'Camera', share: 0.1, soc: 0.6, disp: 1.3, radio: 0.2, cam: 1, gnss: 0 },
  { id: 'nav', name: 'Navigation', share: 0.15, soc: 0.4, disp: 1.2, radio: 0.8, cam: 0, gnss: 1 },
];
const BOOK_HALF = { speaker: 'B', haptic: 'B', cell2: 'B', display2: 'B' };
const FLIP_HALF = { usbc: 'B', speaker: 'B', mic: 'B', haptic: 'B', cell: 'B', cell2: 'A', qi_coil: 'B', nfc_coil: 'B', ant_main: 'B', display2: 'B', keypad: 'B', seal_usbc: 'B' };
export const FORMS = {
  slab: { name: 'Slab', text: 'One rigid housing. The buildable default.', halves: 1, buildable: true, axis: null, hinges: [] },
  dual: { name: 'Dual-screen book', text: 'Two rigid halves side by side, each with its own real panel, folding across the long axis. A center friction hinge (like Surface Duo) or the dual outer hinge with magnets. The seam is not one continuous picture.', halves: 2, buildable: true, axis: 'long', hinges: ['spine', 'outer'], halfOf: BOOK_HALF },
  flip: { name: 'Dual-panel flip', text: 'Clamshell that folds across the short axis: a rigid top screen and a rigid bottom screen (or a keypad), with an optional cover screen on the outside. Buildable from buyable panels; center friction hinge or the dual outer hinge with magnets.', halves: 2, buildable: true, axis: 'short', hinges: ['spine', 'outer'], halfOf: FLIP_HALF },
  fold: { name: 'Foldable book (reference)', text: 'One folding OLED across both halves (book fold). Foldable panels and their hinges are OEM-only, so this form is reference-only.', halves: 2, buildable: false, axis: 'long', hinges: ['waterdrop', 'u_shape', 'multi_link'], foldable: 'book', halfOf: BOOK_HALF },
  flipfold: { name: 'Foldable flip (reference)', text: 'Classic clamshell flip: one folding inner OLED across both halves plus a cover screen. The foldable panel and its waterdrop / U-shape / multi-link hinge are OEM-only, so this form is reference-only.', halves: 2, buildable: false, axis: 'short', hinges: ['waterdrop', 'u_shape', 'multi_link'], foldable: 'flip', halfOf: FLIP_HALF },
};
export const HINGES = {
  spine: { name: 'Center friction hinge', short: 'Center spine', text: 'Friction hinges at the seam corners with the pivot on the display face. Opens 0–180°; shut faces touch.', kind: 'friction', pf: 0, leaf: 0, range: [0, 180], buildable: true },
  outer: { name: 'Dual outer hinge with magnets', short: 'Outer links', text: 'Two flat leaf links on the OUTSIDE of the shells, one at each end of the seam, each with a pin into each half’s side wall. The shells swing without touching; NdFeB magnets hold it shut and flat. A longer leaf parks the pins inboard and allows 360°.', kind: 'outer_link', range: [0, 360], buildable: true },
  waterdrop: { name: 'Waterdrop hinge (OEM)', short: 'Waterdrop', text: 'Panel bends into a teardrop inside the hinge housing; shuts with no gap (Galaxy Z Flip5+). OEM-only.', kind: 'waterdrop', pf: 0, leaf: 0, range: [0, 180], buildable: false, teardrop: 3 },
  u_shape: { name: 'U-shape hinge (OEM)', short: 'U-shape', text: 'Panel bends at a U radius; leaves a gap of about twice the bend radius when shut (Galaxy Z Flip 1–4). OEM-only.', kind: 'u_shape', pf: -1.5, leaf: 0, range: [0, 180], buildable: false },
  multi_link: { name: 'Multi-link hinge (OEM)', short: 'Multi-link', text: 'Multi-link waterdrop mechanism (Huawei, Oppo, Honor); gapless when shut, more parts. OEM-only.', kind: 'multi_link', pf: 0, leaf: 0, range: [0, 180], buildable: false, teardrop: 2.5 },
};
export const DOCK_DEFAULT = { on: false, edges: { E: true, W: true, N: true, S: true }, links: { E: true, W: true, N: true, S: true }, perEdge: 4, back: true, code: 'pair', sealed: false };
export const DOCK_CODES = { pair: { name: 'Anti-palindromic pairs (+ + − −)', seq: n => Array.from({ length: n }, (_, k) => k < n / 2 ? 1 : -1) }, alt: { name: 'Alternating (+ − + −)', seq: n => Array.from({ length: n }, (_, k) => k % 2 ? -1 : 1) }, same: { name: 'All north out (+ + + +)', seq: n => Array.from({ length: n }, () => 1) } };
export const HINGE_DEFAULT = { type: 'spine', leaf: 6, pinFace: 2, inset: 2.5, pinD: 1.6, leafT: 1.0, leafW: 4.5, leafMat: 'ti5', shutPairs: 2, flatPairs: 2, detents: [], flipBottom: 'screen' };
export const ROLES = [
  { id: 'display', cat: ['display', 'display_ref'], name: 'Display + touch', step: 'display', req: true, mount: 'display' },
  { id: 'display2', cat: ['display'], name: 'Second display', step: 'display', req: false, mount: 'display', half: 'B', forms: ['dual', 'flip'], when: d => d.form !== 'flip' || d.hinge.flipBottom !== 'keys' },
  { id: 'display_cover', cat: ['display'], name: 'Cover (outer) display', step: 'display', req: false, mount: 'backDisplay', kind: 'cover', forms: ['flip', 'flipfold'] },
  { id: 'keypad', cat: ['button'], name: 'Keypad switches (bottom half)', step: 'controls', req: true, mount: 'keypad', forms: ['flip'], when: d => d.hinge.flipBottom === 'keys', count: 16 },
  { id: 'glass', cat: ['cover_glass'], name: 'Cover glass', step: 'display', req: true, mount: 'glass' },
  { id: 'som', cat: ['som', 'soc_ref'], name: 'Compute module', step: 'compute', req: true, mount: 'boardTop', when: d => d.board.path === 'som' },
  { id: 'mcu', cat: ['mcu'], name: 'Companion processor (MCU / light MPU)', step: 'compute', req: true, mount: 'boardTop', when: d => d.board.path === 'mcu' },
  { id: 'soc', cat: ['soc', 'soc_ref'], name: 'Application processor (chip-level)', step: 'compute', req: true, mount: 'boardTop', when: d => d.board.path === 'custom', bga: true },
  { id: 'soc_pmic', cat: ['pmic'], name: 'SoC PMIC', step: 'compute', req: true, mount: 'boardTop', kind: 'soc_pmic', when: d => d.board.path === 'custom', bga: true },
  { id: 'lpddr', cat: ['lpddr'], name: 'LPDDR memory', step: 'compute', req: true, mount: 'boardTop', when: d => d.board.path === 'custom', bga: true },
  { id: 'ufs', cat: ['ufs'], name: 'UFS / eMMC storage', step: 'compute', req: true, mount: 'boardBottom', when: d => d.board.path === 'custom', bga: true },
  { id: 'codec', cat: ['codec'], name: 'Audio codec / smart amp', step: 'audio', req: false, mount: 'boardBottom', when: d => d.board.path === 'custom' },
  { id: 'memory', cat: ['memory'], name: 'Extra memory', step: 'compute', req: false, mount: 'boardTop' },
  { id: 'modem', cat: ['modem'], name: 'Cellular modem', step: 'compute', req: 'noModem', mount: 'boardBottom' },
  { id: 'wifi', cat: ['wifi'], name: 'Wi-Fi / Bluetooth', step: 'compute', req: 'noWifi', mount: 'boardBottom' },
  { id: 'gnss', cat: ['gnss'], name: 'GNSS', step: 'compute', req: false, mount: 'boardBottom' },
  { id: 'ntn', cat: ['ntn'], name: 'Satellite (NTN)', step: 'compute', req: false, mount: 'boardBottom' },
  { id: 'cell', cat: ['cell', 'cell_custom'], name: 'Battery cell', step: 'power', req: true, mount: 'floor' },
  { id: 'cell2', cat: ['cell'], name: 'Second cell', step: 'power', req: false, mount: 'floor', half: 'B', forms: ['dual', 'fold', 'flip', 'flipfold'] },
  { id: 'charger', cat: ['charger'], name: 'Charger', step: 'power', req: true, mount: 'boardBottom' },
  { id: 'fuel_gauge', cat: ['fuel_gauge'], name: 'Fuel gauge', step: 'power', req: true, mount: 'boardBottom' },
  { id: 'protection', cat: ['protection'], name: 'Cell protection', step: 'power', req: 'noProtect', mount: 'boardBottom' },
  { id: 'usb_pd', cat: ['usb_pd'], name: 'USB-C PD controller', step: 'power', req: false, mount: 'boardBottom' },
  { id: 'pmic', cat: ['pmic'], name: 'Peripheral regulator', step: 'power', req: false, mount: 'boardBottom', kind: 'reg' },
  { id: 'qi_rx', cat: ['qi_rx'], name: 'Wireless charging IC', step: 'power', req: 'sealed', mount: 'boardBottom' },
  { id: 'qi_coil', cat: ['qi_coil'], name: 'Wireless charging coil', step: 'power', req: 'sealed', mount: 'floor' },
  { id: 'cam_main', cat: ['camera'], name: 'Main camera', step: 'camera', req: 'csi', mount: 'back' },
  { id: 'cam_ultra', cat: ['camera'], name: 'Second rear camera', step: 'camera', req: false, mount: 'back' },
  { id: 'cam_front', cat: ['camera_front'], name: 'Front camera', step: 'camera', req: 'csi', mount: 'front' },
  { id: 'flash', cat: ['flash'], name: 'Flash LED', step: 'camera', req: false, mount: 'back', kind: 'led' },
  { id: 'flash_drv', cat: ['flash'], name: 'Flash LED driver', step: 'camera', req: false, mount: 'boardBottom', kind: 'drv' },
  { id: 'tof', cat: ['camera_aux'], name: 'Laser AF / ToF sensor', step: 'camera', req: false, mount: 'back', kind: 'tof' },
  { id: 'ois_drv', cat: ['camera_aux'], name: 'AF / OIS driver', step: 'camera', req: false, mount: 'boardBottom', kind: 'actuator' },
  { id: 'amp', cat: ['audio_amp'], name: 'Smart speaker amp', step: 'audio', req: false, mount: 'boardBottom' },
  { id: 'speaker', cat: ['speaker'], name: 'Loudspeaker', step: 'audio', req: true, mount: 'floor', half2: 'B' },
  { id: 'receiver', cat: ['receiver'], name: 'Earpiece receiver', step: 'audio', req: true, mount: 'top' },
  { id: 'mic', cat: ['mic'], name: 'Bottom microphone', step: 'audio', req: true, mount: 'boardBottom' },
  { id: 'mic2', cat: ['mic'], name: 'Top microphone', step: 'audio', req: false, mount: 'boardTop' },
  { id: 'haptic', cat: ['haptic'], name: 'Haptic LRA', step: 'audio', req: true, mount: 'floor', half2: 'B' },
  { id: 'haptic_drv', cat: ['haptic_drv'], name: 'Haptic driver', step: 'audio', req: true, mount: 'boardBottom' },
  { id: 'usbc', cat: ['usbc', 'seal_usbc'], name: 'USB-C receptacle', step: 'controls', req: true, mount: 'edgeBottom', when: d => !d.dock.sealed },
  { id: 'btn_power', cat: ['button'], name: 'Power key', step: 'controls', req: true, mount: 'edgeRight', when: d => !d.dock.sealed },
  { id: 'btn_up', cat: ['button'], name: 'Volume up', step: 'controls', req: true, mount: 'edgeRight', when: d => !d.dock.sealed },
  { id: 'btn_down', cat: ['button'], name: 'Volume down', step: 'controls', req: true, mount: 'edgeRight', when: d => !d.dock.sealed },
  { id: 'sim', cat: ['sim'], name: 'Nano-SIM holder', step: 'controls', req: 'noEsim', mount: 'boardBottom', when: d => !d.dock.sealed },
  { id: 'esim', cat: ['esim'], name: 'eSIM (eUICC)', step: 'controls', req: 'sealed', mount: 'boardBottom' },
  { id: 'imu', cat: ['sensor'], name: 'IMU', step: 'controls', req: true, mount: 'boardBottom', kind: 'imu' },
  { id: 'als', cat: ['sensor'], name: 'Ambient light + proximity', step: 'controls', req: true, mount: 'top', kind: 'als' },
  { id: 'baro', cat: ['sensor'], name: 'Barometer', step: 'controls', req: false, mount: 'boardBottom', kind: 'baro' },
  { id: 'mag', cat: ['sensor'], name: 'Magnetometer', step: 'controls', req: false, mount: 'boardBottom', kind: 'mag' },
  { id: 'fingerprint', cat: ['fingerprint'], name: 'Fingerprint sensor', step: 'controls', req: false, mount: 'back' },
  { id: 'nfc', cat: ['nfc'], name: 'NFC controller', step: 'controls', req: false, mount: 'boardBottom' },
  { id: 'nfc_coil', cat: ['nfc_coil'], name: 'NFC coil', step: 'controls', req: false, mount: 'floor' },
  { id: 'hall', cat: ['sensor'], name: 'Lid (Hall) sensor', step: 'controls', req: false, mount: 'boardBottom', kind: 'hall', forms: ['dual', 'flip', 'fold', 'flipfold'] },
  { id: 'ant_main', cat: ['antenna'], name: 'Cellular main antenna', step: 'rf', req: true, mount: 'antBottom', kind: 'cell' },
  { id: 'ant_div', cat: ['antenna'], name: 'Cellular diversity antenna', step: 'rf', req: true, mount: 'antTop', kind: 'cell' },
  { id: 'ant_wifi', cat: ['antenna'], name: 'Wi-Fi / BT antenna', step: 'rf', req: true, mount: 'antTop', kind: 'wifi' },
  { id: 'ant_gnss', cat: ['antenna'], name: 'GNSS antenna', step: 'rf', req: false, mount: 'antTop', kind: 'gnss' },
  { id: 'conn_display', cat: ['b2b', 'fpc_conn'], name: 'Display connector', step: 'layout', req: true, mount: 'boardTop' },
  { id: 'conn_cam', cat: ['b2b', 'fpc_conn'], name: 'Camera connector', step: 'layout', req: true, mount: 'boardTop' },
  { id: 'conn_batt', cat: ['b2b', 'fpc_conn'], name: 'Battery connector', step: 'layout', req: true, mount: 'boardTop' },
  { id: 'shield', cat: ['shield'], name: 'RF shield can', step: 'layout', req: false, mount: 'boardTop' },
  { id: 'thermal', cat: ['thermal'], name: 'Heat spreader', step: 'layout', req: true, mount: 'spreader' },
  { id: 'hinge', cat: ['hinge'], name: 'Friction hinge (×2)', step: 'form', req: 'folding', mount: 'hinge', forms: ['dual', 'flip'], hinges: ['spine'], kind: 'friction', count: 2 },
  { id: 'hinge_fold', cat: ['hinge'], name: 'Foldable hinge', step: 'form', req: 'folding', mount: 'none', forms: ['fold', 'flipfold'], kindFrom: 'type' },
  { id: 'hinge_leaf', cat: ['hinge'], name: 'Outer hinge leaf (×2)', step: 'form', req: 'folding', mount: 'none', hinges: ['outer'], kind: 'outer_link', count: 2 },
  { id: 'hinge_pin', cat: ['hinge'], name: 'Hinge pins / bushings (×4)', step: 'form', req: 'folding', mount: 'none', hinges: ['outer'], kind: 'outer_pin', count: 4 },
  { id: 'hinge_detent', cat: ['hinge'], name: 'Friction / detent washers (×4)', step: 'form', req: false, mount: 'none', hinges: ['outer'], kind: 'detent', count: 4 },
  { id: 'mag_shut', cat: ['magnet'], name: 'Closing magnets', step: 'form', req: 'outer', mount: 'magShut', kind: 'block', forms: ['dual', 'flip'], pairs: 'shutPairs' },
  { id: 'mag_flat', cat: ['magnet'], name: 'Flat-open magnets', step: 'form', req: 'outer', mount: 'magFlat', kind: 'block', hinges: ['outer'], pairs: 'flatPairs' },
  { id: 'dock_mag', cat: ['magnet'], name: 'Dock magnets (edge arrays)', step: 'form', req: 'dock', mount: 'magEdge', kind: 'block', when: d => d.dock.on },
  { id: 'dock_back', cat: ['magnet'], name: 'Dock magnets (back array)', step: 'form', req: false, mount: 'magBack', when: d => d.dock.on && d.dock.back },
  { id: 'dock_link', cat: ['interconnect'], name: 'Dock link (per linked edge)', step: 'form', req: 'dock', mount: 'linkEdge', when: d => d.dock.on },
  { id: 'dock_hall', cat: ['sensor'], name: 'Dock orientation sensors (per edge)', step: 'form', req: false, mount: 'hallEdge', kind: 'hall', when: d => d.dock.on },
  { id: 'link', cat: ['interconnect'], name: 'Half-to-half link', step: 'form', req: 'folding', mount: 'none', forms: ['dual', 'flip', 'fold', 'flipfold'] },
  { id: 'adhesive', cat: ['adhesive'], name: 'Display / back bond tape', step: 'seal', req: 'ip', mount: 'none', kind: 'display_back_bond' },
  { id: 'adhesive_int', cat: ['adhesive'], name: 'Internal bonding tape', step: 'seal', req: false, mount: 'none', kind: 'internal_bond' },
  { id: 'gasket', cat: ['gasket'], name: 'Button O-ring', step: 'seal', req: 'ip', mount: 'none', kind: 'oring_button' },
  { id: 'foam', cat: ['gasket'], name: 'Foam dust gasket', step: 'seal', req: false, mount: 'none', kind: 'foam_seal' },
  { id: 'vent_mic', cat: ['vent'], name: 'Microphone acoustic vent', step: 'seal', req: 'ip', mount: 'none', kind: 'vent_acoustic_mic' },
  { id: 'vent_spk', cat: ['vent'], name: 'Speaker / receiver acoustic vent', step: 'seal', req: 'ip', mount: 'none', kind: 'vent_acoustic_speaker' },
  { id: 'vent_baro', cat: ['vent'], name: 'Pressure-equalisation vent', step: 'seal', req: false, mount: 'none', kind: 'vent_pressure' },
  { id: 'coating', cat: ['coating'], name: 'Nano-coating', step: 'seal', req: false, mount: 'none' },
];
export const STEPS = [
  { id: 'req', short: 'Reqs', name: 'Requirements' }, { id: 'form', short: 'Form', name: 'Form + housing' }, { id: 'display', short: 'Display', name: 'Display + glass' }, { id: 'compute', short: 'Compute', name: 'Compute + radios' }, { id: 'power', short: 'Battery', name: 'Battery + power' }, { id: 'camera', name: 'Cameras' }, { id: 'audio', short: 'Audio', name: 'Audio + haptics' }, { id: 'controls', short: 'Controls', name: 'Controls + sensors' }, { id: 'rf', short: 'Antennas', name: 'Antennas' }, { id: 'seal', short: 'Seal', name: 'Ingress protection' }, { id: 'layout', short: 'Board', name: 'Board + layout' }, { id: 'validate', short: 'Checks', name: 'Validate' }, { id: 'optimize', short: 'Optimize', name: 'Optimize' }, { id: 'build', short: 'Build', name: 'Build pack' },
];
export const IP_LEVELS = { none: { name: 'No rating', n: 0 }, ip54: { name: 'IP54 splash', n: 4 }, ip67: { name: 'IP67 (1 m, 30 min)', n: 7 }, ip68: { name: 'IP68 (declared depth/time)', n: 8 } };
export const OPENINGS = [
  { id: 'display', name: 'Display / cover-glass seam', roles: ['display'], methods: ['bond'] },
  { id: 'back', name: 'Back cover seam', roles: [], methods: ['bond'], when: 'bondedBack' },
  { id: 'usbc', name: 'USB-C port', roles: ['usbc'], methods: ['sealedPart', 'gasket'] },
  { id: 'speaker', name: 'Speaker port', roles: ['speaker'], methods: ['vent'] },
  { id: 'receiver', name: 'Earpiece slot', roles: ['receiver'], methods: ['vent'] },
  { id: 'mic', name: 'Microphone ports', roles: ['mic', 'mic2'], methods: ['vent'] },
  { id: 'buttons', name: 'Side keys', roles: ['btn_power', 'btn_up', 'btn_down'], methods: ['sealedPart', 'oring', 'membrane'] },
  { id: 'sim', name: 'SIM tray', roles: ['sim'], methods: ['gasket'] },
  { id: 'baro', name: 'Pressure vent', roles: ['baro'], methods: ['vent', 'gelSensor'] },
  { id: 'camera', name: 'Camera / flash windows', roles: ['cam_main', 'cam_ultra', 'flash', 'fingerprint'], methods: ['bond'] },
  { id: 'hinge', name: 'Hinge barrel', roles: ['hinge', 'hinge_fold'], methods: ['gasket', 'coating'], when: 'spine' },
  { id: 'pins', name: 'Outer hinge pin bores (blind bosses)', roles: ['hinge_pin'], methods: ['blind', 'oring'], when: 'outer' },
  { id: 'flex', name: 'Half-to-half flex / contact passage', roles: ['link'], methods: ['gasket', 'potting', 'contactless'], when: 'folding' },
];
