import { MATERIALS, BACKS, FORMS, IP_LEVELS, SRC, K } from './catalog.js';
import { boardStudy, HDI } from './board.js';
import { db, priceAt } from './parts.js';
import { autoSchematic } from './schematic.js';
const f2 = v => (Math.round(v * 100) / 100).toFixed(2);
const esc = s => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const csvCell = v => { const s = v == null ? '' : String(v); return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s; };
export const csv = rows => rows.map(r => r.map(csvCell).join(',')).join('\n') + '\n';
const PREFIX = { som: 'U', memory: 'U', modem: 'U', ntn: 'U', wifi: 'U', gnss: 'U', charger: 'U', fuel_gauge: 'U', protection: 'U', usb_pd: 'U', pmic: 'U', qi_rx: 'U', haptic_drv: 'U', nfc: 'U', sensor: 'U', esim: 'U', usbc: 'J', seal_usbc: 'J', sim: 'J', b2b: 'J', fpc_conn: 'J', cell: 'BT', cell_custom: 'BT', speaker: 'LS', receiver: 'LS', mic: 'MK', haptic: 'M', button: 'SW', antenna: 'AE', qi_coil: 'L', nfc_coil: 'L', flash: 'D', camera: 'CAM', camera_front: 'CAM', display: 'DS', display_ref: 'DS', cover_glass: 'G', shield: 'SH', thermal: 'TH', fingerprint: 'U', hinge: 'H' };
export function designators(items) { const n = {}; return Object.fromEntries(items.map(it => { const p = PREFIX[it.cat] || 'X'; n[p] = (n[p] || 0) + 1; return [it.uid, p + n[p]]; })); }
export function bomRows(res) {
  if (res.system && !res.__piece) { const S = res.system, nA = S.tiles.filter(t => t.type === 'A').length, nB = S.tiles.filter(t => t.type === 'B').length, A = bomRows({ ...res, system: null, __piece: true }).map(r => ({ ...r, piece: 'A', perPiece: r.qty, qty: r.qty * nA })), B = res.resB && nB ? bomRows({ ...res.resB, __piece: true }).map(r => ({ ...r, piece: 'B', perPiece: r.qty, qty: r.qty * nB, ref: r.ref ? 'B:' + r.ref : '' })) : []; return [...A, ...B]; }
  const q = res.d.req.qty, refs = designators(res.items), out = [];
  res.cost.rows.forEach(r => { const p = db().byId.get(r.pid) || {}, buy = (p.buy || [])[0] || {}; const pr = [1, 100, 1000].map(k => priceAt(p, k).usd); out.push({ ref: res.items.filter(i => i.role === r.role).map(i => refs[i.uid]).join(' '), role: r.name, mfr: p.mfr, mpn: p.mpn, qty: r.qty, status: p.status, lifecycle: p.lifecycle, q1: pr[0], q100: pr[1], q1k: pr[2], at: r.usd, ext: r.ext, vendor: buy.vendor, url: buy.url, datasheet: p.datasheet, checked: p.checked, dims: p.dims ? p.dims.join('×') : '', basis: r.basis }); });
  res.cost.fab.forEach(r => out.push({ ref: '', role: r.name, mfr: r.mfr, mpn: r.mpn, qty: r.qty, status: r.status, lifecycle: '', q1: null, q100: null, q1k: null, at: r.usd, ext: r.ext, vendor: r.mfr, url: (((db().byId.get(r.pid) || {}).buy || [])[0] || {}).url, datasheet: '', checked: (db().byId.get(r.pid) || {}).checked, dims: '', basis: r.basis }));
  return out;
}
export function bomCSV(res) { if (res.system) return csv([['Piece', 'Designator', 'Role', 'Manufacturer', 'MPN', 'Qty per piece', 'Qty per set', 'Status', 'Lifecycle', 'USD q1', 'USD q100', 'USD q1k', 'USD used (qty ' + res.d.req.qty + ')', 'USD ext per set', 'Supplier', 'Datasheet', 'Checked'], ...bomRows(res).map(r => [r.piece, r.ref, r.role, r.mfr, r.mpn, r.perPiece, r.qty, r.status, r.lifecycle, r.q1, r.q100, r.q1k, r.at, r.at == null ? null : r.at * r.qty, r.vendor, r.datasheet, r.checked])]); return csv([['Designator', 'Role', 'Manufacturer', 'MPN', 'Qty/unit', 'Status', 'Lifecycle', 'USD q1', 'USD q100', 'USD q1k', 'USD used (qty ' + res.d.req.qty + ')', 'USD ext', 'Price basis', 'Supplier', 'Supplier URL', 'Datasheet', 'Dims mm', 'Checked'], ...bomRows(res).map(r => [r.ref, r.role, r.mfr, r.mpn, r.qty, r.status, r.lifecycle, r.q1, r.q100, r.q1k, r.at, r.ext, r.basis, r.vendor, r.url, r.datasheet, r.dims, r.checked])]); }
export function rfqRows(res) { return bomRows(res).filter(r => r.status !== 'buyable' || r.at == null); }
export function rfqCSV(res) { return csv([['Role', 'Manufacturer', 'MPN', 'Qty per phone', 'Target volume', 'Status', 'Why RFQ', 'Contact / URL', 'Checked'], ...rfqRows(res).map(r => [r.role, r.mfr, r.mpn, r.qty, res.d.req.qty, r.status, r.status === 'oem' ? 'OEM-only: needs an OEM agreement' : r.at == null ? 'No published price' : 'MOQ / custom part', r.url, r.checked])]); }
function boardOrigin(res) { const p = res.board.poly; return [Math.min(...p.map(v => v[0])), Math.min(...p.map(v => v[1]))]; }
export function placementCSV(res) {
  const refs = designators(res.items), [ox, oy] = boardOrigin(res);
  return csv([['Designator', 'Role', 'Manufacturer', 'MPN', 'Mid X mm', 'Mid Y mm', 'Z bottom mm', 'Rotation', 'Layer', 'Half', 'Size X', 'Size Y', 'Size Z'], ...res.items.map(it => [refs[it.uid], it.name, it.p.mfr, it.p.mpn, f2(it.x - (it.mount.startsWith('board') ? ox : 0)), f2(it.y - (it.mount.startsWith('board') ? oy : 0)), f2(it.z), it.rot, it.mount === 'boardTop' ? 'Top' : it.mount === 'boardBottom' ? 'Bottom' : 'Frame:' + it.mount, it.half, f2(it.sx), f2(it.sy), f2(it.sz)])]);
}
export function kicadPCB(res) {
  const refs = designators(res.items), P = 100, kx = x => f2(P + x), ky = y => f2(P - y), poly = res.board.poly;
  const q = s => '"' + String(s == null ? '' : s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
  const lines = poly.map((a, i) => { const b = poly[(i + 1) % poly.length]; return `  (gr_line (start ${kx(a[0])} ${ky(a[1])}) (end ${kx(b[0])} ${ky(b[1])}) (stroke (width 0.1) (type default)) (layer "Edge.Cuts"))`; });
  const fps = res.items.filter(it => it.mount === 'boardTop' || it.mount === 'boardBottom').map(it => {
    const bot = it.mount === 'boardBottom', L = bot ? 'B' : 'F', w = it.p.n.sx || it.sx, h = it.p.n.sy || it.sy;
    return `  (footprint ${q('Amni:' + (it.p.mpn || it.p.id))} (layer "${L}.Cu") (at ${kx(it.x)} ${ky(it.y)} ${it.rot})\n    (property "MPN" ${q(it.p.mpn)}) (property "Manufacturer" ${q(it.p.mfr)}) (property "Datasheet" ${q(it.p.datasheet || '')}) (property "Height_mm" ${q(f2(it.sz))})\n    (fp_text reference ${q(refs[it.uid])} (at 0 ${f2(-h / 2 - 1)} ${it.rot}) (layer "${L}.SilkS") (effects (font (size 0.8 0.8) (thickness 0.12))${bot ? ' (justify mirror)' : ''}))\n    (fp_text value ${q(it.p.mpn)} (at 0 0 ${it.rot}) (layer "${L}.Fab") (effects (font (size 0.6 0.6) (thickness 0.1))${bot ? ' (justify mirror)' : ''}))\n    (fp_rect (start ${f2(-w / 2 - 0.25)} ${f2(-h / 2 - 0.25)}) (end ${f2(w / 2 + 0.25)} ${f2(h / 2 + 0.25)}) (stroke (width 0.05) (type default)) (fill none) (layer "${L}.CrtYd"))\n    (fp_rect (start ${f2(-w / 2)} ${f2(-h / 2)}) (end ${f2(w / 2)} ${f2(h / 2)}) (stroke (width 0.1) (type default)) (fill none) (layer "${L}.Fab"))\n  )`;
  });
  const keep = res.items.filter(it => it.cat === 'antenna' && it.half === 'A').map(a => `  (gr_rect (start ${kx(a.box[0] - 3)} ${ky(a.box[4] + 3)}) (end ${kx(a.box[3] + 3)} ${ky(a.box[1] - 3)}) (stroke (width 0.1) (type dash)) (fill none) (layer "Dwgs.User"))`);
  return `(kicad_pcb (version 20221018) (generator "amni_phone_studio")\n  (general (thickness ${f2(res.board.t)}))\n  (paper "A4")\n  (layers\n    (0 "F.Cu" signal) (31 "B.Cu" signal) (34 "B.Paste" user) (35 "F.Paste" user) (36 "B.SilkS" user "B.Silkscreen") (37 "F.SilkS" user "F.Silkscreen") (38 "B.Mask" user) (39 "F.Mask" user) (40 "Dwgs.User" user "User.Drawings") (41 "Cmts.User" user "User.Comments") (44 "Edge.Cuts" user) (46 "B.CrtYd" user "B.Courtyard") (47 "F.CrtYd" user "F.Courtyard") (48 "B.Fab" user) (49 "F.Fab" user)\n  )\n  (setup (pad_to_mask_clearance 0))\n  (net 0 "")\n${lines.join('\n')}\n${keep.join('\n')}\n  (gr_text ${q('Amni-Phone Studio: ' + res.d.name + ' carrier board outline + placement. Footprints are courtyard/fab outlines named by MPN; swap in library footprints before routing. Dashed = antenna keep-outs.')} (at ${kx(Math.min(...poly.map(p => p[0])))} ${ky(Math.max(...poly.map(p => p[1])) + 6)}) (layer "Cmts.User") (effects (font (size 1 1) (thickness 0.15)) (justify left)))\n${fps.join('\n')}\n)\n`;
}
function dxfOut(ents) { return ['0', 'SECTION', '2', 'HEADER', '9', '$INSUNITS', '70', '4', '0', 'ENDSEC', '0', 'SECTION', '2', 'ENTITIES', ...ents.flat(), '0', 'ENDSEC', '0', 'EOF'].join('\n') + '\n'; }
const dxLine = (layer, a, b) => ['0', 'LINE', '8', layer, '10', f2(a[0]), '20', f2(a[1]), '30', '0', '11', f2(b[0]), '21', f2(b[1]), '31', '0'];
const dxCircle = (layer, c, r) => ['0', 'CIRCLE', '8', layer, '10', f2(c[0]), '20', f2(c[1]), '30', '0', '40', f2(r)];
const dxText = (layer, p, h, s) => ['0', 'TEXT', '8', layer, '10', f2(p[0]), '20', f2(p[1]), '30', '0', '40', f2(h), '1', String(s).replace(/\n/g, ' ')];
const dxPoly = (layer, pts) => pts.map((a, i) => dxLine(layer, a, pts[(i + 1) % pts.length]));
const dxRect = (layer, b) => dxPoly(layer, [[b[0], b[1]], [b[3], b[1]], [b[3], b[4]], [b[0], b[4]]]);
export function roundedPts(w, l, r, n) { const out = [], k = n || 8, rr = Math.min(r, w / 2, l / 2); [[w / 2 - rr, l / 2 - rr, 0], [-w / 2 + rr, l / 2 - rr, 90], [-w / 2 + rr, -l / 2 + rr, 180], [w / 2 - rr, -l / 2 + rr, 270]].forEach(([cx, cy, a0]) => { for (let i = 0; i <= k; i++) { const a = (a0 + 90 * i / k) * Math.PI / 180; out.push([cx + rr * Math.cos(a), cy + rr * Math.sin(a)]); } }); return out; }
export function dxfBoard(res) {
  const refs = designators(res.items), ents = [...dxPoly('BOARD_OUTLINE', res.board.poly)];
  res.items.filter(it => it.half === 'A' && (it.mount === 'boardTop' || it.mount === 'boardBottom')).forEach(it => { const L = it.mount === 'boardTop' ? 'TOP_PARTS' : 'BOTTOM_PARTS'; ents.push(...dxRect(L, it.box), dxText(L, [it.box[0] + 0.3, it.box[1] + 0.3], 0.8, refs[it.uid] + ' ' + it.p.mpn)); });
  res.items.filter(it => it.cat === 'antenna' && it.half === 'A').forEach(a => ents.push(...dxRect('ANTENNA_KEEPOUT', [a.box[0] - 3, a.box[1] - 3, 0, a.box[3] + 3, a.box[4] + 3, 0])));
  ents.push(...dxPoly('HOUSING_INNER', roundedPts(res.g.iw, res.g.il, res.g.ir)));
  return dxfOut(ents);
}
export function dxfHousing(res) {
  const g = res.g, ents = [...dxPoly('OUTLINE', roundedPts(g.w, g.l, g.r)), ...dxPoly('INNER_WALL', roundedPts(g.iw, g.il, g.ir))];
  res.items.filter(i => i.half === 'A' && i.mount === 'back').forEach(i => ents.push(i.role === 'fingerprint' ? dxRect('BACK_WINDOWS', i.box) : dxCircle('BACK_WINDOWS', [i.x, i.y], Math.max(0.75, Math.min(i.sx, i.sy) / 2 - 0.9))));
  res.items.filter(i => i.half === 'A').forEach(i => { i.mount === 'edgeBottom' && ents.push(...dxRect('PORTS', [i.x - 4.7, -g.l / 2 - 0.5, 0, i.x + 4.7, -g.l / 2 + g.wall + 0.5, 0])); i.mount === 'edgeRight' && ents.push(...dxRect('KEYS', [g.w / 2 - g.wall - 0.5, i.y - i.sy / 2 - 0.5, 0, g.w / 2 + 0.5, i.y + i.sy / 2 + 0.5, 0])); i.mount === 'edgeLeft' && ents.push(...dxRect('SIM', [-g.w / 2 - 0.5, i.y - i.sy / 2, 0, -g.w / 2 + g.wall + 0.5, i.y + i.sy / 2, 0])); });
  ents.push(dxText('NOTES', [-g.w / 2, -g.l / 2 - 8], 2, 'Amni-Phone Studio ' + res.d.name + ' housing plan, mm. ' + MATERIALS[g.mat].name + ', wall ' + g.wall + ', floor ' + g.floor + ', height ' + f2(g.t - g.glassT - g.adhT)));
  return dxfOut(ents);
}
export function drawingSVG(res) {
  const g = res.g, d = res.d, gap = 26, s = 2.2, bump = res.bump || 0, T = g.t;
  const W = g.w * s, Lh = g.l * s, Ts = T * s, B = bump * s;
  const fx = 40, fy = 60, sx = fx + W + gap * s, tx = fx, ty = fy + Lh + gap * s;
  const open = d.form !== 'slab';
  const ow = open ? (res.G && !res.G.book ? g.w * s + 40 : 2 * g.w * s + 3) : 0;
  const totalW = sx + Ts + B + 60 + (open ? ow + gap * s : 0), totalH = Math.max(ty + Ts + B + 120, open && res.G && !res.G.book ? fy + (2 * g.l + 4) * s + 90 : 0);
  const rp = (x, y, w, h, r) => `<rect x="${f2(x)}" y="${f2(y)}" width="${f2(w)}" height="${f2(h)}" rx="${f2(r || 0)}"/>`;
  const dim = (x1, y1, x2, y2, label, off, vert) => { const o = off || 12; return vert ? `<g class="dim"><line x1="${f2(x1 + o)}" y1="${f2(y1)}" x2="${f2(x2 + o)}" y2="${f2(y2)}"/><line x1="${f2(x1 + 2)}" y1="${f2(y1)}" x2="${f2(x1 + o + 3)}" y2="${f2(y1)}"/><line x1="${f2(x2 + 2)}" y1="${f2(y2)}" x2="${f2(x2 + o + 3)}" y2="${f2(y2)}"/><text x="${f2(x1 + o + 4)}" y="${f2((y1 + y2) / 2)}" transform="rotate(90 ${f2(x1 + o + 4)} ${f2((y1 + y2) / 2)})" text-anchor="middle">${label}</text></g>` : `<g class="dim"><line x1="${f2(x1)}" y1="${f2(y1 - o)}" x2="${f2(x2)}" y2="${f2(y2 - o)}"/><line x1="${f2(x1)}" y1="${f2(y1 - 2)}" x2="${f2(x1)}" y2="${f2(y1 - o - 3)}"/><line x1="${f2(x2)}" y1="${f2(y2 - 2)}" x2="${f2(x2)}" y2="${f2(y2 - o - 3)}"/><text x="${f2((x1 + x2) / 2)}" y="${f2(y1 - o - 3)}" text-anchor="middle">${label}</text></g>`; };
  const X = x => fx + (x + g.w / 2) * s, Y = y => fy + (g.l / 2 - y) * s;
  const front = [`<g class="body">${rp(fx, fy, W, Lh, g.r * s)}</g>`, `<g class="thin">${rp(fx + g.wall * s, fy + g.wall * s, g.iw * s, g.il * s, g.ir * s)}</g>`];
  const disp = res.items.find(i => i.role === 'display');
  disp && front.push(`<g class="hidden">${rp(X(disp.box[0]), Y(disp.box[4]), disp.sx * s, disp.sy * s, 2)}</g>`);
  res.items.filter(i => i.half === 'A' && ['back', 'front', 'edgeRight', 'edgeLeft', 'edgeBottom'].includes(i.mount)).forEach(i => front.push(i.mount === 'back' || i.mount === 'front' ? `<circle class="hidden" cx="${f2(X(i.x))}" cy="${f2(Y(i.y))}" r="${f2(Math.min(i.sx, i.sy) / 2 * s)}"/>` : `<g class="thin">${rp(X(i.box[0]), Y(i.box[4]), i.sx * s, i.sy * s, 0.5)}</g>`));
  front.push(dim(fx, fy, fx + W, fy, f2(g.w)), dim(fx + W, fy, fx + W, fy + Lh, f2(g.l), 10, true));
  disp && front.push(`<text class="note" x="${f2(fx + 4)}" y="${f2(fy + Lh + 14)}">Panel ${f2(disp.sx)} × ${f2(disp.sy)} (${esc(disp.p.mpn)})</text>`);
  const side = [`<g class="body">${rp(sx, fy, Ts, Lh, 1.5)}</g>`, `<g class="thin">${rp(sx + (T - g.glassT) * s, fy + 0.3 * s, g.glassT * s, Lh - 0.6 * s, 0.5)}</g>`];
  const backs = res.items.filter(i => i.half === 'A' && i.mount === 'back');
  B > 0 && backs.length && side.push(`<g class="body">${rp(sx - B, Y(Math.max(...backs.map(i => i.box[4])) + 1.6), B + 0.5, (Math.max(...backs.map(i => i.box[4])) - Math.min(...backs.map(i => i.box[1])) + 3.2) * s, 1)}</g>`, dim(sx - B, fy + Lh, sx, fy + Lh, 'island ' + f2(bump), -14));
  res.items.filter(i => i.half === 'A' && i.mount === 'edgeRight').forEach(i => side.push(`<g class="thin">${rp(sx + (i.z) * s, Y(i.box[4]), i.sz * s, i.sy * s, 0.5)}</g>`));
  side.push(dim(sx, fy, sx + Ts, fy, f2(T)));
  const top = [`<g class="body">${rp(tx, ty, W, Ts, 1.5)}</g>`];
  res.items.filter(i => i.half === 'A' && i.mount === 'edgeBottom').forEach(i => top.push(`<g class="thin">${rp(X(i.x) - 4.7 * s, ty + Ts - (i.z + i.sz / 2 + 1.8) * s, 9.4 * s, 3.6 * s, 1.8 * s)}</g>`));
  res.items.filter(i => i.half === 'A' && i.role === 'speaker').forEach(i => [-2, -1, 0, 1, 2].forEach(k => top.push(`<circle class="thin" cx="${f2(X(i.x + k * 1.8))}" cy="${f2(ty + Ts - (i.z + i.sz / 2) * s)}" r="${f2(0.55 * s)}"/>`)));
  top.push(dim(tx, ty + Ts, tx + W, ty + Ts, 'bottom edge', -18));
  const G = res.G, flip = G && !G.book, lo = G && G.outer ? G.leafT + 0.3 : 0, ox = sx + Ts + B + gap * s, oW = (flip ? g.w + 2 * lo : 2 * g.w + (G ? G.flatGap : 1.2)) * s, oL = (flip ? 2 * g.l + (G ? G.flatGap : 1.2) : g.l + 2 * lo) * s;
  const leaves = G && G.outer ? [-1, 1].map(sg => flip ? rp(ox + (sg < 0 ? 0 : oW - lo * s), fy + (g.l - G.inset - G.leafW / 2) * s, G.leafT * s, (G.leaf + G.leafW) * s, 1) : rp(ox + (g.w - G.inset - G.leafW / 2) * s, fy + (sg < 0 ? 0 : oL - lo * s), (G.leaf + G.leafW) * s, G.leafT * s, 1)).join('') : '';
  const openV = open ? [`<g class="body">${flip ? rp(ox + lo * s, fy, g.w * s, g.l * s, g.r * s) + rp(ox + lo * s, fy + (g.l + G.flatGap) * s, g.w * s, g.l * s, g.r * s) : rp(ox, fy + lo * s, g.w * s, g.l * s, g.r * s) + rp(ox + (g.w + (G ? G.flatGap : 1.2)) * s, fy + lo * s, g.w * s, g.l * s, g.r * s)}${leaves}</g>`, dim(ox, fy, ox + oW, fy, 'open ' + f2(oW / s)), dim(ox + oW, fy, ox + oW, fy + oL, f2(oL / s), 10, true)] : [];
  const title = `<g class="title"><rect x="${f2(totalW - 330)}" y="${f2(totalH - 70)}" width="310" height="56"/><text x="${f2(totalW - 320)}" y="${f2(totalH - 50)}" class="t1">${esc(d.name)}</text><text x="${f2(totalW - 320)}" y="${f2(totalH - 34)}">AMNI-SCIENT · Phone Studio · ${esc(FORMS[d.form].name)} · units mm · scale ${s}:1 on screen</text><text x="${f2(totalW - 320)}" y="${f2(totalH - 20)}">Third-angle: front, right side, bottom · ${esc(MATERIALS[g.mat].name)}</text></g>`;
  const labels = `<text class="lab" x="${f2(fx)}" y="${f2(fy - 30)}">FRONT</text><text class="lab" x="${f2(sx)}" y="${f2(fy - 30)}">RIGHT SIDE</text><text class="lab" x="${f2(tx)}" y="${f2(ty + Ts + 34)}">BOTTOM</text>${open ? `<text class="lab" x="${f2(sx + Ts + B + gap * s)}" y="${f2(fy - 30)}">OPEN</text>` : ''}`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${f2(totalW)} ${f2(totalH)}" width="${f2(totalW)}" height="${f2(totalH)}" font-family="Archivo, sans-serif" font-size="9"><style>.body rect{fill:none;stroke:#1a1a1a;stroke-width:1.2}.thin rect,.thin circle,circle.thin{fill:none;stroke:#444;stroke-width:.6}.hidden,.hidden rect{fill:none;stroke:#777;stroke-width:.5;stroke-dasharray:3 2}.dim line{stroke:#8A6318;stroke-width:.5}.dim text{fill:#8A6318;font-family:'Cascadia Code',ui-monospace,monospace;font-size:8px}.lab{font-weight:700;letter-spacing:.14em;fill:#1a1a1a}.note{fill:#555}.title rect{fill:none;stroke:#1a1a1a}.title text{fill:#1a1a1a}.t1{font-weight:700;font-size:12px}</style><rect width="100%" height="100%" fill="#fff"/>${labels}${front.join('')}${side.join('')}${top.join('')}${openV.join('')}${title}</svg>`;
}
export function dxfLeaf(res) {
  const G = res.G; if (!G || !G.outer) return dxfOut([dxText('NOTES', [0, 0], 2, 'No outer hinge in this design')]);
  const L = G.leaf, w = G.leafW, arc = (cx, a0, a1) => { const pts = []; for (let i = 0; i <= 16; i++) { const a = (a0 + (a1 - a0) * i / 16) * Math.PI / 180; pts.push([cx + w / 2 * Math.cos(a), w / 2 * Math.sin(a)]); } return pts; }, outline = [...arc(L, -90, 90), ...arc(0, 90, 270)];
  return dxfOut([...dxPoly('LEAF_OUTLINE', outline), dxCircle('PIN_HOLES', [0, 0], G.pinD / 2 + 0.01), dxCircle('PIN_HOLES', [L, 0], G.pinD / 2 + 0.01), dxText('NOTES', [-w, -w * 1.6], 1.2, `Amni outer hinge leaf x2: ${L} mm pin-to-pin, ${w} mm wide, ${G.leafT} mm ${G.leafMat.name}; pin holes ${G.pinD} mm + 0.01 slip fit; deburr, passivate. Pins ${G.pinD} mm into blind side-wall bosses ${K.pinEngage} mm deep.`)]);
}
export function stackSVG(res, cut, axis) {
  const g = res.g, ax = axis === 'x' ? 'x' : 'y', c = cut || 0, s = 6, zx = 3, pad = 34, len = ax === 'y' ? g.w : g.l, top = Math.max(0, res.bump || 0);
  const hit = res.items.filter(i => i.half === 'A' && (ax === 'y' ? i.box[1] <= c && i.box[4] >= c : i.box[0] <= c && i.box[3] >= c)).sort((a, b) => a.z - b.z);
  const W = len * s + pad * 2 + 60, Hs = (g.t + top) * s * zx, rowsH = Math.ceil(hit.length / 2) * 13 + 30, H = Hs + pad * 2 + rowsH;
  const X = v => pad + (v + len / 2) * s, Z = z => pad + (g.t - z) * s * zx;
  const color = { display: '#20252c', display_ref: '#20252c', cover_glass: '#9fc6e0', cell: '#b9bec6', cell_custom: '#b9bec6', som: '#5d6671', camera: '#3a3f47', camera_front: '#3a3f47', antenna: '#c98a3a', thermal: '#d2b27a', qi_coil: '#b87333', nfc_coil: '#b87333', speaker: '#4a5058', usbc: '#c4c8ce', seal_usbc: '#c4c8ce' };
  const col = i => color[i.cat] || '#7d8691';
  const rects = hit.map(i => { const a = ax === 'y' ? i.box[0] : i.box[1], b = ax === 'y' ? i.box[3] : i.box[4]; return `<rect x="${f2(X(a))}" y="${f2(Z(i.z + i.sz))}" width="${f2((b - a) * s)}" height="${f2(Math.max(0.8, i.sz * s * zx))}" fill="${col(i)}" fill-opacity="${i.cat === 'cover_glass' ? 0.45 : 0.9}" stroke="#101216" stroke-width=".5"><title>${esc(i.name + ' ' + i.p.mpn + ' z ' + f2(i.z) + '–' + f2(i.z + i.sz))}</title></rect>`; });
  const xs = res.board.poly.map(p => ax === 'y' ? p[0] : p[1]), ys = res.board.poly.map(p => ax === 'y' ? p[1] : p[0]);
  const inBoard = Math.min(...ys) <= c && Math.max(...ys) >= c;
  const boardR = inBoard ? `<rect x="${f2(X(Math.min(...xs)))}" y="${f2(Z(res.board.z + res.board.t))}" width="${f2((Math.max(...xs) - Math.min(...xs)) * s)}" height="${f2(res.board.t * s * zx)}" fill="#2f6b4f" stroke="#101216" stroke-width=".5"><title>Carrier PCB ${f2(res.board.t)} mm</title></rect>` : '';
  const Hh = g.t - g.glassT - g.adhT;
  const shell = `<path d="M${f2(X(-len / 2))} ${f2(Z(Hh))} L${f2(X(-len / 2))} ${f2(Z(0))} L${f2(X(len / 2))} ${f2(Z(0))} L${f2(X(len / 2))} ${f2(Z(Hh))} L${f2(X(len / 2 - g.wall))} ${f2(Z(Hh))} L${f2(X(len / 2 - g.wall))} ${f2(Z(g.floor))} L${f2(X(-len / 2 + g.wall))} ${f2(Z(g.floor))} L${f2(X(-len / 2 + g.wall))} ${f2(Z(Hh))} Z" fill="#8d949e" fill-opacity=".55" stroke="#101216" stroke-width=".6"/>`;
  const glass = `<rect x="${f2(X(-len / 2 + 0.3))}" y="${f2(Z(g.t))}" width="${f2((len - 0.6) * s)}" height="${f2(g.glassT * s * zx)}" fill="#9fc6e0" fill-opacity=".45" stroke="#101216" stroke-width=".5"/><rect x="${f2(X(-len / 2 + 0.3))}" y="${f2(Z(g.t - g.glassT))}" width="${f2((len - 0.6) * s)}" height="${f2(g.adhT * s * zx)}" fill="#62b0e8" fill-opacity=".5"/>`;
  const legend = hit.map((i, k) => `<g transform="translate(${f2(pad + (k % 2) * (len * s / 2 + 20))} ${f2(Hs + pad * 2 + 8 + Math.floor(k / 2) * 13)})"><rect width="9" height="9" fill="${col(i)}" stroke="#101216" stroke-width=".4"/><text x="13" y="8" font-size="9.5" fill="currentColor">${esc(f2(i.z) + '–' + f2(i.z + i.sz) + ' mm  ' + i.name + ' (' + (i.p.mpn || '') + ')')}</text></g>`).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${f2(W)} ${f2(H)}" width="100%" font-family="Archivo, sans-serif" font-size="9" style="color:currentColor"><text x="${pad}" y="16" font-size="10" font-weight="700" letter-spacing="1.2" fill="currentColor">SECTION AT ${ax === 'y' ? 'Y' : 'X'} = ${f2(c)} mm · thickness exaggerated ×${zx}</text>${shell}${glass}${boardR}${rects.join('')}<g stroke="#C89B4E" stroke-width=".7"><line x1="${f2(X(len / 2) + 10)}" y1="${f2(Z(0))}" x2="${f2(X(len / 2) + 10)}" y2="${f2(Z(g.t))}"/><line x1="${f2(X(len / 2) + 6)}" y1="${f2(Z(0))}" x2="${f2(X(len / 2) + 14)}" y2="${f2(Z(0))}"/><line x1="${f2(X(len / 2) + 6)}" y1="${f2(Z(g.t))}" x2="${f2(X(len / 2) + 14)}" y2="${f2(Z(g.t))}"/></g><text x="${f2(X(len / 2) + 16)}" y="${f2((Z(0) + Z(g.t)) / 2 + 3)}" fill="#C89B4E" font-family="ui-monospace,monospace" font-size="10">${f2(g.t)} mm</text>${legend}</svg>`;
}
export function interconnect(res) {
  const it = id => res.items.find(i => i.role === id), rows = [], som = it('som'), sn = (som && som.p.n) || {}, S = som ? som.p.mpn : 'SoM';
  res.items.filter(i => i.cat === 'display').forEach(dd => rows.push(['Display', dd.p.mpn, S, 'MIPI DSI ' + (dd.p.n.lanes || '?') + '-lane + I²C touch + reset/TE', 'FPC → ' + ((it('conn_display') || {}).p || {}).mpn, dd.half === 'B' ? 'crosses hinge via FPC' : '']));
  res.items.filter(i => i.cat === 'camera' || i.cat === 'camera_front').forEach(c => rows.push(['Camera', c.p.mpn, S, 'MIPI CSI-2 ' + (c.p.n.lanes || '?') + '-lane + CCI (I²C) + MCLK', 'FPC → ' + ((it('conn_cam') || {}).p || {}).mpn, '']));
  it('modem') && rows.push(['Cellular', it('modem').p.mpn, S, it('modem').p.n.ifc || 'USB 2.0 / PCIe', 'on board', 'SIM/eSIM + antennas ant_main/ant_div']);
  it('wifi') && rows.push(['Wi-Fi/BT', it('wifi').p.mpn, S, it('wifi').p.n.ifc || 'SDIO / PCIe + UART', 'on board', 'antenna ant_wifi']);
  it('gnss') && rows.push(['GNSS', it('gnss').p.mpn, S, it('gnss').p.n.ifc || 'UART / I²C', 'on board', 'antenna ant_gnss']);
  it('usbc') && rows.push(['USB-C', it('usbc').p.mpn, S + ' USB + ' + ((it('usb_pd') || {}).p || {}).mpn, 'USB 2.0 D±, SuperSpeed if supported, CC1/CC2 → PD controller, VBUS → charger', 'bottom FPC/sub-board', '']);
  it('cell') && rows.push(['Battery', it('cell').p.mpn, ((it('charger') || {}).p || {}).mpn + ' / ' + ((it('fuel_gauge') || {}).p || {}).mpn, 'VBAT, NTC, (ID)', 'Battery B2B → ' + ((it('conn_batt') || {}).p || {}).mpn, 'fuel gauge sense on pack side']);
  ['speaker', 'receiver'].forEach(r => it(r) && rows.push(['Audio out', it(r).p.mpn, S + ' I²S → amp', 'Speaker ±', 'spring contacts / flex', '']));
  ['mic', 'mic2'].forEach(r => it(r) && rows.push(['Audio in', it(r).p.mpn, S, it(r).p.n.ifc || 'PDM', 'flex', '']));
  it('haptic') && rows.push(['Haptics', it('haptic').p.mpn, ((it('haptic_drv') || {}).p || {}).mpn, 'LRA drive ±', 'flex/spring', 'driver on I²C']);
  ['imu', 'als', 'baro', 'mag', 'charger', 'fuel_gauge', 'usb_pd', 'haptic_drv', 'nfc', 'qi_rx'].forEach(r => it(r) && rows.push(['I²C / control', it(r).p.mpn, S, it(r).p.n.ifc || 'I²C + IRQ', 'on board', '']));
  ['btn_power', 'btn_up', 'btn_down'].forEach(r => it(r) && rows.push(['Key', it(r).p.mpn, S, r === 'btn_power' ? 'PWRKEY (module power-on / wake)' : 'GPIO with debounce (' + (r === 'btn_up' ? 'volume up' : 'volume down') + ')', 'side flex', '']));
  it('sim') && rows.push(['SIM', it('sim').p.mpn, ((it('modem') || som || {}).p || {}).mpn, 'USIM (VCC, CLK, IO, RST)', 'on board edge', '']);
  const power = [['USB-C VBUS 5–20 V', ((it('charger') || {}).p || {}).mpn || 'charger', 'VSYS 3.5–4.4 V'], ['VSYS', S, 'module PMIC rails (on SoM)'], ['VSYS', ((it('pmic') || {}).p || {}).mpn || 'buck/LDO', '3.3 V / 1.8 V peripherals'], ['VBAT', ((it('fuel_gauge') || {}).p || {}).mpn || 'fuel gauge', 'coulomb counting'], ...(it('modem') ? [['VBAT/VSYS', it('modem').p.mpn, 'modem VBAT (peak current: see datasheet)']] : [])];
  return { rows, power };
}
export function assemblySteps(res) {
  const has = r => res.items.some(i => i.role === r), g = res.g;
  return [
    'Fabricate and assemble the carrier PCB (both sides), then mate the compute module onto its board-to-board connectors.',
    'Flash and bring up the module on the bench with the display, touch and one camera before the housing exists.',
    `Machine or print the ${MATERIALS[g.mat].name} housing (${f2(g.w)} × ${f2(g.l)} mm, wall ${g.wall} mm, floor ${g.floor} mm); deburr ports; anodize or finish.`,
    res.d.req.ip !== 'none' ? 'Fit acoustic vents and gaskets to speaker, receiver, mic and pressure ports; seat button O-rings or membranes; install the SIM tray gasket.' : 'Fit acoustic meshes to speaker, receiver and mic ports.',
    'Place antennas (flex, adhesive side down) and route coax/flex to the board; keep keep-out zones clear of metal.',
    has('qi_coil') || has('nfc_coil') ? 'Adhere NFC / wireless-charging coils to the floor; then the battery cell on top with stretch-release adhesive.' : 'Adhere the battery cell with stretch-release adhesive, leaving the swell gap above it.',
    'Install rear cameras, flash and bonded camera windows; connect camera FPCs.',
    'Drop the board assembly in, screw down, connect battery, cameras, USB/sub-board and antenna feeds.',
    'Fit side keys and USB-C receptacle (sealed variant if IP-rated); install the speaker, receiver and haptic motor.',
    'Lay the graphite/thermal spreader over the module, connect the display FPC, then bond the display + cover glass with the die-cut adhesive frame' + (res.d.req.ip !== 'none' ? ' and cure/press per the adhesive datasheet.' : '.'),
    res.d.req.ip !== 'none' ? 'Run a pressure-decay leak test on every unit, then IEC 60529 immersion on samples.' : 'Run functional test: display, touch, cameras, audio, radios, charging.',
  ];
}
const tb = (head, body) => `<table><thead><tr>${head.map(h => `<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${body.map(r => `<tr>${r.map(c => `<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
function hingeSection(res) {
  const G = res.G; if (!G) return '';
  const sw = res.sw, ms = res.magnets, ld = res.loads, lk = res.link;
  return `<h2>8a. Hinge, magnets and half-to-half link</h2>${tb(['Item', 'Value'], [['Hinge', G.H.name], ['Opening range', sw ? sw.lo + '°–' + sw.hi + '°' : '—'], ['Shut / open size', res.dims.shut.map(v => f2(v)).join(' × ') + ' / ' + res.dims.open.map(v => f2(v)).join(' × ') + ' mm'], ['Gap shut / flat / back-to-back', `${f2(Math.max(0, G.shutGap))} / ${f2(G.flatGap)} / ${G.backGap > 0 ? f2(G.backGap) : 'n/a'} mm`], ['Minimum swing clearance', sw ? f2(sw.minClear) + ' mm at ' + sw.at + '°' : '—'], ...(G.outer ? [['Leaf', `${G.leaf} mm pin-to-pin × ${G.leafW} mm × ${G.leafT} mm, ${G.leafMat.name}`], ['Pins', `⌀${G.pinD} mm, ${f2(G.pf)} mm under the display face, ${G.inset} mm in from the seam`]] : []), ...(ms && ms.shut.length ? [['Hold shut', `${f2(ms.shutN)} N (need ≥ ${f2(ms.needShut)} N)`]] : []), ...(ms && ms.flat.length ? [['Hold flat', `${f2(ms.flatN)} N (need ≥ ${f2(ms.needFlat)} N)`]] : []), ...(ms && ms.compass ? [['Field at compass', ms.compass.map(c => c.th + '° ' + Math.round(c.ut) + ' µT').join(', ')]] : []), ...(ld ? [['Pin shear / bearing safety factor (30 g drop)', f2(ld.sfShear) + ' / ' + f2(ld.sfBear)]] : []), ...(lk ? [['Link', (lk.kind || 'none') + [...lk.errors, ...lk.warns, ...lk.notes].map(t => ' · ' + t).join('')]] : [])])}<p class="muted">Magnet forces: Akoun &amp; Yonnet cuboid model; fields: dipole sums; swing: 2D section sweep every ${K.swingStep}°. Leaf drawing: export "Hinge leaf (DXF)".</p>`;
}
function boardSection(res) {
  const bs = boardStudy(res), st = bs.stack;
  return `<h2>8b. Main board</h2><p>${esc(res.d.board.path === 'custom' ? 'Custom chip-level board' : 'Module carrier')} · ${st.layers}-layer ${esc(HDI[st.hdi].name)}, ${st.total} mm · fab rules ${esc(bs.fab.name)}</p>${tb(['Interface', 'Need', 'Have'], bs.ifc.rows.map(r => [r.name, r.need, r.have == null ? '—' : r.have]))}${tb(['Rail', 'V', 'W', 'A', 'From', 'Seq'], bs.pwr.rails.map(r => [r.name, f2(r.v), f2(r.w), f2(r.a), r.from, r.seq]))}${tb(['Impedance target', 'Layer', 'Width µm', 'Gap µm', 'Z Ω'], bs.imp.rows.map(r => [r.name, r.layer + (r.ref ? ' → ' + r.ref : ''), r.w != null ? Math.round(r.w * 1000) : '—', r.s != null ? Math.round(r.s * 1000) : '—', r.z != null ? r.z : '—']))}${tb(['Path', 'Engineering weeks', 'Spins', 'Risk'], bs.paths.map(p => [p.name, p.nreWeeks.join('–'), p.spins, p.risk]))}`;
}
function schSection(res, x) {
  const table = (head, body) => `<table><thead><tr>${head.map(h => `<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${body.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`, f = v => v == null ? '—' : String(Math.round(v * 1000) / 1000);
  return [['A', res], ...(res.resB ? [['B', res.resB]] : [])].map(([pc, r]) => { const sc = autoSchematic(r), S = sc.stats, rt = (x.routes || {})[pc];
    return `<h3>${res.resB ? 'Piece ' + pc + ': ' : ''}${esc(r.d.name)}</h3>${table(['Item', 'Value'], [['Components', `${S.ics} ICs/connectors, ${S.passives} passives, ${S.nets} nets, ${S.pins} pins`], ['Pin maps', `${S.datasheet} parts from datasheets, ${S.synth} interface-level placeholders`], ['Checks', `${S.powerOpen} open power pins, ${S.floating} floating inputs, ${S.errors} errors, ${S.warns} warnings`], ['Routing', rt && rt.state === 'done' ? `${rt.completion != null ? rt.completion + '% routed' : 'not routed'}, ${rt.drc ? rt.drc.unconnected + ' unrouted, DRC ' + rt.drc.errors + ' errors' : ''}, ERC ${rt.erc ? rt.erc.errors : '—'} errors; files in ${esc(rt.dir)}` : 'Not run in this session: npm run board-job -- --preset &lt;id&gt; (KiCad + Freerouting on this PC)']])}
<h4>I²C buses</h4>${table(['Bus', 'Devices', 'Pull-up', 'Rp window'], sc.buses.map(b => [esc(b.k), esc(b.devs.map(d => d.ref + ' ' + d.mpn + ' @' + d.addr).join(', ')), f(b.calc.rp) + ' Ω', b.calc.rmin + '–' + b.calc.rmax + ' Ω (Cb ' + b.calc.cb_pf + ' pF)']))}
<h4>Regulators</h4>${table(['Ref', 'Rail', 'V', 'Load', 'Part', 'Divider'], sc.regs.map(g => [esc(g.ref), esc(g.rail), f(g.v), g.ma + ' mA', esc(g.topo + ' ' + g.part), g.div ? `${f(g.div.r1)} / ${f(g.div.r2)} Ω → ${f(g.div.vo)} V` : 'fixed']))}
<h4>Passives (BOM)</h4>${table(['Refs', 'Qty', 'Kind', 'Value', 'MPN', 'Size', 'Note'], sc.bomP.map(b => [esc(b.refs.slice(0, 12).join(' ') + (b.refs.length > 12 ? '…' : '')), b.refs.length, esc(b.kind), esc(b.value), `<span class="mono">${esc(b.mpn || 'select')}</span>`, esc(b.size || ''), b.dnp ? 'DNP' : '']))}
${sc.checks.filter(c => c.sev !== 'info').length ? '<h4>Open items</h4><ul>' + sc.checks.filter(c => c.sev !== 'info').map(c => `<li>${esc(c.text)}</li>`).join('') + '</ul>' : ''}`; }).join('');
}
export function buildPackHTML(res, extra) {
  const x = extra || {}, d = res.d, q = d.req, rows = bomRows(res), ic = interconnect(res), DB = db();
  const money = v => v == null ? '—' : '$' + v.toFixed(2);
  const table = (head, body) => `<table><thead><tr>${head.map(h => `<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${body.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
  const link = (u, t) => u ? `<a href="${esc(u)}">${esc(t || 'link')}</a>` : '—';
  const certs = (DB.parts || []).filter(p => p.cat === 'cert'), path = DB.path || [], tests = DB.tests || [];
  const sum = [1, 100, 1000].map(k => rows.reduce((s, r) => s + (r[k === 1 ? 'q1' : k === 100 ? 'q100' : 'q1k'] || 0) * r.qty, 0));
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(d.name)} build pack</title><style>body{font-family:Archivo,system-ui,sans-serif;color:#101216;background:#fff;margin:32px;line-height:1.45;font-size:13px}h1{font-size:22px;margin:0}h2{font-size:15px;margin:28px 0 8px;border-bottom:1px solid #CBC7BE;padding-bottom:4px;letter-spacing:.04em}table{border-collapse:collapse;width:100%;font-size:11.5px;margin:6px 0}th,td{border:1px solid #E0DED8;padding:4px 6px;text-align:left;vertical-align:top}th{background:#F3F2EF}td.n,.mono{font-family:'Cascadia Code',ui-monospace,monospace}.k{color:#8A6318;font-weight:700;letter-spacing:.12em;font-size:11px}.muted{color:#767B84}ol li{margin:3px 0}.sheet svg{max-width:100%;height:auto;border:1px solid #E0DED8}@media print{body{margin:12mm}h2{break-after:avoid}.sheet{break-inside:avoid}}</style></head><body>
<div class="k">AMNI-SCIENT · PHONE STUDIO · BUILD PACK</div><h1>${esc(d.name)}</h1><p class="muted">${esc(FORMS[d.form].name)} · generated ${new Date().toISOString().slice(0, 10)} · parts checked ${esc(DB.checked || '')} · ${res.buildable ? 'all parts are purchasable or RFQ' : 'contains OEM-only / reference parts: not buildable as is'}</p>
<h2>1. Summary</h2>${table(['Metric', 'Value'], [['Housing', `${f2(res.g.w)} × ${f2(res.g.l)} × ${f2(res.g.t)} mm${d.form !== 'slab' ? ' per half' : ''}, ${esc(MATERIALS[res.g.mat].name)}, ${esc(BACKS[res.g.back].name)}`], ['Mass', res.mass.toFixed(0) + ' g'], ['Battery', res.power.wh.toFixed(1) + ' Wh'], ['Screen-on (model)', res.power.sot.toFixed(1) + ' h at ' + res.power.pOn.toFixed(2) + ' W'], ['Standby (model)', res.power.standby.toFixed(1) + ' days'], ['Ingress target / achieved', esc(IP_LEVELS[q.ip].name) + ' / ' + esc(IP_LEVELS[res.ip.achieved].name)], ['Parts cost at q1 / q100 / q1k (published prices only)', sum.map(v => '$' + v.toFixed(0)).join(' / ')], ['Unit cost used (qty ' + q.qty + ', incl. quoted fab)', '$' + res.cost.unit.toFixed(0) + (res.cost.unknown ? ` + ${res.cost.unknown} unpriced line(s)` : '')], ['Open checks', res.errors + ' errors, ' + res.warns + ' warnings']])}
<h2>2. Bill of materials</h2>${table(['Ref', 'Role', 'Manufacturer', 'MPN', 'Qty', 'Status', 'q1', 'q100', 'q1k', 'Supplier', 'Datasheet', 'Checked'], rows.map(r => [esc(r.ref), esc(r.role), esc(r.mfr), `<span class="mono">${esc(r.mpn)}</span>`, r.qty, esc(r.status), money(r.q1), money(r.q100), money(r.q1k), link(r.url, r.vendor), link(r.datasheet, 'PDF'), esc(r.checked)]))}
<h2>3. RFQ list</h2>${table(['Role', 'Manufacturer', 'MPN', 'Why', 'Contact'], rfqRows(res).map(r => [esc(r.role), esc(r.mfr), esc(r.mpn), r.status === 'oem' ? 'OEM-only' : r.at == null ? 'No published price' : 'MOQ/custom', link(r.url)]))}
<h2>4. Interconnect</h2>${table(['Function', 'Part', 'To', 'Signals', 'Via', 'Note'], ic.rows.map(r => r.map(c => esc(c))))}<h3>Power tree</h3>${table(['From', 'Through', 'To'], ic.power.map(r => r.map(c => esc(c))))}
<h2>5. Assembly order</h2><ol>${assemblySteps(res).map(s => `<li>${esc(s)}</li>`).join('')}</ol>
<h2>6. Ingress protection plan</h2>${table(['Opening', 'Method', 'Parts / rule', 'Rated'], res.ip.openings.map(o => [esc(o.name), o.selfRated ? 'Part is rated' : esc(o.tactic ? o.tactic.name : '—'), esc(o.tactic ? [(o.tactic.parts || []).join(', '), o.tactic.design_rule].filter(Boolean).join(' · ') : ''), o.ok ? 'yes' : '<b>no</b>']))}${tests.length ? table(['Test', 'Requirement', 'Source'], tests.map(t => [esc(t.name || t.id), esc(t.requirement || t.method || ''), link((t.source || [])[0])])) : ''}
<h2>7. Certification checklist</h2>${certs.length ? table(['Item', 'Scope', 'Typical cost', 'Time', 'Source'], certs.map(c => [esc(c.name), esc((c.specs && (c.specs.scope || c.specs.what)) || c.notes || ''), esc(c.price && (c.price.note || '')), esc((c.specs && c.specs.weeks) || (c.price && c.price.lead_time) || ''), link((c.source || [])[0])])) : '<p class="muted">No certification data loaded.</p>'}
<h2>8. Prototype path</h2>${path.length ? table(['Stage', 'What', 'Cost (USD)', 'Weeks', 'Source'], path.map(p => [esc(p.stage), esc(p.what), p.typical_cost_usd ? '$' + p.typical_cost_usd.join('–$') : '—', p.typical_weeks ? p.typical_weeks.join('–') : '—', link((p.source || [])[0])])) : '<p class="muted">No path data loaded.</p>'}
${hingeSection(res)}${boardSection(res)}<h2>8c. Auto-wired main board</h2>${schSection(res, x)}<h2>9. Drawings</h2><div class="sheet">${x.drawing || ''}</div><div class="sheet">${x.stack || ''}</div>
<h2>10. Sources</h2><ul>${Object.values(SRC).map(s => `<li>${esc(s.name)} — ${link(s.url, s.url)}</li>`).join('')}</ul></body></html>`;
}
