import { stackup, impedance, fabOf, HDI } from './board.js';
import { autoSchematic, SHEETS, fmtVal } from './schematic.js';
const f2 = v => (Math.round(v * 100) / 100).toFixed(2), r2 = v => Math.round(v * 100) / 100, r3 = v => Math.round(v * 1000) / 1000, q = s => '"' + String(s == null ? '' : s).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ') + '"', G = v => Math.round(v / 1.27) * 1.27;
let seed = 1;
const mix = x => { x = Math.imul(x ^ (x >>> 16), 0x85ebca6b); x = Math.imul(x ^ (x >>> 13), 0xc2b2ae35); return (x ^ (x >>> 16)) >>> 0; }, uid = () => { seed++; const w = [1, 2, 3, 4].map(k => mix(seed * 4 + k + 0x9e3779b9).toString(16).padStart(8, '0')).join(''); return `${w.slice(0, 8)}-${w.slice(8, 12)}-4${w.slice(13, 16)}-a${w.slice(17, 20)}-${w.slice(20, 32)}`; };
const safe = s => String(s || 'X').replace(/[^A-Za-z0-9_.+-]+/g, '_').slice(0, 48);
export const CLASSES = { DDR_40: 'ddr40', MIPI_100: 'mipi100', USB_90: 'usb90', PCIE_85: 'pcie85', RF_50: 'se50' };
const TYPE = { power_in: 'power_in', power_out: 'power_out', gnd: 'power_in', in: 'input', out: 'output', io: 'bidirectional', od: 'open_collector', passive: 'passive', analog: 'passive', nc: 'no_connect', bidirectional: 'bidirectional', input: 'input', output: 'output', tri_state: 'tri_state' };
const PASS = { '0201': [0.32, 0.4, 0.36], '0402': [0.48, 0.56, 0.62], '0603': [0.775, 0.9, 0.95], '0805': [0.95, 1.0, 1.45] };
const isGrid = pins => pins.length > 3 && pins.every(p => /^[A-HJ-NPR-Y]{1,2}\d{1,2}$/.test(p.num) || /^(EP|PAD|TP)\d*$/i.test(p.num));
const rowIdx = s => { const L = 'ABCDEFGHJKLMNPRTUVWY', a = s.match(/^([A-Z]+)/)[1]; return a.length === 1 ? L.indexOf(a) : (L.indexOf(a[0]) + 1) * L.length + L.indexOf(a[1]); };
const snapP = v => [0.35, 0.4, 0.5, 0.65, 0.8, 1.0, 1.27].reduce((b, x) => Math.abs(x - v) < Math.abs(b - v) ? x : b, 0.5);
export function geomOf(c) {
  const pk = String((c.pm && c.pm.package) || (c.part && c.part.specs && c.part.specs.package) || c.size || ''), it = c.it, dims = (c.part && c.part.dims) || (it && it.p && it.p.dims) || null, uniq = [...new Map(c.pins.map(p => [p.num, p])).values()], n = uniq.length;
  const bodyM = pk.match(/(\d+(?:\.\d+)?)\s*[x×]\s*(\d+(?:\.\d+)?)(?:\s*[x×]\s*\d+(?:\.\d+)?)?\s*mm/), pitchM = pk.match(/(0\.\d+)\s*mm\s*pitch|pitch\s*(0\.\d+)|(0\.[3-8]\d?)\s*mm(?!\s*[x×])/i);
  let bw = bodyM ? Number(bodyM[1]) : dims && dims[0] ? dims[0] : it ? it.sx : 2, bh = bodyM ? Number(bodyM[2]) : dims && dims[1] ? dims[1] : it ? it.sy : 2, pitch = pitchM ? Number(pitchM[1] || pitchM[2] || pitchM[3]) : null, pads = [], kind = 'dual', approx = false;
  if (c.role === 'passive') { const sz = PASS[c.size] ? c.size : c.kind === 'ind' ? '0603' : '0201', [x, w, h] = PASS[sz]; if (c.kind === 'tp') return { pads: [{ num: '1', x: 0, y: 0, w: 1.0, h: 1.0, shape: 'circle' }], bw: 1.2, bh: 1.2, kind: 'tp' }; return { pads: [{ num: '1', x: -x, y: 0, w, h, shape: 'roundrect' }, { num: '2', x, y: 0, w, h, shape: 'roundrect' }], bw: 2 * x + w + 0.1, bh: h + 0.1, kind: 'chip' }; }
  const offB = ['speaker', 'receiver', 'haptic', 'qi_coil', 'nfc_coil', 'flash', 'btn_power', 'btn_up', 'btn_down'].includes(c.role) || /^ant_/.test(c.role) || (it && it.mount && !['boardTop', 'boardBottom'].includes(it.mount) && n <= 6 && !c.fpc);
  if (offB) { uniq.forEach((p, i) => pads.push({ num: p.num, x: r3((i - (n - 1) / 2) * 1.5), y: 0, w: 0.9, h: 0.9, shape: 'rect' })); return { pads, bw: r3(n * 1.5 + 0.2), bh: 1.3, kind: 'contacts', pitch: 1.5, approx: false, offB: true }; }
  if (isGrid(uniq)) { const gp = uniq.filter(p => /^[A-Z]/.test(p.num) && !/^(EP|PAD|TP)/i.test(p.num)), rows = Math.max(...gp.map(p => rowIdx(p.num))) + 1, cols = Math.max(...gp.map(p => Number(p.num.match(/\d+$/)[0]))); pitch = pitch || snapP(Math.min(bw / Math.max(1, cols), bh / Math.max(1, rows))); const d = r3(Math.max(0.18, pitch * 0.5)); gp.forEach(p => pads.push({ num: p.num, x: r3((Number(p.num.match(/\d+$/)[0]) - 1 - (cols - 1) / 2) * pitch), y: r3((rowIdx(p.num) - (rows - 1) / 2) * pitch), w: d, h: d, shape: 'circle' })); bw = Math.max(bw, cols * pitch), bh = Math.max(bh, rows * pitch); kind = 'grid'; }
  else if ((['soc', 'som', 'lpddr', 'ufs', 'soc_pmic', 'mcu'].includes(c.role) && n > 24) || (n > 2 * (bw + bh) / 0.4 && !c.fpc && !['usbc', 'sim', 'conn_display', 'conn_cam', 'conn_batt'].includes(c.role))) { const cols = Math.max(1, Math.round(Math.sqrt(n * bw / bh))), rows = Math.ceil(n / cols); pitch = Math.max(0.35, Math.floor(Math.min(bw / cols, bh / rows) * 100) / 100); const d = r3(Math.max(0.18, Math.min(0.5, pitch * 0.5))); uniq.forEach((p, i) => pads.push({ num: p.num, x: r3((i % cols - (cols - 1) / 2) * pitch), y: r3((Math.floor(i / cols) - (rows - 1) / 2) * pitch), w: d, h: d, shape: 'circle' })); kind = 'grid'; approx = true; }
  else { const ep = uniq.filter(p => /^(EP|PAD|TP|EPAD|\d+EP)$/i.test(p.num) || /thermal|exposed|^EP$|^PAD$|powerpad/i.test(p.name)), per = uniq.filter(p => !ep.includes(p)), N = per.length, quad = /QFN|LGA-?\d|QFP/i.test(pk) && N >= 8, conn = ['usbc', 'sim', 'conn_display', 'conn_cam', 'conn_batt', 'dock_link'].includes(c.role) || c.fpc, sot = /SOT|SC-?70|SC70|SSOP|SOIC|TSSOP|VSSOP|US8/i.test(pk);
    if (quad) { const nV = Math.max(1, Math.round(N * bh / (2 * (bw + bh)))), nH = Math.max(1, Math.ceil((N - 2 * nV) / 2)), cnt = [nV, nH, N - nV - nH - Math.min(nH, N - 2 * nV - nH) , 0]; cnt[2] = nV; cnt[3] = N - 2 * nV - nH; const L = r3(Math.min(0.6, Math.min(bw, bh) * 0.2)), sideLen = sd => (sd % 2 ? bw : bh) - 2 * L - 0.3, pt = sd => Math.min(pitch || 9, snapP(sideLen(sd) / Math.max(1, cnt[sd])) > sideLen(sd) / Math.max(1, cnt[sd]) ? sideLen(sd) / Math.max(1, cnt[sd]) : snapP(sideLen(sd) / Math.max(1, cnt[sd]))); let i = 0; [0, 1, 2, 3].forEach(sd => { const ps = r3(pt(sd)), W = r3(Math.min(0.35, ps * 0.55)); for (let k = 0; k < cnt[sd] && i < N; k++, i++) { const p = per[i], off = (k - (cnt[sd] - 1) / 2) * ps; pads.push(sd === 0 ? { num: p.num, x: -bw / 2 + L / 2, y: off, w: L, h: W } : sd === 1 ? { num: p.num, x: off, y: bh / 2 - L / 2, w: W, h: L } : sd === 2 ? { num: p.num, x: bw / 2 - L / 2, y: -off, w: L, h: W } : { num: p.num, x: -off, y: -bh / 2 + L / 2, w: W, h: L }); } }); pitch = pitch || r3(pt(0)); kind = 'quad'; }
    else { const s = Math.ceil(N / 2); pitch = pitch || (conn ? snapP(Math.max(bw, bh) * 0.85 / Math.max(1, s)) : snapP(Math.max(bw, bh) * 0.8 / Math.max(1, s))); const horiz = conn && bw >= bh, L = sot ? 0.9 : conn ? 0.7 : 0.55, W = r3(Math.min(0.6, pitch * 0.55)); const span = horiz ? bh : bw; per.forEach((p, i) => { const row = conn ? i % 2 : i < s ? 0 : 1, k = conn ? Math.floor(i / 2) : row === 0 ? i : N - 1 - i, off = (k - (s - 1) / 2) * pitch, e = span / 2 + (sot ? 0.35 : -L / 2 + 0.15); pads.push(horiz ? { num: p.num, x: off, y: row ? e : -e, w: W, h: L } : { num: p.num, x: row ? e : -e, y: off, w: L, h: W }); }); kind = conn ? 'conn' : sot ? 'sot' : 'dual'; approx = conn; }
    ep.forEach((p, i) => pads.push({ num: p.num, x: 0, y: 0, w: r3(Math.max(0.3, Math.min(bw, bh) * 0.45)), h: r3(Math.max(0.3, Math.min(bw, bh) * 0.45)), shape: 'rect', ep: true }));
    !/QFN|SON|DFN|SOT|SC-?70|SSOP|SOIC|TSSOP|VSSOP|US8|BGA|CSP|LGA/i.test(pk) && (approx = true); }
  const minX = Math.min(...pads.map(p => p.x - p.w / 2)), maxX = Math.max(...pads.map(p => p.x + p.w / 2)), minY = Math.min(...pads.map(p => p.y - p.h / 2)), maxY = Math.max(...pads.map(p => p.y + p.h / 2));
  return { pads, bw: r3(Math.max(bw, maxX - minX)), bh: r3(Math.max(bh, maxY - minY)), kind, pitch, approx: approx || !c.pm || c.pm.src !== 'datasheet' };
}
const symName = c => c.role === 'passive' ? ({ res: 'R', cap: 'C', ind: 'L', ferrite: 'FB', tvs: 'D_TVS', tp: 'TP', ntc: 'R' }[c.kind] || 'X') : safe((c.mpn || c.role) + '_' + c.pins.length + 'p' + (c.pm && c.pm.src === 'synth' ? '_iface' : ''));
function symbolDef(c, name) {
  const pins = c.pins, two = c.role === 'passive', stack = new Map(), rows = [];
  pins.forEach(p => { const k = (p.type === 'gnd' || p.type === 'power_in' || p.type === 'power_out') ? p.name + '|' + p.type : null; if (k && stack.has(k)) { stack.get(k).push(p); return; } const arr = [p]; k && stack.set(k, arr); rows.push(arr); });
  if (two) { const out = c.pins.length === 1 ? [`      (pin passive line (at 0 2.54 270) (length 1.27) (name "1" (effects (font (size 1 1)))) (number "1" (effects (font (size 1 1)))))`] : [`      (pin passive line (at 0 3.81 270) (length 1.27) (name "1" (effects (font (size 1 1)))) (number "1" (effects (font (size 1 1)))))`, `      (pin passive line (at 0 -3.81 90) (length 1.27) (name "2" (effects (font (size 1 1)))) (number "2" (effects (font (size 1 1)))))`]; c.pins.forEach((p, i) => { p.sx = 0; p.sy = c.pins.length === 1 ? 2.54 : i ? -3.81 : 3.81; }); return { w: 2.54, h: 7.62, text: `    (symbol ${q('Amni:' + name)} (pin_numbers hide) (pin_names (offset 0) hide) (exclude_from_sim no) (in_bom yes) (on_board yes)\n      (property "Reference" ${q(c.ref.replace(/\d+$/, ''))} (at 2.54 1.27 0) (effects (font (size 1.27 1.27)) (justify left)))\n      (property "Value" ${q(name)} (at 2.54 -1.27 0) (effects (font (size 1.27 1.27)) (justify left)))\n      (property "Footprint" "" (at 0 0 0) (effects (font (size 1.27 1.27)) hide))\n      (property "Datasheet" "" (at 0 0 0) (effects (font (size 1.27 1.27)) hide))\n      (symbol ${q(name + '_0_1')} (rectangle (start -0.762 -2.54) (end 0.762 2.54) (stroke (width 0.254) (type default)) (fill (type none))))\n      (symbol ${q(name + '_1_1')}\n${out.join('\n')}\n      )\n    )` }; }
  const half = Math.ceil(rows.length / 2), H = Math.max(5.08, half * 2.54 + 2.54), W = 30.48, out = [];
  rows.forEach((grp, i) => { const left = i < half, py = G(H / 2 - 2.54 - (left ? i : i - half) * 2.54), px = left ? -W / 2 - 2.54 : W / 2 + 2.54; grp.forEach((p, j) => { p.sx = px; p.sy = py; out.push(`      (pin ${TYPE[p.type] || 'passive'} line (at ${f2(px)} ${f2(py)} ${left ? 0 : 180}) (length 2.54) (name ${q(p.name)} (effects (font (size 1 1)))) (number ${q(p.num)} (effects (font (size 1 1)))))`); }); });
  return { w: W, h: H, text: `    (symbol ${q('Amni:' + name)} (pin_names (offset 0.508)) (exclude_from_sim no) (in_bom yes) (on_board yes)\n      (property "Reference" ${q(c.ref.replace(/\d+$/, ''))} (at 0 ${f2(H / 2 + 1.27)} 0) (effects (font (size 1.27 1.27))))\n      (property "Value" ${q(c.mpn || name)} (at 0 ${f2(-H / 2 - 1.27)} 0) (effects (font (size 1.27 1.27))))\n      (property "Footprint" "" (at 0 0 0) (effects (font (size 1.27 1.27)) hide))\n      (property "Datasheet" "" (at 0 0 0) (effects (font (size 1.27 1.27)) hide))\n      (symbol ${q(name + '_0_1')} (rectangle (start ${f2(-W / 2)} ${f2(H / 2)}) (end ${f2(W / 2)} ${f2(-H / 2)}) (stroke (width 0.254) (type default)) (fill (type background))))\n      (symbol ${q(name + '_1_1')}\n${out.join('\n')}\n      )\n    )` };
}
const FLAG = `    (symbol "Amni:PWR_FLAG" (power) (pin_numbers hide) (pin_names (offset 0) hide) (exclude_from_sim no) (in_bom no) (on_board yes)\n      (property "Reference" "#FLG" (at 0 1.905 0) (effects (font (size 1.27 1.27)) hide))\n      (property "Value" "PWR_FLAG" (at 0 3.81 0) (effects (font (size 1.27 1.27))))\n      (property "Footprint" "" (at 0 0 0) (effects (font (size 1.27 1.27)) hide))\n      (property "Datasheet" "" (at 0 0 0) (effects (font (size 1.27 1.27)) hide))\n      (symbol "PWR_FLAG_0_0" (pin power_out line (at 0 0 90) (length 0) (name "pwr" (effects (font (size 1.27 1.27)))) (number "1" (effects (font (size 1.27 1.27))))))\n      (symbol "PWR_FLAG_0_1" (polyline (pts (xy 0 0) (xy 0 1.27) (xy -1.016 1.905) (xy 0 2.54) (xy 1.016 1.905) (xy 0 1.27)) (stroke (width 0) (type default)) (fill (type none))))\n    )`;
export function kicadProject(res, name, opts) {
  seed = 7; const o = opts || {}, sch = o.sch || autoSchematic(res), proj = safe(name || res.d.name || 'amni-phone'), b = res.d.board, st = stackup(b.layers, b.hdi), fab = fabOf(b.fab), imp = impedance(st, fab), root = uid(), date = new Date().toISOString().slice(0, 10);
  const symDefs = new Map(), fpName = c => safe(c.role === 'passive' ? (c.kind === 'tp' ? 'TP_Pad_1.0mm' : ({ res: 'R', cap: 'C', ind: 'L', ferrite: 'FB', tvs: 'D', ntc: 'R' }[c.kind] || 'X') + '_' + (PASS[c.size] ? c.size : c.kind === 'ind' ? '0603' : '0201')) : (c.mpn || c.role) + '_' + c.pins.length + 'p');
  sch.comps.forEach(c => { const nm = symName(c); c.sym = nm; c.fp = fpName(c); symDefs.has(nm) || symDefs.set(nm, symbolDef(c, nm)); symDefs.get(nm).text && c.pins.forEach(p => { const d = symDefs.get(nm); }); if (!c.pins.every(p => p.sx != null)) { const ref = sch.comps.find(x => x !== c && x.sym === nm && x.pins.every(p => p.sx != null)); ref && c.pins.forEach((p, i) => { p.sx = ref.pins[i].sx; p.sy = ref.pins[i].sy; }); } });
  const sheetIds = Object.keys(SHEETS).filter(k => sch.comps.some(c => c.sheet === k)), sheetU = Object.fromEntries(sheetIds.map(k => [k, uid()])), files = {}, labelShape = t => ({ input: 'input', output: 'output', bidirectional: 'bidirectional', open_collector: 'bidirectional', power_in: 'passive', power_out: 'passive' }[TYPE[t]] || 'passive');
  const flagged = sch.nets.filter(n => n.flag).map(n => n.name);
  sheetIds.forEach((k, si) => {
    const cs = sch.comps.filter(c => c.sheet === k), out = [], used = new Set(); let x = 25.4, y = 25.4, rowH = 0; const maxW = 400;
    cs.sort((a, b) => (a.role === 'passive') - (b.role === 'passive')).forEach(c => { const d = symDefs.get(c.sym); used.add(c.sym); const w = d.w + 45, h = d.h + 12.7; if (x + w > maxW) { x = 25.4; y += rowH; rowH = 0; } const cx = G(x + w / 2), cy = G(y + h / 2); x += w; rowH = Math.max(rowH, h);
      out.push(`  (symbol (lib_id ${q('Amni:' + c.sym)}) (at ${f2(cx)} ${f2(cy)} 0) (unit 1) (exclude_from_sim no) (in_bom ${c.kind === 'tp' ? 'no' : 'yes'}) (on_board yes) (dnp ${c.dnp ? 'yes' : 'no'}) (uuid ${q(uid())})\n    (property "Reference" ${q(c.ref)} (at ${f2(cx + (c.role === 'passive' ? 2.54 : 0))} ${f2(cy - (c.role === 'passive' ? 1.27 : d.h / 2 + 1.27))} 0) (effects (font (size 1.27 1.27))${c.role === 'passive' ? ' (justify left)' : ''}))\n    (property "Value" ${q(c.role === 'passive' ? c.label : c.mpn)} (at ${f2(cx + (c.role === 'passive' ? 2.54 : 0))} ${f2(cy + (c.role === 'passive' ? 1.27 : d.h / 2 + 1.27))} 0) (effects (font (size 1.27 1.27))${c.role === 'passive' ? ' (justify left)' : ''}))\n    (property "Footprint" ${q('Amni:' + c.fp)} (at ${f2(cx)} ${f2(cy)} 0) (effects (font (size 1.27 1.27)) hide))\n    (property "Datasheet" ${q((c.part && c.part.datasheet) || c.url || '')} (at ${f2(cx)} ${f2(cy)} 0) (effects (font (size 1.27 1.27)) hide))\n    (property "MPN" ${q(c.mpn || '')} (at ${f2(cx)} ${f2(cy)} 0) (effects (font (size 1.27 1.27)) hide))\n    (property "Manufacturer" ${q(c.mfr || '')} (at ${f2(cx)} ${f2(cy)} 0) (effects (font (size 1.27 1.27)) hide))\n${c.pins.map(p => `    (pin ${q(p.num)} (uuid ${q(uid())}))`).join('\n')}\n    (instances (project ${q(proj)} (path ${q('/' + root + '/' + sheetU[k])} (reference ${q(c.ref)}) (unit 1))))\n  )`);
      const seen = new Set(); c.pins.forEach(p => { const px = G(cx + p.sx), py = G(cy - p.sy), key = px + ',' + py; if (seen.has(key)) return; seen.add(key); if (p.net) { const left = p.sx < 0 || (c.role === 'passive' && false), ang = c.role === 'passive' ? (p.sy > 0 ? 90 : 270) : left ? 180 : 0; out.push(`  (global_label ${q(p.net)} (shape ${labelShape(p.type)}) (at ${f2(px)} ${f2(py)} ${ang}) (fields_autoplaced yes) (effects (font (size 1 1)) (justify ${ang === 180 || ang === 90 ? 'right' : 'left'})) (uuid ${q(uid())}) (property "Intersheetrefs" "\${INTERSHEET_REFS}" (at ${f2(px)} ${f2(py)} 0) (effects (font (size 1 1)) hide)))`); } else out.push(`  (no_connect (at ${f2(px)} ${f2(py)}) (uuid ${q(uid())}))`); }); });
    k === 'power' && flagged.forEach((nm, i) => { const fx = G(25.4 + i * 25.4), fy = G(y + rowH + 25.4); used.add('PWR_FLAG'); out.push(`  (symbol (lib_id "Amni:PWR_FLAG") (at ${f2(fx)} ${f2(fy)} 0) (unit 1) (exclude_from_sim no) (in_bom no) (on_board yes) (dnp no) (uuid ${q(uid())})\n    (property "Reference" ${q('#FLG0' + (i + 1))} (at ${f2(fx)} ${f2(fy - 1.905)} 0) (effects (font (size 1.27 1.27)) hide))\n    (property "Value" "PWR_FLAG" (at ${f2(fx)} ${f2(fy - 3.81)} 0) (effects (font (size 1.27 1.27))))\n    (property "Footprint" "" (at ${f2(fx)} ${f2(fy)} 0) (effects (font (size 1.27 1.27)) hide))\n    (property "Datasheet" "" (at ${f2(fx)} ${f2(fy)} 0) (effects (font (size 1.27 1.27)) hide))\n    (pin "1" (uuid ${q(uid())}))\n    (instances (project ${q(proj)} (path ${q('/' + root + '/' + sheetU[k])} (reference ${q('#FLG0' + (i + 1))}) (unit 1))))\n  )`, `  (global_label ${q(nm)} (shape passive) (at ${f2(fx)} ${f2(fy)} 270) (fields_autoplaced yes) (effects (font (size 1 1)) (justify right)) (uuid ${q(uid())}) (property "Intersheetrefs" "\${INTERSHEET_REFS}" (at ${f2(fx)} ${f2(fy)} 0) (effects (font (size 1 1)) hide)))`); });
    const libs = [...used].map(nm => nm === 'PWR_FLAG' ? FLAG : symDefs.get(nm).text);
    files[proj + '-' + k + '.kicad_sch'] = `(kicad_sch (version 20250114) (generator "eeschema") (generator_version "9.0") (uuid ${q(sheetU[k])}) (paper "A0")\n  (title_block (title ${q(res.d.name + ' — ' + SHEETS[k])}) (date ${q(date)}) (comment 1 "Generated by Amni-Phone Studio auto-schematic from datasheet pin maps; parts marked _iface use interface-level placeholder pins."))\n  (lib_symbols\n${libs.join('\n')}\n  )\n${out.join('\n')}\n)\n`;
  });
  const sheetsTxt = sheetIds.map((k, i) => { const x = 25.4 + (i % 4) * 63.5, y = 38.1 + Math.floor(i / 4) * 38.1; return `  (sheet (at ${f2(x)} ${f2(y)}) (size 50.8 25.4) (exclude_from_sim no) (in_bom yes) (on_board yes) (dnp no) (fields_autoplaced yes) (stroke (width 0.1524) (type solid)) (fill (color 0 0 0 0.0000)) (uuid ${q(sheetU[k])})\n    (property "Sheetname" ${q(SHEETS[k])} (at ${f2(x)} ${f2(y - 0.7)} 0) (effects (font (size 1.27 1.27)) (justify left bottom)))\n    (property "Sheetfile" ${q(proj + '-' + k + '.kicad_sch')} (at ${f2(x)} ${f2(y + 26)} 0) (effects (font (size 1.27 1.27)) (justify left top)))\n    (instances (project ${q(proj)} (path ${q('/' + root)} (page ${q(String(i + 2))})))))`; });
  files[proj + '.kicad_sch'] = `(kicad_sch (version 20250114) (generator "eeschema") (generator_version "9.0") (uuid ${q(root)}) (paper "A3")\n  (title_block (title ${q(res.d.name + ' — schematic')}) (date ${q(date)}) (comment 1 ${q(`${sch.stats.ics} ICs/connectors, ${sch.stats.passives} passives, ${sch.stats.nets} nets; ${sch.stats.datasheet} parts from datasheet pin maps, ${sch.stats.synth} interface-level`)}) (comment 2 "Hierarchical sheets per subsystem; nets connect through global labels."))\n  (lib_symbols)\n${sheetsTxt.join('\n')}\n  (sheet_instances (path "/" (page "1")))\n)\n`;
  const pcb = pcbOf(res, sch, st, fab, imp, proj);
  const w = (id, def) => { const r = imp.rows.find(x => x.target === id && x.w != null && x.ok) || imp.rows.find(x => x.target === id && x.w != null); return r ? Math.max(fab.min_trace_mm, r3(r.w)) : def; }, gap = id => { const r = imp.rows.find(x => x.target === id && x.s != null); return r ? Math.max(fab.min_space_mm, r3(r.s)) : fab.min_space_mm; };
  const viaD = Math.max(0.35, (fab.min_drill_mm || 0.15) + 0.2), cls = (name, tw, gp, extra) => ({ name, bus_width: 12, clearance: Math.max(fab.min_space_mm, 0.075), diff_pair_gap: gp || fab.min_space_mm, diff_pair_via_gap: 0.25, diff_pair_width: tw, line_style: 0, microvia_diameter: fab.microvia_pad_mm || 0.25, microvia_drill: fab.laser_via_mm || 0.1, pcb_color: 'rgba(0, 0, 0, 0.000)', schematic_color: 'rgba(0, 0, 0, 0.000)', track_width: tw, via_diameter: viaD, via_drill: fab.min_drill_mm || 0.15, wire_width: 6, priority: 0, ...(extra || {}) });
  const classes = [cls('Default', Math.max(fab.min_trace_mm, 0.1)), cls('PWR', 0.2), cls('GND', 0.2), cls('DDR_40', w('ddr40', 0.1)), cls('MIPI_100', w('mipi100', 0.1), gap('mipi100')), cls('USB_90', w('usb90', 0.1), gap('usb90')), cls('PCIE_85', w('pcie85', 0.1), gap('pcie85')), cls('RF_50', w('se50', 0.2)), cls('SDIO', Math.max(fab.min_trace_mm, 0.1))];
  const pats = sch.nets.filter(n => n.cls && n.cls !== 'Default').map(n => ({ netclass: n.cls === 'GND' ? 'GND' : n.cls, pattern: n.name }));
  const pro = { board: { '3dviewports': [], design_settings: { defaults: {}, diff_pair_dimensions: [], drc_exclusions: [], rule_severities: { lib_footprint_mismatch: 'ignore', lib_footprint_issues: 'ignore' }, rules: { min_clearance: fab.min_space_mm, min_track_width: fab.min_trace_mm, min_microvia_diameter: fab.microvia_pad_mm || 0.2, min_microvia_drill: fab.laser_via_mm || 0.1, min_through_hole_diameter: fab.min_drill_mm || 0.15, min_via_diameter: Math.max(0.3, (fab.min_drill_mm || 0.15) + 0.15), min_via_annular_width: 0.1, min_hole_to_hole: 0.2, min_copper_edge_clearance: 0.2, min_hole_clearance: 0.1 }, track_widths: [], via_dimensions: [] }, layer_presets: [], viewports: [] }, boards: [], libraries: { pinned_footprint_libs: [], pinned_symbol_libs: [] }, meta: { filename: proj + '.kicad_pro', version: 1 }, net_settings: { classes, meta: { version: 3 }, net_colors: null, netclass_assignments: null, netclass_patterns: pats }, pcbnew: { last_paths: {}, page_layout_descr_file: '' }, schematic: { legacy_lib_dir: '', legacy_lib_list: [] }, sheets: [[root, 'Root'], ...sheetIds.map(k => [sheetU[k], SHEETS[k]])], text_variables: {} };
  const dru = `(version 1)\n(rule "MIPI intra-pair skew"\n  (condition "A.NetClass == 'MIPI_100' && A.inDiffPair('*')")\n  (constraint skew (max 0.15mm)))\n(rule "USB intra-pair skew"\n  (condition "A.NetClass == 'USB_90' && A.inDiffPair('*')")\n  (constraint skew (max 0.15mm)))\n(rule "LPDDR byte lane match"\n  (condition "A.NetClass == 'DDR_40'")\n  (constraint length (max 25mm)))\n(rule "MIPI lane length"\n  (condition "A.NetClass == 'MIPI_100'")\n  (constraint length (max 60mm)))\n`;
  const libSym = `(kicad_symbol_lib (version 20241209) (generator "amni_phone_studio") (generator_version "3.0")\n${[...[...symDefs.values()].map(d => d.text), FLAG].join('\n').replace(/\(symbol "Amni:/g, '(symbol "')}\n)\n`;
  const tbl = kind => `(${kind}_lib_table\n  (version 7)\n  (lib (name "Amni")(type "KiCad")(uri "\${KIPRJMOD}/${kind === 'sym' ? 'Amni.kicad_sym' : 'Amni.pretty'}")(options "")(descr "Generated by Amni-Phone Studio"))\n)\n`;
  const bom = bomCSV(sch);
  return { name: proj, sch, files: { [proj + '.kicad_pro']: JSON.stringify(pro, null, 2) + '\n', ...files, [proj + '.kicad_pcb']: pcb.text, [proj + '.kicad_dru']: dru, 'Amni.kicad_sym': libSym, 'sym-lib-table': tbl('sym'), 'fp-lib-table': tbl('fp'), ...pcb.mods, [proj + '-bom.csv']: bom, [proj + '-schematic.json']: JSON.stringify({ stats: sch.stats, checks: sch.checks, buses: sch.buses, regs: sch.regs, lanes: sch.lanes, notes: sch.notes, placement: pcb.stats }, null, 1) }, stats: { ...sch.stats, sheets: sheetIds.length, layers: st.layers, thickness: st.total, custom: !!res.items.find(i => i.role === 'soc'), placed: pcb.stats.placed, offboard: pcb.stats.offboard, approx: pcb.stats.approx } };
}
function bomCSV(sch) {
  const rows = [['Refs', 'Qty', 'Kind', 'Value', 'Manufacturer', 'MPN', 'Package', 'DNP', 'Pin map', 'Source']], grp = new Map();
  sch.comps.forEach(c => { const k = c.role === 'passive' ? [c.kind, c.label, c.mpn, c.dnp].join('|') : [c.role, c.mpn].join('|'); grp.has(k) || grp.set(k, []); grp.get(k).push(c); });
  grp.forEach(cs => { const c = cs[0]; rows.push([cs.map(x => x.ref).join(' '), cs.length, c.role === 'passive' ? c.kind : c.role, c.role === 'passive' ? c.label : '', c.mfr || '', c.mpn || (c.role === 'passive' ? 'select ' + c.size : ''), c.role === 'passive' ? c.size : (c.pm && c.pm.package) || '', c.dnp ? 'DNP' : '', c.pm ? c.pm.src : '', c.url || (c.part && c.part.datasheet) || ((c.pm && c.pm.source) || [])[0] || '']); });
  return rows.map(r => r.map(v => /[",\n]/.test(String(v)) ? '"' + String(v).replace(/"/g, '""') + '"' : String(v)).join(',')).join('\n') + '\n';
}
const pip = (x, y, poly) => { let c = false; for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) { const [xi, yi] = poly[i], [xj, yj] = poly[j]; (yi > y) !== (yj > y) && x < (xj - xi) * (y - yi) / (yj - yi) + xi && (c = !c); } return c; };
function pcbOf(res, sch, st, fab, imp, proj) {
  const P0 = 100, kx = x => P0 + x, ky = y => P0 - y, poly = res.board.poly, bb = [Math.min(...poly.map(p => p[0])), Math.min(...poly.map(p => p[1])), Math.max(...poly.map(p => p[0])), Math.max(...poly.map(p => p[1]))], netNames = ['', ...sch.nets.map(n => n.name)], netId = nm => netNames.indexOf(nm), occ = { F: [], B: [] }, placed = [];
  const inside = (r) => [[r[0] - 0.25, r[1] - 0.25], [r[2] + 0.25, r[1] - 0.25], [r[2] + 0.25, r[3] + 0.25], [r[0] - 0.25, r[3] + 0.25], [(r[0] + r[2]) / 2, r[1] - 0.25], [(r[0] + r[2]) / 2, r[3] + 0.25], [r[0] - 0.25, (r[1] + r[3]) / 2], [r[2] + 0.25, (r[1] + r[3]) / 2]].every(([x, y]) => pip(x, y, poly)), free = (r, L) => !occ[L].some(o => r[0] < o[2] && o[0] < r[2] && r[1] < o[3] && o[1] < r[3]);
  const spot = (cx, cy, w, h, L, rad) => { for (let rr = 0; rr <= (rad || 80); rr += 0.25) { const n = rr ? Math.max(8, Math.round(2 * Math.PI * rr / 0.35)) : 1; for (let k = 0; k < n; k++) { const a = k / n * 2 * Math.PI, x = cx + rr * Math.cos(a), y = cy + rr * Math.sin(a), r = [x - w / 2, y - h / 2, x + w / 2, y + h / 2]; if (inside(r) && free(r, L)) return [x, y, L]; } } return null; };
  const geo = new Map(); sch.comps.forEach(c => geo.set(c.ref, geomOf(c)));
  const byUid = new Map(res.items.map(i => [i.uid, i])), board = sch.comps.filter(c => c.role !== 'passive'), pas = sch.comps.filter(c => c.role === 'passive');
  const put = (c, x, y, rot, L) => { const g = geo.get(c.ref), sw = rot % 180 ? g.bh : g.bw, sh = rot % 180 ? g.bw : g.bh; c.pcb = { x: r2(x), y: r2(y), rot, L }; occ[L].push([x - sw / 2 - 0.1, y - sh / 2 - 0.1, x + sw / 2 + 0.1, y + sh / 2 + 0.1]); placed.push(c); };
  let offN = 0; const offboard = c => { const g = geo.get(c.ref); c.pcb = { x: r2(bb[2] + 8 + g.bw / 2), y: r2(bb[3] - 4 - offN), rot: 0, L: 'F', off: true }; offN += g.bh + 2; };
  const onBoard = c => { const it = c.uid && byUid.get(String(c.uid).split('@')[0]); return !!it && (it.mount === 'boardTop' || it.mount === 'boardBottom'); }; board.sort((a, b) => (onBoard(b) - onBoard(a)) || (geo.get(b.ref).bw * geo.get(b.ref).bh) - (geo.get(a.ref).bw * geo.get(a.ref).bh)).forEach(c => { const it = c.uid && byUid.get(String(c.uid).split('@')[0]), g = geo.get(c.ref), onB = it && (it.mount === 'boardTop' || it.mount === 'boardBottom'), L = it && it.mount === 'boardBottom' ? 'B' : 'F', rot = onB ? (it.rot || 0) : 0, k = Number(String(c.uid || '').split('@')[1] || 0); let tx = it ? it.x + (k ? k * (g.bw + 1.2) : 0) : (bb[0] + bb[2]) / 2, ty = it ? it.y : (bb[1] + bb[3]) / 2; if (!onB) { tx = Math.max(bb[0] + g.bw / 2 + 0.5, Math.min(bb[2] - g.bw / 2 - 0.5, tx)); ty = Math.max(bb[1] + g.bh / 2 + 0.5, Math.min(bb[3] - g.bh / 2 - 0.5, ty)); } const sw = rot % 180 ? g.bh : g.bw, sh = rot % 180 ? g.bw : g.bh, s = spot(tx, ty, sw + 0.2, sh + 0.2, L, onB ? 6 : 60) || spot(tx, ty, sw + 0.2, sh + 0.2, L, 60) || spot(tx, ty, sw + 0.2, sh + 0.2, L === 'F' ? 'B' : 'F', 60) || (onB && !k ? (() => { const cx = (bb[0] + bb[2]) / 2, cy = (bb[1] + bb[3]) / 2, dd = Math.hypot(cx - tx, cy - ty) || 1; for (let m = 0.1; m <= 3; m += 0.1) { const x = tx + (cx - tx) / dd * m, y = ty + (cy - ty) / dd * m, rr = [x - sw / 2 - 0.1, y - sh / 2 - 0.1, x + sw / 2 + 0.1, y + sh / 2 + 0.1]; if (inside(rr) && free(rr, L)) return [x, y, L]; } return null; })() : null) || (onB && !k && free([tx - sw / 2 - 0.1, ty - sh / 2 - 0.1, tx + sw / 2 + 0.1, ty + sh / 2 + 0.1], L) ? [tx, ty, L] : null) || spot(tx, ty, sw + 0.2, sh + 0.2, L, onB ? 6 : 60) || spot(tx, ty, sw + 0.2, sh + 0.2, L === 'F' ? 'B' : 'F', 60); s ? put(c, s[0], s[1], rot, s[2]) : offboard(c); });
  const padWorld = (c, num) => { const g = geo.get(c.ref), p = g.pads.find(x => x.num === num) || g.pads[0], fb = c.pcb.L === 'B', a = (fb ? -(c.pcb.rot || 0) : c.pcb.rot || 0) * Math.PI / 180, x = p.x, y = fb ? p.y : -p.y; return [c.pcb.x + x * Math.cos(a) - y * Math.sin(a), c.pcb.y + x * Math.sin(a) + y * Math.cos(a)]; };
  pas.forEach(c => { const g = geo.get(c.ref), par = c.near && sch.comps.find(x => x.ref === c.near.ref && x.pcb && !x.pcb.off), grid = par && geo.get(par.ref).kind === 'grid'; let tx, ty, L = 'F'; if (par) { const [px, py] = padWorld(par, c.near.num), dx = px - par.pcb.x, dy = py - par.pcb.y, d = Math.hypot(dx, dy) || 1, gp = geo.get(par.ref), out = grid && c.kind === 'cap' ? 0 : Math.max(gp.bw, gp.bh) / 2 * 0 + 1.0; L = grid && c.kind === 'cap' ? (par.pcb.L === 'F' ? 'B' : 'F') : par.pcb.L; tx = px + dx / d * out; ty = py + dy / d * out; } else { const nb = sch.comps.find(x => x.pcb && !x.pcb.off && x.role !== 'passive' && x.pins.some(p => c.pins.some(q => q.net && q.net === p.net))); tx = nb ? nb.pcb.x : (bb[0] + bb[2]) / 2; ty = nb ? nb.pcb.y : (bb[1] + bb[3]) / 2; L = nb ? nb.pcb.L : 'F'; } const s = spot(tx, ty, g.bw + 0.25, g.bh + 0.25, L, 25) || spot(tx, ty, g.bw + 0.25, g.bh + 0.25, L === 'F' ? 'B' : 'F', 40); s ? put(c, s[0], s[1], 0, s[2]) : offboard(c); });
  const fpBody = c => fpOf(c, geo.get(c.ref), netId, kx, ky).body, mods = {}, fps = sch.comps.map(c => { const { body } = fpOf(c, geo.get(c.ref), netId, kx, ky);
    mods['Amni.pretty/' + c.fp + '.kicad_mod'] || (mods['Amni.pretty/' + c.fp + '.kicad_mod'] = (c.pcb.L === 'F' && !c.pcb.rot ? body : fpBody({ ...c, pcb: { x: 0, y: 0, rot: 0, L: 'F' } })).replace(/^  \(footprint "Amni:/, '(footprint "').replace(/ \(at [-\d.]+ [-\d.]+ -?\d+\)\n/, '\n').replace(/ \(net \d+ "[^"]*"\)/g, '').replace(/\n  \)$/, '\n)') + '\n'); return body; });
  const cus = ['F.Cu', ...Array.from({ length: st.layers - 2 }, (_, i) => `In${i + 1}.Cu`), 'B.Cu'], layerIds = cus.map((c, i) => `    (${i === 0 ? 0 : i === st.layers - 1 ? 2 : 2 * i + 2} ${q(c)} signal)`);
  let di = 0; const stk = st.rows.map(r => r.kind === 'cu' ? `      (layer ${q(cus[Number(r.name.slice(1)) - 1])} (type "copper") (thickness ${r.t}))` : `      (layer ${q('dielectric ' + (++di))} (type ${q(r.kind === 'core' ? 'core' : 'prepreg')}) (thickness ${r.t}) (material ${q(String(r.name).slice(0, 30))}) (epsilon_r ${r.dk || 4}) (loss_tangent 0.02))`);
  const edge = poly.map((a, i) => { const c = poly[(i + 1) % poly.length]; return `  (gr_line (start ${f2(kx(a[0]))} ${f2(ky(a[1]))}) (end ${f2(kx(c[0]))} ${f2(ky(c[1]))}) (stroke (width 0.1) (type default)) (layer "Edge.Cuts") (uuid ${q(uid())}))`; });
  const planes = st.rows.filter(r => r.kind === 'cu' && r.role === 'plane').map(r => cus[Number(r.name.slice(1)) - 1]), inset = poly.map(([x, y]) => [x, y]), zone = (layer, nm) => `  (zone (net ${netId(nm)}) (net_name ${q(nm)}) (layer ${q(layer)}) (uuid ${q(uid())}) (hatch edge 0.5) (connect_pads (clearance 0.1)) (min_thickness 0.1) (filled_areas_thickness no) (fill (thermal_gap 0.15) (thermal_bridge_width 0.15)) (polygon (pts ${inset.map(([x, y]) => `(xy ${f2(kx(x))} ${f2(ky(y))})`).join(' ')})))`;
  const zones = planes.map((l, i) => zone(l, i % 2 === 0 || !netId('VSYS') ? 'GND' : 'VSYS')).filter(() => netId('GND') > 0);
  const text = `(kicad_pcb (version 20241229) (generator "pcbnew") (generator_version "9.0")\n  (general (thickness ${st.total}) (legacy_teardrops no))\n  (paper "A3")\n  (title_block (title ${q(res.d.name + ' main board')}) (comment 1 ${q(`${st.layers}-layer ${HDI[st.hdi].name}; fab rules: ${fab.name}`)}) (comment 2 "Auto-placed by Amni-Phone Studio from the layout; decoupling next to its pins (under BGAs on the far side)."))\n  (layers\n${layerIds.join('\n')}\n    (5 "F.SilkS" user "F.Silkscreen") (7 "B.SilkS" user "B.Silkscreen") (1 "F.Mask" user) (3 "B.Mask" user) (13 "F.Paste" user) (15 "B.Paste" user) (25 "Edge.Cuts" user) (27 "Margin" user) (31 "F.CrtYd" user "F.Courtyard") (29 "B.CrtYd" user "B.Courtyard") (35 "F.Fab" user) (33 "B.Fab" user) (17 "Dwgs.User" user "User.Drawings") (19 "Cmts.User" user "User.Comments")\n  )\n  (setup\n    (stackup\n      (layer "F.SilkS" (type "Top Silk Screen"))\n      (layer "F.Paste" (type "Top Solder Paste"))\n      (layer "F.Mask" (type "Top Solder Mask") (thickness 0.01))\n${stk.join('\n')}\n      (layer "B.Mask" (type "Bottom Solder Mask") (thickness 0.01))\n      (layer "B.Paste" (type "Bottom Solder Paste"))\n      (layer "B.SilkS" (type "Bottom Silk Screen"))\n      (copper_finish "ENIG")\n      (dielectric_constraints no)\n    )\n    (pad_to_mask_clearance 0)\n    (allow_soldermask_bridges_in_footprints yes)\n  )\n${netNames.map((n, i) => `  (net ${i} ${q(n)})`).join('\n')}\n${fps.join('\n')}\n${edge.join('\n')}\n${zones.join('\n')}\n)\n`;
  return { text, mods, stats: { placed: placed.filter(c => !c.pcb.off).length, offboard: sch.comps.filter(c => c.pcb && c.pcb.off).map(c => c.ref), approx: sch.comps.filter(c => geo.get(c.ref).approx && c.role !== 'passive').map(c => c.ref), bottom: placed.filter(c => c.pcb.L === 'B').length, area: r2((bb[2] - bb[0]) * (bb[3] - bb[1])) } };
}
function fpOf(c, g, netId, kx, ky) {
  const L = c.pcb.L, fl = L === 'B', ang = fl ? (360 - (c.pcb.rot || 0)) % 360 : c.pcb.rot || 0, pin = num => c.pins.find(p => p.num === num), pad = p => { const pn = pin(p.num), n = pn && pn.net ? netId(pn.net) : 0, shape = p.shape === 'circle' ? 'circle' : p.shape === 'rect' ? 'rect' : 'roundrect'; return `    (pad ${q(p.num)} smd ${shape} (at ${f2(p.x)} ${f2(fl ? -p.y : p.y)} ${ang}) (size ${f2(p.w)} ${f2(p.h)}) (layers "${L}.Cu" "${L}.Paste" "${L}.Mask")${shape === 'roundrect' ? ' (roundrect_rratio 0.25)' : ''}${n > 0 ? ` (net ${n} ${q(pn.net)})` : ''}${pn ? ` (pinfunction ${q(pn.name)}) (pintype ${q(TYPE[pn.type] || 'passive')})` : ''} (uuid ${q(uid())}))`; }, cw = g.bw / 2 + 0.05, ch = g.bh / 2 + 0.05, lines = [[-cw, -ch, cw, -ch], [cw, -ch, cw, ch], [cw, ch, -cw, ch], [-cw, ch, -cw, -ch]];
  const body = `  (footprint ${q('Amni:' + c.fp)} (layer "${L}.Cu") (uuid ${q(uid())}) (at ${f2(kx(c.pcb.x))} ${f2(ky(c.pcb.y))} ${ang})\n    (property "Reference" ${q(c.ref)} (at 0 ${f2(fl ? ch + 0.5 : -ch - 0.5)} ${fl ? (ang + 180) % 360 : ang}) (layer "${L}.Fab") (uuid ${q(uid())}) (effects (font (size 0.4 0.4) (thickness 0.06))${fl ? ' (justify mirror)' : ''}))\n    (property "Value" ${q(c.role === 'passive' ? c.label : c.mpn)} (at 0 ${f2(fl ? -ch - 0.5 : ch + 0.5)} ${fl ? (ang + 180) % 360 : ang}) (layer "${L}.Fab") (hide yes) (uuid ${q(uid())}) (effects (font (size 0.4 0.4) (thickness 0.06))${fl ? ' (justify mirror)' : ''}))\n    (property "Footprint" ${q('Amni:' + c.fp)} (at 0 0 0) (layer "${L}.Fab") (hide yes) (uuid ${q(uid())}) (effects (font (size 1 1))))\n    (property "MPN" ${q(c.mpn || '')} (at 0 0 0) (layer "${L}.Fab") (hide yes) (uuid ${q(uid())}) (effects (font (size 1 1))))\n    (attr smd)\n${lines.map(l => `    (fp_line (start ${f2(l[0])} ${f2(l[1])}) (end ${f2(l[2])} ${f2(l[3])}) (stroke (width 0.05) (type solid)) (layer "${L}.CrtYd") (uuid ${q(uid())}))`).join('\n')}\n${lines.map(l => `    (fp_line (start ${f2(l[0] * 0.98)} ${f2(l[1] * 0.98)}) (end ${f2(l[2] * 0.98)} ${f2(l[3] * 0.98)}) (stroke (width 0.05) (type solid)) (layer "${L}.Fab") (uuid ${q(uid())}))`).join('\n')}\n${g.pads.map(pad).join('\n')}\n  )`;
  return { body };
}
const CRC = (() => { const t = new Uint32Array(256); for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1; t[n] = c >>> 0; } return t; })();
const crc32 = b => { let c = 0xFFFFFFFF; for (let i = 0; i < b.length; i++) c = CRC[(c ^ b[i]) & 255] ^ (c >>> 8); return (c ^ 0xFFFFFFFF) >>> 0; };
export function zip(files) {
  const enc = new TextEncoder(), parts = [], dir = []; let off = 0;
  Object.entries(files).forEach(([name, text]) => { const data = typeof text === 'string' ? enc.encode(text) : text, nm = enc.encode(name), c = crc32(data), h = new DataView(new ArrayBuffer(30)); [[0, 0x04034b50, 4], [4, 20, 2], [6, 0x0800, 2], [8, 0, 2], [10, 0, 2], [12, 0x21, 2], [14, c, 4], [18, data.length, 4], [22, data.length, 4], [26, nm.length, 2], [28, 0, 2]].forEach(([o, v, s]) => s === 4 ? h.setUint32(o, v, true) : h.setUint16(o, v, true)); parts.push(new Uint8Array(h.buffer), nm, data); const cd = new DataView(new ArrayBuffer(46)); [[0, 0x02014b50, 4], [4, 20, 2], [6, 20, 2], [8, 0x0800, 2], [10, 0, 2], [12, 0, 2], [14, 0x21, 2], [16, c, 4], [20, data.length, 4], [24, data.length, 4], [28, nm.length, 2], [30, 0, 2], [32, 0, 2], [34, 0, 2], [36, 0, 2], [38, 0, 4], [42, off, 4]].forEach(([o, v, s]) => s === 4 ? cd.setUint32(o, v, true) : cd.setUint16(o, v, true)); dir.push(new Uint8Array(cd.buffer), nm); off += 30 + nm.length + data.length; });
  const dsz = dir.reduce((s, x) => s + x.length, 0), e = new DataView(new ArrayBuffer(22)), n = Object.keys(files).length; [[0, 0x06054b50, 4], [4, 0, 2], [6, 0, 2], [8, n, 2], [10, n, 2], [12, dsz, 4], [16, off, 4], [20, 0, 2]].forEach(([o, v, s]) => s === 4 ? e.setUint32(o, v, true) : e.setUint16(o, v, true));
  const all = [...parts, ...dir, new Uint8Array(e.buffer)], out = new Uint8Array(all.reduce((s, x) => s + x.length, 0)); let p = 0; all.forEach(x => { out.set(x, p); p += x.length; }); return out;
}
