import { K } from './catalog.js';
import { mulberry } from './optimize.js';
import { evaluate, fitDesign, applyPatch, unpinned } from './engine.js';
const NETS = [['soc', 'lpddr', 0.3], ['soc', 'ufs', 0.12], ['soc', 'soc_pmic', 0.1], ['som', 'conn_display', 0.06], ['soc', 'conn_display', 0.06], ['mcu', 'conn_display', 0.06], ['som', 'conn_cam', 0.06], ['soc', 'conn_cam', 0.06], ['som', 'modem', 0.04], ['soc', 'modem', 0.04], ['som', 'wifi', 0.04], ['soc', 'wifi', 0.04], ['conn_batt', 'cell', 0.05], ['charger', 'conn_batt', 0.04], ['charger', 'usb_pd', 0.03], ['usbc', 'usb_pd', 0.03], ['cam_main', 'conn_cam', 0.04], ['cam_ultra', 'conn_cam', 0.03], ['modem', 'ant_main', 0.06], ['modem', 'ant_div', 0.04], ['wifi', 'ant_wifi', 0.06], ['gnss', 'ant_gnss', 0.05], ['ntn', 'ant_main', 0.03], ['speaker', 'codec', 0.02], ['haptic', 'haptic_drv', 0.02], ['qi_rx', 'qi_coil', 0.03], ['nfc', 'nfc_coil', 0.03]];
const MOVE = new Set(['floor', 'boardTop', 'boardBottom', 'back', 'antTop', 'antBottom']), FIXR = new Set(['thermal']), COIL = new Set(['qi_coil', 'nfc_coil']);
const inRR = (x, y, hw, hl, r) => { const dx = Math.abs(x) - (hw - r), dy = Math.abs(y) - (hl - r); return dx <= 0 || dy <= 0 ? Math.max(0, Math.abs(x) - hw, Math.abs(y) - hl) : Math.max(0, Math.hypot(dx, dy) - r); };
export function maxRects(rects, W, H, gap) {
  const g = gap == null ? 0.3 : gap, free = [[0, 0, W, H]], out = [], ov = (a, b) => a[0] < b[0] + b[2] && b[0] < a[0] + a[2] && a[1] < b[1] + b[3] && b[1] < a[1] + a[3];
  for (const r of rects.slice().sort((a, b) => Math.max(b.w, b.h) - Math.max(a.w, a.h) || b.w * b.h - a.w * a.h)) {
    let best = null; free.forEach(f => [[r.w + g, r.h + g, 0], [r.h + g, r.w + g, 90]].forEach(([w, h, rot]) => { if (w <= f[2] + 1e-9 && h <= f[3] + 1e-9) { const ss = Math.min(f[2] - w, f[3] - h), ls = Math.max(f[2] - w, f[3] - h); (!best || ss < best.ss || (ss === best.ss && ls < best.ls)) && (best = { x: f[0], y: f[1], w, h, rot, ss, ls }); } }));
    if (!best) return null; const pl = [best.x, best.y, best.w, best.h]; out.push({ id: r.id, x: best.x + (best.w - g) / 2, y: best.y + (best.h - g) / 2, rot: best.rot });
    for (let i = free.length - 1; i >= 0; i--) { const f = free[i]; if (!ov(f, pl)) continue; free.splice(i, 1); pl[0] > f[0] && free.push([f[0], f[1], pl[0] - f[0], f[3]]); pl[0] + pl[2] < f[0] + f[2] && free.push([pl[0] + pl[2], f[1], f[0] + f[2] - pl[0] - pl[2], f[3]]); pl[1] > f[1] && free.push([f[0], f[1], f[2], pl[1] - f[1]]); pl[1] + pl[3] < f[1] + f[3] && free.push([f[0], pl[1] + pl[3], f[2], f[1] + f[3] - pl[1] - pl[3]]); }
    for (let i = free.length - 1; i >= 0; i--) free.some((o, j) => j !== i && o[0] <= free[i][0] && o[1] <= free[i][1] && o[0] + o[2] >= free[i][0] + free[i][2] && o[1] + o[3] >= free[i][1] + free[i][3]) && free.splice(i, 1);
  }
  return out;
}
export function placePiece(res, half, opts) {
  const o = { iters: 30000, seed: 11, ...(opts || {}) }, rnd = mulberry(o.seed), g = half === 'B' ? res.g.B : res.g, hw = res.g.iw / 2, hl = res.g.il / 2, ir = res.g.ir, items = res.items.filter(i => i.half === half), swell = i => i.cat.startsWith('cell') ? Math.max(K.swellMin, i.sz * K.swellFrac) : 0, over = g.dispT + res.g.adhT + res.g.glassT + K.gapDisplay;
  const mov = items.filter(i => MOVE.has(i.mount) && !i.lock && !FIXR.has(i.role) && !i.sub), obs = items.filter(i => !mov.includes(i) && i.box && !['display', 'glass', 'spreader', 'hinge'].includes(i.mount) && !FIXR.has(i.role)), coils = [];
  const S = mov.map(i => ({ it: i, x: i.x, y: i.y, rot: i.rot, mount: i.mount, w: i.sx, h: i.sy, flip: ['boardTop', 'boardBottom'].includes(i.mount) && i.sz < 1.6 && !['soc', 'som', 'lpddr', 'conn_display', 'conn_cam', 'conn_batt'].includes(i.role) }));
  const byRole = r => S.find(s => s.it.role === r) || (o2 => o2 && { x: o2.x, y: o2.y })(items.find(i => i.role === r)), mag = items.find(i => i.role === 'mag'), mags = items.filter(i => i.cat === 'magnet'), hot = ['som', 'soc', 'modem', 'mcu'];
  const geom = () => { const bs = S.filter(s => s.mount === 'boardTop' || s.mount === 'boardBottom'); if (!bs.length) return { bz: null, rect: null }; const rect = [Math.min(...bs.map(s => s.x - s.w / 2)) - 0.6, Math.min(...bs.map(s => s.y - s.h / 2)) - 0.6, Math.max(...bs.map(s => s.x + s.w / 2)) + 0.6, Math.max(...bs.map(s => s.y + s.h / 2)) + 0.6], bottomH = Math.max(0.6, ...bs.filter(s => s.mount === 'boardBottom').map(s => s.it.sz)), under = S.filter(s => s.mount === 'floor' && s.x - s.w / 2 < rect[2] && s.x + s.w / 2 > rect[0] && s.y - s.h / 2 < rect[3] && s.y + s.h / 2 > rect[1]).map(s => g.floor + (s.it.lift || 0) + s.it.sz + swell(s.it) + K.clear); return { rect, bz: Math.max(g.floor + bottomH + 0.2, ...under.map(u => u + bottomH + 0.2)) }; };
  const zOf = (s, G) => s.mount === 'antTop' || s.mount === 'antBottom' ? s.it.z : s.mount === 'floor' ? g.floor + (s.it.lift || 0) : s.mount === 'back' ? g.floor : s.mount === 'boardBottom' ? G.bz - s.it.sz : G.bz + res.board.t + (s.it.cat === 'som' && Number.isFinite(s.it.p.n.mated) ? s.it.p.n.mated : s.it.cat === 'som' ? 1.5 : 0);
  const cost = () => {
    const G = geom(); let c = 0, top = g.floor + 1;
    const bx = S.map(s => { const z = zOf(s, G); top = Math.max(top, z + s.it.sz + swell(s.it)); return [s.x - s.w / 2, s.y - s.h / 2, z, s.x + s.w / 2, s.y + s.h / 2, z + s.it.sz]; });
    obs.forEach(ob => { top = Math.max(top, ob.mount === 'back' || ob.mount === 'front' || ob.mount === 'top' ? 0 : ob.box[5] + swell(ob)); });
    const ov = (a, b, cl) => { const x = Math.min(a[3], b[3]) - Math.max(a[0], b[0]) + cl, y = Math.min(a[4], b[4]) - Math.max(a[1], b[1]) + cl, z = Math.min(a[5], b[5]) - Math.max(a[2], b[2]) + cl; return x > 0 && y > 0 && z > 0 ? x * y : 0; };
    const skip = (a, b) => (COIL.has(a.role) && (b.cat.startsWith('cell') || COIL.has(b.role))) || (COIL.has(b.role) && a.cat.startsWith('cell'));
    for (let i = 0; i < bx.length; i++) { const b = bx[i], si = S[i]; [[b[0], b[1]], [b[3], b[1]], [b[3], b[4]], [b[0], b[4]]].forEach(([x, y]) => { c += 400 * inRR(x, y, hw, hl, ir); }); for (let j = i + 1; j < bx.length; j++) skip(si.it, S[j].it) || (c += 120 * ov(b, bx[j], K.clear)); obs.forEach(ob => { skip(si.it, ob) || (c += 120 * ov(b, ob.box, K.clear)); }); if (si.it.cat === 'antenna') { c += 3 * Math.min(hw - Math.abs(si.x) - si.w / 2, hl - Math.abs(si.y) - si.h / 2); const kz = [b[0] - K.antKeep, b[1] - K.antKeep, -1, b[3] + K.antKeep, b[4] + K.antKeep, 99]; S.forEach((q, j) => { j !== i && q.it.metal && (c += 4 * ov(kz, bx[j], 0)); }); obs.forEach(ob => { ob.metal && (c += 4 * ov(kz, ob.box, 0)); }); } }
    G.rect && obs.forEach(ob => { c += 60 * ov([G.rect[0], G.rect[1], G.bz, G.rect[2], G.rect[3], G.bz + res.board.t], ob.box, 0); }); G.rect && S.filter(q => q.mount === 'floor' || q.mount === 'back').forEach((q, k) => { const b = bx[S.indexOf(q)]; c += 60 * ov([G.rect[0], G.rect[1], G.bz, G.rect[2], G.rect[3], G.bz + res.board.t], b, 0); });
    G.rect && (c += 400 * (inRR(G.rect[0], G.rect[1], hw, hl, ir) + inRR(G.rect[2], G.rect[3], hw, hl, ir) + inRR(G.rect[0], G.rect[3], hw, hl, ir) + inRR(G.rect[2], G.rect[1], hw, hl, ir)), c += 0.01 * (G.rect[2] - G.rect[0]) * (G.rect[3] - G.rect[1]), S.filter(s => s.mount === 'floor' && !s.it.cat.startsWith('cell')).forEach(s => { const r = G.rect; r && s.x + s.w / 2 > r[0] && s.x - s.w / 2 < r[2] && s.y + s.h / 2 > r[1] && s.y - s.h / 2 < r[3] && (c += 0); }));
    c += 300 * (top + over);
    NETS.forEach(([a, b, w]) => { const p = byRole(a), q = byRole(b); p && q && (c += w * (Math.abs(p.x - q.x) + Math.abs(p.y - q.y))); });
    mag && mags.length && (m => { const pm = S.find(s => s.it === mag) || mag; mags.forEach(mg => { const dd = Math.hypot(mg.x - pm.x, mg.y - pm.y); c += dd < 30 ? (30 - dd) * 2 : 0; }); })();
    const hs = hot.map(byRole).filter(Boolean); for (let i = 0; i < hs.length; i++) for (let j = i + 1; j < hs.length; j++) { const dd = Math.hypot(hs[i].x - hs[j].x, hs[i].y - hs[j].y); c += dd < 20 ? (20 - dd) * 0.5 : 0; }
    false && o.debug && !o.dbgDone && (o.dbgDone = true, console.log('dbg board', G.rect && G.rect.map(v => v.toFixed(1)), 'bz', G.bz && G.bz.toFixed(2), 'top', top.toFixed(2)), S.forEach((s2, i) => { const b = bx[i]; obs.concat(S.filter((q, j) => j > i).map(q => ({ ...q.it, box: bx[S.indexOf(q)] }))).forEach(ob => { const x = Math.min(b[3], ob.box[3]) - Math.max(b[0], ob.box[0]), y = Math.min(b[4], ob.box[4]) - Math.max(b[1], ob.box[1]), z = Math.min(b[5], ob.box[5]) - Math.max(b[2], ob.box[2]); x > -0.2 && y > -0.2 && z > -0.2 && !skip(s2.it, ob) && console.log('ov', s2.it.uid, s2.mount, ob.uid, x.toFixed(2), y.toFixed(2), z.toFixed(2), 'z', b[2].toFixed(2), b[5].toFixed(2), 'eng z', s2.it.z.toFixed(2)); }); }));
    return { c, top: top + over, G };
  };
  const seed = (() => { const bs = S.filter(q => (q.mount === 'boardTop' || q.mount === 'boardBottom') && !q.it.lock), G0 = geom(); if (!bs.length || !G0.rect) return null; const cx = (G0.rect[0] + G0.rect[2]) / 2, cy = (G0.rect[1] + G0.rect[3]) / 2, area = bs.reduce((a, q) => a + (q.w + 0.3) * (q.h + 0.3), 0); for (let k = 0.62; k <= 0.9; k += 0.04) { const W = Math.min(2 * hw - 1, Math.max(...bs.map(q => Math.max(q.w, q.h))) + 1, Math.sqrt(area / k * (2 * hw) / (2 * hl)) * 1.2), H = area / k / W, tops = maxRects(bs.filter(q => q.mount === 'boardTop').map(q => ({ id: S.indexOf(q), w: q.w, h: q.h })), W, H), bots = maxRects(bs.filter(q => q.mount === 'boardBottom').map(q => ({ id: S.indexOf(q), w: q.w, h: q.h })), W, H); if (tops && bots && H <= 2 * hl - 1) return [...tops, ...bots].map(o => ({ ...o, x: o.x + cx - W / 2, y: o.y + cy - H / 2 })); } return null; })();
  const before = cost(), keep0 = S.map(q => ({ ...q })), c0 = before.c; if (seed) { seed.forEach(o => { const q = S[o.id]; q.x = o.x; q.y = o.y; o.rot && (q.rot = (q.rot + 90) % 360, [q.w, q.h] = [q.h, q.w]); }); cost().c > c0 && keep0.forEach((b, i) => Object.assign(S[i], b)); }
  S.forEach(s => { s.x = Math.max(-hw + s.w / 2, Math.min(hw - s.w / 2, s.x)); s.y = Math.max(-hl + s.h / 2, Math.min(hl - s.h / 2, s.y)); }); let cur = cost().c, best = { c: cur, st: S.map(s => ({ ...s })) }, packed = !!seed && cur < c0;
  for (let k = 0; k < o.iters; k++) {
    const T = 40 * Math.pow(0.002, k / o.iters), s = S[Math.floor(rnd() * S.length)]; if (!s) break;
    const old = { x: s.x, y: s.y, rot: s.rot, mount: s.mount, w: s.w, h: s.h }, mv = rnd();
    if (mv < 0.7) { const st = Math.max(0.3, 12 * T / 40); s.x += (rnd() - 0.5) * 2 * st; s.y += (rnd() - 0.5) * 2 * st; } else if (mv < 0.85) { s.rot = (s.rot + 90) % 360; [s.w, s.h] = [s.h, s.w]; } else if (mv < 0.93 && s.flip) { s.mount = s.mount === 'boardTop' ? 'boardBottom' : 'boardTop'; } else { const t2 = S[Math.floor(rnd() * S.length)]; if (t2 && t2 !== s && t2.mount === s.mount) { [s.x, t2.x] = [t2.x, s.x]; [s.y, t2.y] = [t2.y, s.y]; const n2 = cost().c; if (n2 < cur || rnd() < Math.exp((cur - n2) / T)) { cur = n2; } else { [s.x, t2.x] = [t2.x, s.x]; [s.y, t2.y] = [t2.y, s.y]; } continue; } }
    const n = cost().c; if (n < cur || rnd() < Math.exp((cur - n) / T)) { cur = n; n < best.c && (best = { c: n, st: S.map(q => ({ ...q })) }); } else Object.assign(s, old);
  }
  best.st.forEach((b, i) => Object.assign(S[i], b));
  const after = cost(), r2 = v => Math.round(v * 100) / 100, pos = {};
  S.forEach(s => { pos[s.it.uid] = { x: r2(s.x), y: r2(s.y), rot: s.rot, half, mount: s.mount === s.it.p && null || s.mount, placed: true, z: null }; });
  const cell = S.find(s => s.it.cat.startsWith('cell')); coils.forEach(cl => { const c0 = cell || cl; pos[cl.uid] = { x: r2(c0.x), y: r2(c0.y), rot: 0, half, placed: true, z: null }; });
  return { pos, poly: after.G.rect ? [[after.G.rect[0], after.G.rect[1]], [after.G.rect[2], after.G.rect[1]], [after.G.rect[2], after.G.rect[3]], [after.G.rect[0], after.G.rect[3]]].map(p => p.map(r2)) : null, before: { cost: Math.round(before.c), top: r2(before.top) }, after: { cost: Math.round(after.c), top: r2(after.top) }, moved: S.length, packed };
}
export function optimizePlacement(src, opts) {
  const d0 = fitDesign(src), r0 = evaluate(d0, { fixes: false }), halves = r0.g.halves > 1 ? ['A', 'B'] : ['A'], runs = halves.map(h => ({ h, ...placePiece(r0, h, opts) })), pos = Object.assign({}, ...runs.map(x => x.pos)), polyA = (runs.find(x => x.h === 'A') || {}).poly;
  const d1 = fitDesign(applyPatch(d0, { pos: { ...unpinned(d0.pos), ...pos }, board: { poly: polyA || d0.board.poly, z: null }, keepBoard: true })), r1 = evaluate(d1, { fixes: false }), sum = r => ({ errors: r.errors, warns: r.warns, thick: r.obj.thick, w: r.g.w, l: r.g.l, t: r.g.t, mass: r.mass, life: r.power.sot });
  const better = r1.errors < r0.errors || (r1.errors === r0.errors && r1.obj.thick < r0.obj.thick - 0.01);
  return { d: better ? d1 : d0, applied: better, before: sum(r0), after: sum(r1), runs: runs.map(x => ({ half: x.h, moved: x.moved, before: x.before, after: x.after })) };
}
