import { OPT } from './presets.opt.js';
const H = (w, l, t, r, fillet, wall, floor, mat) => ({ w, l, t, r, fillet, wall, floor, mat, back: 'unibody' });
const Q = (price, life, mass, thick, ip, qty) => ({ price, life, mass, thick, ip, qty, margin: 0.4, skin: 43 });
export const SPECS = {
  'amni-duo-twins': { name: 'Amni Duo — symmetric twins', group: 'duo', default: true, concept: false, require: ['modem', 'cell', 'display'], objective: 'balanced', text: 'Two identical sealed pieces, each a compact phone (≤ 72 × 124 mm), no hinge: magnet arrays on every edge and the back snap them side by side, end to end or back to back. Battery dies, the other half still works. Frame auto-fits around each screen; custom chip-level board.', d: { form: 'slab', dock: { on: true, sealed: true, perEdge: 4, back: true, code: 'pair' }, system: { arch: 'twins', config: 'widebook' }, housing: { auto: true, w: 72, l: 110, t: 6, r: 6, fillet: 0.8, wall: 1.0, floor: 0.5, mat: 'ti5', back: 'unibody' }, board: { path: 'custom', layers: 10, hdi: 'any', fab: 'jlcpcb-hdi' }, req: { ...Q(1400, 2.5, 260, 16, 'ip68', 100), maxW: 72, maxL: 124, depth: 5 }, sel: {} } },
  'amni-duo-companion': { name: 'Amni Duo — primary + companion', group: 'duo', concept: false, require: ['modem', 'cell', 'display'], objective: 'balanced', text: 'A primary piece (SoC, modem, main camera) and a lighter companion (screen, battery, low-power processor) that magnet-dock into one wide screen or a back-to-back brick. Compared against the twins in the Report tab.', d: { form: 'slab', dock: { on: true, sealed: true, perEdge: 4, back: true, code: 'pair' }, system: { arch: 'companion', config: 'widebook' }, housing: { auto: true, w: 72, l: 110, t: 6, r: 6, fillet: 0.8, wall: 1.0, floor: 0.5, mat: 'ti5', back: 'unibody' }, board: { path: 'custom', layers: 10, hdi: 'any', fab: 'jlcpcb-hdi' }, req: { ...Q(1200, 2.5, 240, 16, 'ip68', 100), maxW: 72, maxL: 124, depth: 5 }, sel: {} } },
  'amni-tiles-grid4': { name: 'Amni Tiles — 2 × 2 grid', group: 'duo', concept: false, require: ['modem', 'cell', 'display'], objective: 'balanced', text: 'Four twin pieces snapped into a 2 × 2 grid for one large screen; any piece still works alone.', d: { form: 'slab', dock: { on: true, sealed: true, perEdge: 4, back: true, code: 'pair' }, system: { arch: 'twins', config: 'grid4' }, housing: { auto: true, w: 72, l: 110, t: 6, r: 6, fillet: 0.8, wall: 1.0, floor: 0.5, mat: 'ti5', back: 'unibody' }, board: { path: 'custom', layers: 10, hdi: 'any', fab: 'jlcpcb-hdi' }, req: { ...Q(2800, 2.5, 520, 16, 'ip68', 100), maxW: 72, maxL: 124, depth: 5 }, sel: {} } },
  'amni-one': { name: 'Amni One (balanced slab)', concept: false, objective: 'balanced', text: 'The everyday buildable phone: smart module with built-in 5G on our carrier board, a current AMOLED with touch, sealed to IP67. Every part choice is the optimizer’s balanced Pareto point.', d: { form: 'slab', housing: H(73.4, 161, 10, 9, 1.2, 1.4, 0.9, 'al6061'), req: Q(1100, 6.5, 230, 10.5, 'ip67', 1000), sel: {} } },
  'amni-max': { name: 'Amni Max (battery-max slab)', concept: false, objective: 'battery', text: 'Largest priced cell that fits a 6.7 in class slab; screen-on hours first.', d: { form: 'slab', housing: H(77, 165, 11, 9, 1.2, 1.4, 0.9, 'al6061'), req: Q(1200, 8, 260, 12.5, 'ip67', 1000), sel: {} } },
  'amni-air': { name: 'Amni Air (thinnest slab)', concept: false, objective: 'thin', text: 'Thinnest slab the buyable modules allow; thickness then mass first.', d: { form: 'slab', housing: H(72, 158, 9, 9, 1, 1.2, 0.8, 'al7075'), req: Q(1200, 5, 210, 10, 'ip54', 1000), sel: {} } },
  'amni-bench': { name: 'Amni Bench — cheapest, single units', concept: false, objective: 'cheap', text: 'Cheapest phone you can order in single units, every line priced, in a 3D-printed housing.', d: { form: 'slab', housing: H(76, 162, 13, 8, 1.5, 1.6, 1.2, 'pa12'), req: Q(950, 5, 280, 14, 'none', 1), sel: {} } },
  'amni-rugged': { name: 'Amni Rugged — IP68', concept: false, objective: 'rugged', text: 'Thick 7075 walls, IPX8 USB-C, sealed keys, gel-sealed barometer and vents: durability first.', d: { form: 'slab', housing: H(75, 163, 11, 7, 1.6, 2.0, 1.1, 'al7075'), req: Q(1250, 6.5, 270, 12.5, 'ip68', 1000), sel: { baro: 'st-lps28dfwtr' } } },
  'amni-handset': { name: 'Amni Handset — satellite texting', concept: false, objective: 'balanced', fixed: ['ntn'], text: 'A plain slab with a 5G smart module plus an NB-NTN satellite modem for messaging.', d: { form: 'slab', housing: H(74, 162, 10.5, 9, 1.2, 1.4, 0.9, 'al6061'), req: Q(1200, 6.5, 240, 11, 'ip67', 1000), sel: { ntn: 'nordic-nrf9151' } } },
  'amni-book-center': { name: 'Amni Book — center hinge', concept: false, objective: 'balanced', require: ['display2'], text: 'Two rigid panels side by side on center friction hinges, like Surface Duo; the module needs two DSI ports.', d: { form: 'dual', hinge: { type: 'spine' }, housing: H(73.4, 163, 8.6, 7, 1, 1.3, 0.8, 'al6061'), req: Q(1100, 4.5, 340, 24, 'ip54', 100), sel: {} } },
  'amni-book-outer': { group: 'hinged', name: 'Amni Book — dual outer hinge', concept: false, objective: 'balanced', require: ['display2'], text: 'Anthony’s dual outer hinge on a book: two leaf links outside the shells at the top and bottom ends of the seam, magnets hold it shut and flat, no center spine.', d: { form: 'dual', hinge: { type: 'outer', leaf: 6, pinFace: 2, inset: 2.6, shutPairs: 2, flatPairs: 2 }, housing: H(73.4, 163, 8.6, 7, 1.2, 1.3, 0.8, 'al6061'), req: Q(1150, 4.5, 350, 24, 'ip54', 100), sel: { mag_shut: 'sm-q-12-07-02-hn', mag_flat: 'sm-q-12-07-02-hn',} } },
  'amni-flip-outer': { group: 'hinged', name: 'Amni Flip — dual outer hinge', concept: false, objective: 'balanced', require: ['display2', 'display_cover'], text: 'Anthony’s dual outer hinge on a clamshell: leaf links on the left and right sides of the seam, magnets hold it shut and flat, top screen + bottom screen + a cover screen.', d: { form: 'flip', hinge: { type: 'outer', leaf: 6, pinFace: 2, inset: 2.6, shutPairs: 2, flatPairs: 2, flipBottom: 'screen' }, housing: H(76, 92, 10, 8, 1.2, 1.3, 0.8, 'al6061'), req: Q(1150, 4, 300, 23, 'ip54', 100), sel: { mag_shut: 'kj-bx081-n52', mag_flat: 'kj-bx081-n52',} } },
  'amni-flip-spine': { name: 'Amni Flip — center hinge', concept: false, objective: 'battery', require: ['display2'], text: 'Clamshell with rigid top and bottom screens on center friction hinges and cells in both halves; battery first.', d: { form: 'flip', hinge: { type: 'spine', flipBottom: 'screen' }, housing: H(76, 92, 10, 8, 1.2, 1.3, 0.8, 'al6061'), req: Q(1150, 4, 300, 23, 'ip54', 100), sel: {} } },
  'amni-keypad': { group: 'hinged', name: 'Amni Keypad — screen and keys', concept: false, objective: 'cheap', text: 'Top screen and a 16-key keypad in the bottom half on the dual outer hinge; cheapest priced build.', d: { form: 'flip', hinge: { type: 'outer', leaf: 6, pinFace: 2, inset: 2.6, shutPairs: 2, flatPairs: 1, flipBottom: 'keys' }, housing: H(68, 92, 10, 8, 1.2, 1.3, 0.8, 'al6061'), req: Q(900, 4, 260, 23, 'none', 100), sel: { mag_shut: 'kj-bx081-n52', mag_flat: 'kj-bx081-n52',} } },
  'amni-square': { name: 'Amni Square — 69 mm dual-screen book', concept: false, objective: 'balanced', fixed: ['ntn'], require: ['display2', 'cam_main', 'modem'], text: 'Ultracompact book: two ≤69 × 69 mm halves on a center hinge, two rigid square-ish screens, satellite texting, split cells, custom chip-level board; the frame auto-fits around the screens. Asked for 4 mm halves; the stack-up report shows what each half really needs and why.', d: { form: 'dual', hinge: { type: 'spine', shutPairs: 2 }, housing: { w: 69, l: 69, t: 4, tB: 4, r: 6, fillet: 0.8, wall: 1.0, floor: 0.5, mat: 'ti5', back: 'unibody' }, board: { path: 'custom', layers: 10, hdi: 'any', fab: 'jlcpcb-hdi' }, req: { ...Q(1500, 3, 170, 9, 'ip54', 100), maxW: 69, maxL: 69 }, sel: { ntn: 'nordic-nrf9151' } } },
  'amni-edge': { name: 'Amni Edge — wishbone hinge', concept: true, objective: 'thin', require: ['display2'], text: 'A thin book on the dual outer hinge: one flat leaf per end with a pin on each half, outside the glass; magnets close the flat-open seam. The Ku sky pair is dropped (no parts exist).', d: { form: 'dual', hinge: { type: 'outer', leaf: 8, pinFace: 2, inset: 3.6, shutPairs: 2, flatPairs: 2 }, housing: H(73.4, 163, 8.6, 7, 1.2, 1.3, 0.8, 'al7075'), req: Q(1200, 4.5, 360, 24, 'ip54', 100), sel: { mag_shut: 'sm-q-12-07-02-hn', mag_flat: 'sm-q-12-07-02-hn', ntn: 'nordic-nrf9151' } } },
  'amni-slim': { name: 'Amni Slim', concept: true, objective: 'thin', require: ['display2'], text: 'The thinnest dual-screen halves the real parts allow. The original 2.1 mm half had no room for a cell, a USB-C port or a module; with buyable modules each half auto-fits to about 9–11 mm, so this is honest rather than slim.', d: { form: 'dual', hinge: { type: 'spine' }, housing: H(73.4, 163, 6, 7, 0.8, 1.1, 0.6, 'ti5'), req: Q(1200, 4, 320, 23, 'none', 100), sel: { flash: '', nfc: '', nfc_coil: '', qi_rx: '', qi_coil: '' } } },
  'amni-fold': { name: 'Amni Fold — reference', concept: true, objective: 'balanced', text: 'Reference-only foldable book on an OEM foldable panel and waterdrop hinge. The Ku “sky pair” back arrays and rotary RFID half link have no sourceable parts, so they are not modelled.', d: { form: 'fold', hinge: { type: 'waterdrop' }, housing: H(74.5, 163, 6.6, 7, 1, 1.2, 0.7, 'al7075'), req: { ...Q(1200, 4.5, 320, 18, 'ip54', 1000), allowRef: true }, sel: {} } },
  'amni-clamshell': { name: 'Amni Clamshell — reference', concept: true, objective: 'balanced', require: ['display_cover'], text: 'Reference-only classic clamshell: an OEM flip-size foldable inner panel on a waterdrop hinge plus a buyable cover screen. Face-NFC half links are not sourceable.', d: { form: 'flipfold', hinge: { type: 'waterdrop' }, housing: H(75, 88, 7.5, 8, 1, 1.2, 0.7, 'al6061'), req: { ...Q(1200, 4, 260, 17, 'ip54', 1000), allowRef: true }, sel: {} } },
};
export const merge = (s, o) => o ? { ...s.d, pos: { ...(o.d.pos || {}) }, system: s.d.system ? { ...s.d.system, ...(o.d.system || {}), ...(o.d.system && o.d.system.B ? { B: { req: { ...s.d.req, ...((o.d.system.B || {}).req || {}) }, ...o.d.system.B } } : {}) } : undefined, sel: { ...s.d.sel, ...o.d.sel }, housing: { ...s.d.housing, ...o.d.housing }, hinge: { ...(s.d.hinge || {}), ...(o.d.hinge || {}) }, board: { ...(s.d.board || {}), ...(o.d.board || {}) }, req: { ...s.d.req, ...(o.d.req || {}) } } : s.d;
export const PRESETS = Object.fromEntries(Object.entries(SPECS).map(([k, s]) => [k, { ...s, opt: OPT[k] || null, d: merge(s, OPT[k]) }]));
