import { db, part } from './parts.js';
const fin = v => typeof v === 'number' && Number.isFinite(v), r3 = v => Math.round(v * 1000) / 1000;
export const SHEETS = { power: 'Power and charging', compute: 'Compute', display: 'Display', camera: 'Camera', radio: 'Radio and SIM', audio: 'Audio and haptics', sensors: 'Sensors', dock: 'Dock link and sensing', ui: 'Keys and test' };
export const SHEET_OF = { charger: 'power', fuel_gauge: 'power', usb_pd: 'power', usbc: 'power', protection: 'power', conn_batt: 'power', qi_rx: 'power', qi_coil: 'power', pmic: 'power', soc_pmic: 'compute', som: 'compute', soc: 'compute', mcu: 'compute', lpddr: 'compute', ufs: 'compute', conn_display: 'display', dsi_mux: 'display', conn_cam: 'camera', flash_drv: 'camera', flash: 'camera', modem: 'radio', wifi: 'radio', gnss: 'radio', ntn: 'radio', nfc: 'radio', nfc_coil: 'radio', sim: 'radio', esim: 'radio', uwb: 'radio', ant_main: 'radio', ant_div: 'radio', ant_wifi: 'radio', ant_gnss: 'radio', mic: 'audio', mic2: 'audio', codec: 'audio', haptic_drv: 'audio', haptic: 'audio', speaker: 'audio', receiver: 'audio', imu: 'sensors', als: 'sensors', baro: 'sensors', mag: 'sensors', hall: 'sensors', dock_hall: 'dock', dock_link: 'dock', btn_power: 'ui', btn_up: 'ui', btn_down: 'ui' };
export const E24 = [1, 1.1, 1.2, 1.3, 1.5, 1.6, 1.8, 2, 2.2, 2.4, 2.7, 3, 3.3, 3.6, 3.9, 4.3, 4.7, 5.1, 5.6, 6.2, 6.8, 7.5, 8.2, 9.1];
export const E96 = Array.from({ length: 96 }, (_, i) => Math.round(Math.pow(10, i / 96) * 100) / 100).map(v => ({ 1.01: 1.01, 2.61: 2.61 }[v] || v)).map((v, i) => [1, 1.02, 1.05, 1.07, 1.1, 1.13, 1.15, 1.18, 1.21, 1.24, 1.27, 1.3, 1.33, 1.37, 1.4, 1.43, 1.47, 1.5, 1.54, 1.58, 1.62, 1.65, 1.69, 1.74, 1.78, 1.82, 1.87, 1.91, 1.96, 2, 2.05, 2.1, 2.15, 2.21, 2.26, 2.32, 2.37, 2.43, 2.49, 2.55, 2.61, 2.67, 2.74, 2.8, 2.87, 2.94, 3.01, 3.09, 3.16, 3.24, 3.32, 3.4, 3.48, 3.57, 3.65, 3.74, 3.83, 3.92, 4.02, 4.12, 4.22, 4.32, 4.42, 4.53, 4.64, 4.75, 4.87, 4.99, 5.11, 5.23, 5.36, 5.49, 5.62, 5.76, 5.9, 6.04, 6.19, 6.34, 6.49, 6.65, 6.81, 6.98, 7.15, 7.32, 7.5, 7.68, 7.87, 8.06, 8.25, 8.45, 8.66, 8.87, 9.09, 9.31, 9.53, 9.76][i]);
export const nearestE = (v, series, mode) => { const dec = Math.pow(10, Math.floor(Math.log10(v))), all = [dec / 10, dec, dec * 10].flatMap(d => series.map(s => Number((s * d).toPrecision(3)))).sort((a, b) => a - b); return mode === 'down' ? all.filter(x => x <= v * 1.0001).pop() : mode === 'up' ? all.find(x => x >= v * 0.9999) : all.reduce((b, x) => Math.abs(Math.log(x / v)) < Math.abs(Math.log(b / v)) ? x : b, all[0]); };
const SI = { p: 1e-12, n: 1e-9, u: 1e-6, 'µ': 1e-6, 'μ': 1e-6, m: 1e-3, k: 1e3, K: 1e3, M: 1e6, G: 1e9, '': 1 };
export const parseVal = s => { const m = String(s == null ? '' : s).replace(',', '.').match(/(\d+(?:\.\d+)?)\s*(?:(?:-|–|to)\s*\d+(?:\.\d+)?\s*)?([pnuµμmkKMG]?)(?:\s*(?:F|H|Ω|ohm|R)?)?/); return m ? Number(m[1]) * SI[m[2] || ''] : null; };
export const parseV = s => { const m = String(s == null ? '' : s).match(/(\d+(?:\.\d+)?)\s*V\b/); return m ? Number(m[1]) : null; };
export const fmtVal = (v, unit) => { if (!fin(v)) return '?'; const ps = unit === 'Ω' ? [[1e6, 'M'], [1e3, 'k'], [1, '']] : [[1, ''], [1e-3, 'm'], [1e-6, 'µ'], [1e-9, 'n'], [1e-12, 'p']], [d, p] = ps.find(([d]) => v >= d * 0.9999) || ps[ps.length - 1]; return String(r3(v / d)).replace(/\.0+$/, '') + ' ' + p + unit; };
export const yageoCode = ohm => ohm < 1 ? 'R' + String(Math.round(ohm * 100)).padStart(2, '0') : ohm < 1e3 ? String(r3(ohm)).replace('.', 'R') + (Number.isInteger(ohm) ? 'R' : '') : ohm < 1e6 ? String(r3(ohm / 1e3)).replace('.', 'K') + (Number.isInteger(r3(ohm / 1e3)) ? 'K' : '') : String(r3(ohm / 1e6)).replace('.', 'M') + (Number.isInteger(r3(ohm / 1e6)) ? 'M' : '');
const P = (num, name, type, fn, note) => ({ num: String(num == null ? '' : num), name: String(name), type: type || 'io', fn: fn || '', note: note || '' });
const IFS = {
  vbat: [['VBAT', 'power_in', 'pwr:vbat']], vsys: [['VSYS', 'power_in', 'pwr:vsys']], vdd: [['VDD', 'power_in', 'pwr:vdd']], vddio: [['VDDIO', 'power_in', 'pwr:vddio']], avdd: [['AVDD', 'power_in', 'pwr:avdd']], vbus: [['VBUS', 'power_in', 'pwr:vbus']], vio_out: [['VDD_1V8_OUT', 'power_out', 'pwr:out:1v8']],
  i2c: [['SCL', 'in', 'i2c:scl'], ['SDA', 'io', 'i2c:sda']], int: [['INT', 'od', 'int']], rst: [['RESET_N', 'in', 'rst_n']], en: [['EN', 'in', 'en']], pwrkey: [['PWRKEY', 'in', 'en']],
  uart: [['TXD', 'out', 'uart:tx'], ['RXD', 'in', 'uart:rx']], spi: [['SCK', 'in', 'spi:sck'], ['MOSI', 'in', 'spi:mosi'], ['MISO', 'out', 'spi:miso'], ['CS_N', 'in', 'spi:cs']], pdm: [['CLK', 'in', 'pdm:clk'], ['DATA', 'out', 'pdm:data'], ['SEL', 'in', 'strap:lr']],
  i2s: [['BCLK', 'in', 'i2s:bclk'], ['LRCK', 'in', 'i2s:ws'], ['DIN', 'in', 'i2s:din'], ['DOUT', 'out', 'i2s:dout']], sdio: [['SDIO_CLK', 'in', 'sdio:clk'], ['SDIO_CMD', 'io', 'sdio:cmd'], ['SDIO_D0', 'io', 'sdio:d0'], ['SDIO_D1', 'io', 'sdio:d1'], ['SDIO_D2', 'io', 'sdio:d2'], ['SDIO_D3', 'io', 'sdio:d3']],
  usb: [['USB_DP', 'io', 'usb:dp'], ['USB_DM', 'io', 'usb:dn']], sim: [['USIM_VCC', 'power_out', 'sim:vcc'], ['USIM_CLK', 'out', 'sim:clk'], ['USIM_DATA', 'io', 'sim:io'], ['USIM_RST', 'out', 'sim:rst']], simcard: [['VCC', 'passive', 'sim:vcc'], ['CLK', 'passive', 'sim:clk'], ['IO', 'passive', 'sim:io'], ['RST', 'passive', 'sim:rst']],
  ant: [['ANT', 'passive', 'rf:ant']], ant2: [['ANT_DIV', 'passive', 'rf:ant2']], gnssant: [['ANT_GNSS', 'passive', 'rf:gnss']], feed: [['FEED', 'passive', 'rf:ant']], mot: [['OUTP', 'out', 'mot+'], ['OUTN', 'out', 'mot-']], motor: [['M+', 'passive', 'mot+'], ['M-', 'passive', 'mot-']], spk: [['SPK_P', 'out', 'spk+'], ['SPK_N', 'out', 'spk-']], spkload: [['+', 'passive', 'spk+'], ['-', 'passive', 'spk-']],
  coil: [['AC1', 'passive', 'coil:ac1'], ['AC2', 'passive', 'coil:ac2']], led: [['LED', 'out', 'led']], ledload: [['A', 'passive', 'led'], ['K', 'passive', 'gnd']], hallout: [['OUT', 'od', 'int']], key: [['1', 'passive', 'key'], ['2', 'passive', 'gnd']],
  usbc: [['VBUS', 'passive', 'pwr:vbus'], ['CC1', 'passive', 'usbc:cc1'], ['CC2', 'passive', 'usbc:cc2'], ['DP1', 'passive', 'usbc:dp1'], ['DN1', 'passive', 'usbc:dn1'], ['DP2', 'passive', 'usbc:dp2'], ['DN2', 'passive', 'usbc:dn2'], ['SBU1', 'passive', 'usbc:sbu1'], ['SBU2', 'passive', 'usbc:sbu2'], ['SHIELD', 'passive', 'gnd']],
  cc: [['CC1', 'io', 'usbc:cc1'], ['CC2', 'io', 'usbc:cc2']], bat: [['BAT+', 'passive', 'pwr:vbat'], ['NTC', 'passive', 'ts'], ['BAT-', 'passive', 'gnd']], chg: [['SW', 'passive', 'sw'], ['BTST', 'passive', 'bst'], ['SYS', 'power_out', 'pwr:vsys'], ['BAT', 'power_in', 'pwr:vbat'], ['TS', 'analog', 'ts'], ['REGN', 'power_out', 'pwr:out:regn']],
  vout: [['VOUT', 'power_out', 'pwr:out:wpc']], link: [['VDD', 'power_in', 'pwr:vdd'], ['TX_DP', 'io', 'usb:dp'], ['TX_DN', 'io', 'usb:dn'], ['EN', 'in', 'en'], ['ANT', 'passive', 'rf:ant']]
};
const SYN = { charger: ['vbus', 'chg', 'i2c', 'int', 'en'], fuel_gauge: ['vbat', 'i2c', 'int'], usb_pd: ['vbus', 'vdd', 'cc', 'i2c', 'int'], protection: ['vbat'], imu: ['vdd', 'vddio', 'i2c', 'int'], als: ['vdd', 'i2c', 'int'], baro: ['vdd', 'vddio', 'i2c', 'int'], mag: ['vdd', 'vddio', 'i2c', 'int'], hall: ['vdd', 'hallout'], dock_hall: ['vdd', 'hallout'], nfc: ['vbat', 'vddio', 'i2c', 'int', 'en', 'coil'], qi_rx: ['coil', 'vout', 'vddio', 'i2c', 'int', 'en'], haptic_drv: ['vbat', 'vddio', 'i2c', 'int', 'mot'], flash_drv: ['vbat', 'i2c', 'en', 'led'], codec: ['vbat', 'vddio', 'i2c', 'i2s', 'spk', 'int'], modem: ['vbat', 'vio_out', 'usb', 'sim', 'ant', 'ant2', 'pwrkey', 'rst', 'int'], wifi: ['vbat', 'vddio', 'sdio', 'uart', 'ant', 'en', 'int'], gnss: ['vdd', 'vddio', 'uart', 'gnssant', 'rst'], ntn: ['vbat', 'vddio', 'uart', 'ant', 'sim', 'en', 'int'], uwb: ['vdd', 'vddio', 'spi', 'int', 'ant', 'en'], esim: ['simcard', 'vdd'], sim: ['simcard'], usbc: ['usbc'], conn_batt: ['bat'], mic: ['vdd', 'pdm'], mic2: ['vdd', 'pdm'], ant_main: ['feed'], ant_div: ['feed'], ant_wifi: ['feed'], ant_gnss: ['feed'], haptic: ['motor'], speaker: ['spkload'], receiver: ['spkload'], qi_coil: ['coil'], nfc_coil: ['coil'], flash: ['ledload'], btn_power: ['key'], btn_up: ['key'], btn_down: ['key'], dock_link: ['link'] };
const GNDP = role => ['usbc', 'conn_batt', 'ant_main', 'ant_div', 'ant_wifi', 'ant_gnss', 'haptic', 'speaker', 'receiver', 'qi_coil', 'nfc_coil', 'flash', 'btn_power', 'btn_up', 'btn_down', 'sim'].includes(role) ? [] : [['GND', 'gnd', 'gnd']];
const DDR = ch => [...Array.from({ length: 16 }, (_, j) => ['DQ' + j, 'io', `ddr:${ch}:dq${j}`]), ...[0, 1].flatMap(j => [['DMI' + j, 'io', `ddr:${ch}:dmi${j}`], ['WCK' + j + '_T', 'out', `ddr:${ch}:wck${j}t`], ['WCK' + j + '_C', 'out', `ddr:${ch}:wck${j}c`], ['RDQS' + j + '_T', 'io', `ddr:${ch}:rdqs${j}t`], ['RDQS' + j + '_C', 'io', `ddr:${ch}:rdqs${j}c`]]), ...Array.from({ length: 7 }, (_, j) => ['CA' + j, 'out', `ddr:${ch}:ca${j}`]), ['CS0', 'out', `ddr:${ch}:cs0`], ['CK_T', 'out', `ddr:${ch}:ckt`], ['CK_C', 'out', `ddr:${ch}:ckc`]].map(([n, t, f]) => [`DDR_${ch.toUpperCase()}_${n}`, t, f]);
const UFS = [['UFS_TX0_P', 'out', 'ufs:tx0p'], ['UFS_TX0_N', 'out', 'ufs:tx0n'], ['UFS_RX0_P', 'in', 'ufs:rx0p'], ['UFS_RX0_N', 'in', 'ufs:rx0n'], ['UFS_TX1_P', 'out', 'ufs:tx1p'], ['UFS_TX1_N', 'out', 'ufs:tx1n'], ['UFS_RX1_P', 'in', 'ufs:rx1p'], ['UFS_RX1_N', 'in', 'ufs:rx1n'], ['UFS_REFCLK', 'out', 'ufs:refclk'], ['UFS_RST_N', 'out', 'ufs:rst']];
const flipT = t => t === 'out' ? 'in' : t === 'in' ? 'out' : t;
SYN.lpddr = 'lpddr'; SYN.ufs = 'ufs';
function synthMem(role) { return role === 'lpddr' ? [...['a', 'b'].flatMap(ch => DDR(ch).map(([n, t, f]) => [n.replace(/^DDR_/, ''), flipT(t), f])), ['RESET_N', 'in', 'ddr:reset'], ['ZQ', 'analog', 'ext:zq'], ['VDD1', 'power_in', 'pwr:dram'], ['VDD2H', 'power_in', 'pwr:dram'], ['VDDQ', 'power_in', 'pwr:dram'], ['VSS', 'gnd', 'gnd'], ['VSS', 'gnd', 'gnd']] : [...UFS.map(([n, t, f]) => [n.replace(/^UFS_/, '').replace('TX', 'DIN').replace('RX', 'DOUT'), f === 'ufs:refclk' || f === 'ufs:rst' ? 'in' : flipT(t), f]), ['VCC', 'power_in', 'pwr:3v3'], ['VCCQ', 'power_in', 'pwr:1v2'], ['VSS', 'gnd', 'gnd']]; }
function synthHost(it) {
  const n = it.p.n || {}, out = [], add = (name, type, fn) => out.push(P('', name, type, fn)), sp = it.p.specs || {}, dP = n.dsiPorts || 1, dL = n.dsi || 4, cP = fin(n.csiPorts) ? n.csiPorts : /^none/i.test(String(sp.mipi_csi || '')) ? 0 : 2;
  for (let k = 0; k < dP; k++) ['CLK', ...Array.from({ length: dL }, (_, j) => 'D' + j)].forEach(x => ['P', 'N'].forEach(pn => add(`DSI${k}_${x}${pn}`, 'out', `dsi:${x.toLowerCase()}${pn.toLowerCase()}`)));
  for (let k = 0; k < cP; k++) ['CLK', 'D0', 'D1', 'D2', 'D3'].forEach(x => ['P', 'N'].forEach(pn => add(`CSI${k}_${x}${pn}`, 'in', `csi:${x.toLowerCase()}${pn.toLowerCase()}`)));
  for (let k = 0; k < 2; k++) [['DP', 'usb:dp'], ['DM', 'usb:dn']].forEach(([x, f]) => add(`USB${k}_${x}`, 'io', f));
  for (let k = 0; k < 4; k++) [['SCL', 'od', 'i2c:scl'], ['SDA', 'od', 'i2c:sda']].forEach(([x, t, f]) => add(`I2C${k}_${x}`, t, f));
  for (let k = 0; k < 3; k++) [['TX', 'out', 'uart:tx'], ['RX', 'in', 'uart:rx']].forEach(([x, t, f]) => add(`UART${k}_${x}`, t, f));
  [['SCLK', 'out', 'spi:sck'], ['MOSI', 'out', 'spi:mosi'], ['MISO', 'in', 'spi:miso'], ['CS0', 'out', 'spi:cs'], ['CS1', 'out', 'spi:cs']].forEach(([x, t, f]) => add('SPI0_' + x, t, f));
  [['BCLK', 'out', 'i2s:bclk'], ['LRCK', 'out', 'i2s:ws'], ['SDO', 'out', 'i2s:din'], ['SDI', 'in', 'i2s:dout'], ['MCLK', 'out', 'i2s:mclk']].forEach(([x, t, f]) => add('I2S0_' + x, t, f));
  [['CLK', 'out', 'pdm:clk'], ['DATA0', 'in', 'pdm:data'], ['DATA1', 'in', 'pdm:data']].forEach(([x, t, f]) => add('PDM_' + x, t, f));
  [['CLK', 'out', 'sdio:clk'], ['CMD', 'io', 'sdio:cmd'], ['D0', 'io', 'sdio:d0'], ['D1', 'io', 'sdio:d1'], ['D2', 'io', 'sdio:d2'], ['D3', 'io', 'sdio:d3']].forEach(([x, t, f]) => add('SDIO_' + x, t, f));
  n.hasModem && IFS.sim.forEach(([x, t, f]) => add(x, t, f)); it.role === 'soc' && ([...DDR('a'), ...DDR('b'), ['DDR_RESET_N', 'out', 'ddr:reset'], ...UFS].forEach(([x, t, f]) => add(x, t, f)));
  for (let k = 0; k < 40; k++) add('GPIO' + k, 'io', 'gpio');
  add('PWRKEY', 'in', 'pwrkey'); add('RESET_N', 'in', 'rst_n');
  it.role === 'soc' ? ['VDD_CPU_BIG', 'VDD_CPU_LIT', 'VDD_GPU', 'VDD_NPU', 'VDD_LOGIC', 'VDD_DDR', 'VDDQ_DDR', 'VCCIO_1V8'].forEach(x => add(x, 'power_in', /DDR/.test(x) ? 'pwr:dram' : /1V8/.test(x) ? 'pwr:1v8' : 'pwr:core')) : (['VSYS_1', 'VSYS_2', 'VSYS_3', 'VSYS_4'].forEach(x => add(x, 'power_in', 'pwr:vsys')), add('VREG_1V8', 'power_out', 'pwr:out:1v8'));
  for (let k = 0; k < 8; k++) add('GND_' + k, 'gnd', 'gnd');
  return out;
}
function synthFPC(it) {
  const n = it.p.n || {}, cam = it.cat === 'camera' || it.cat === 'camera_front', L = n.lanes || (cam ? 2 : 4), out = [], add = (name, type, fn) => out.push(P('', name, type, fn)), k = cam ? 'csi' : 'dsi';
  ['CLK', ...Array.from({ length: L }, (_, j) => 'D' + j)].forEach(x => ['P', 'N'].forEach(pn => add(`${x}_${pn}`, 'passive', `${k}:${x.toLowerCase()}${pn.toLowerCase()}`)));
  cam ? [['AVDD', 'pwr:avdd'], ['DVDD', 'pwr:1v2'], ['DOVDD', 'pwr:1v8']].forEach(([x, f]) => add(x, 'passive', f)) : [['VCI', 'pwr:3v3'], ['VDDI', 'pwr:1v8'], ['VBAT', 'pwr:vbat']].forEach(([x, f]) => add(x, 'passive', f));
  cam ? [['MCLK', 'i2s:mclk'], ['SCL', 'i2c:scl'], ['SDA', 'i2c:sda'], ['XSHUTDOWN', 'rst_n'], ['FSIN', 'gpio']].forEach(([x, f]) => add(x, 'passive', f)) : [['RESET', 'rst_n'], ['TE', 'int'], ['TP_SCL', 'i2c:scl'], ['TP_SDA', 'i2c:sda'], ['TP_INT', 'int'], ['TP_RST', 'rst_n']].forEach(([x, f]) => add(x, 'passive', f));
  for (let j = 0; j < 4; j++) add('GND', 'passive', 'gnd');
  return out.map((p, i) => ({ ...p, num: String(i + 1) }));
}
export function pinmap(p, role, it) {
  const m = p && (db().pinmaps || {})[p.id];
  if (m && Array.isArray(m.pins) && m.pins.length) { const raw = m.pins.map(a => Array.isArray(a) ? P(a[0], a[1], a[2], a[3], a[4]) : P(a.num, a.name, a.type, a.fn, a.note)), seen = new Set(), pins = []; raw.forEach(p => { const bl = (String(p.note).match(/balls?\s*\(\d+\)\s*:\s*([A-Z0-9 ,]+)/i) || [])[1], nums = bl ? bl.split(/[\s,]+/).filter(Boolean) : [p.num]; nums.forEach(n => { const num = n || ''; if (num && seen.has(num)) return; num && seen.add(num); pins.push({ ...p, num }); }); }); let k = 0; pins.forEach(p => { p.num || (p.num = 'X' + (++k)); }); const host = ['som', 'soc', 'mcu'].includes(role); if (host && !m.complete && raw.filter(p => !p.num).length > raw.length / 2) { const sp = synthHost(it).map((x, i) => ({ ...x, num: String(i + 1) })); return { src: 'synth', complete: false, doc: (m.doc || '') + ' — public brochure lists interfaces only; pins are interface-level placeholders', source: m.source || [], package: m.package || '', pins: sp, i2c: null, rails: m.rails || [], ext: m.ext || [], notes: m.notes || '' }; } const extra = host && !m.complete ? synthHost(it).filter(q => !pins.some(x => kindOf(x.fn) === kindOf(q.fn))).map((q, i) => ({ ...q, num: 'S' + (i + 1), note: 'interface-level placeholder (pin number under NDA or not public)' })) : []; return { src: 'datasheet', complete: !!m.complete, partial: extra.length > 0, doc: m.doc || '', source: m.source || [], package: m.package || '', pins: [...pins, ...extra], i2c: m.i2c || null, rails: m.rails || [], ext: m.ext || [], notes: m.notes || '' }; }
  const pins = ['som', 'soc', 'mcu'].includes(role) ? synthHost(it) : ['lpddr', 'ufs'].includes(role) ? synthMem(role).map(a => P('', ...a)) : ['conn_display', 'conn_cam'].includes(role) ? synthFPC(it) : (SYN[role] || ['vdd']).flatMap(k => IFS[k] || []).concat(GNDP(role)).map(a => P('', ...a));
  return { src: 'synth', complete: false, doc: 'Interface-level placeholder pins (no public pin map stored for this part)', source: [], package: '', pins: pins.map((x, i) => ({ ...x, num: x.num || String(i + 1) })), i2c: null, rails: [], ext: [], notes: 'Synthesized from the role; replace with the datasheet pin map.' };
}
const ALT = [[/^I2C(\d+)_(SCL|SDA)(?:_(M\d+))?$/, 'i2c', m => 'i2c:' + m[2].toLowerCase()], [/^UART(\d+)_(TX|RX|RTSN|CTSN)(?:_(M\d+))?$/, 'uart', m => 'uart:' + { TX: 'tx', RX: 'rx', RTSN: 'rts', CTSN: 'cts' }[m[2]]], [/^SPI(\d+)_(CLK|MOSI|MISO|CSN\d)(?:_(M\d+))?$/, 'spi', m => 'spi:' + { CLK: 'sck', MOSI: 'mosi', MISO: 'miso' }[m[2]] || 'spi:cs'], [/^(?:SAI|I2S)(\d+)_(SCLK|LRCK|SDO0|SDI0|MCLK)(?:_(M\d+))?$/, 'i2s', m => 'i2s:' + { SCLK: 'bclk', LRCK: 'ws', SDO0: 'din', SDI0: 'dout', MCLK: 'mclk' }[m[2]]], [/^PDM(\d+)_(CLK0?|SDI\d)(?:_(M\d+))?$/, 'pdm', m => /CLK/.test(m[2]) ? 'pdm:clk' : 'pdm:data'], [/^SDMMC(\d+)_(D[0-3]|CMD|CLK)(?:_(M\d+))?$/, 'sdio', m => 'sdio:' + m[2].toLowerCase()]];
const altOfSeg = seg => { for (const [re, kind, f] of ALT) { const m = seg.match(re); if (m) return { kind, key: seg.replace(/_(SCL|SDA|TX|RX|RTSN|CTSN|CLK|MOSI|MISO|CSN\d|SCLK|LRCK|SDO0|SDI0|MCLK|CLK0|SDI\d|D[0-3]|CMD)(?=(_M\d+)?$)/, ''), fn: f(m) }; } return null; };
const view = (p, fn) => { const v = Object.create(p); Object.defineProperty(v, 'fn', { value: fn, enumerable: true }); Object.defineProperty(v, 'net', { get: () => p.net, set: x => { p.net = x; }, enumerable: true }); return v; };
const portOf = (name, kind) => { const a = altOfSeg(String(name).toUpperCase().split('/')[0]); if (a && a.kind === kind) return a.key; const seg = String(name).toUpperCase().split('/')[0].replace(/_M\d+$/, '').replace(/_[A-Z]*\d*[A-Z]*$/, ''); return seg || kind.toUpperCase() + '0'; };
export const ddrKey = (name, pref) => { const segs = String(name).toUpperCase().split('/'), s0 = (segs.find(x => pref && x.startsWith(pref)) || segs.find(x => /^LP5_/.test(x)) || segs[0]).replace(/^(LP4X|LP5|LP4|DDR\d?)_/, ''); return s0.replace(/^RDQS/, 'DQS').replace(/^DQS(\d)P/, 'DQS$1_T').replace(/^DQS(\d)N/, 'DQS$1_C').replace(/^WCK(\d)P/, 'WCK$1_T').replace(/^WCK(\d)N/, 'WCK$1_C').replace(/^CLKP/, 'CK_T').replace(/^CLKN/, 'CK_C').replace(/^A(\d+)_/, 'CA$1_').replace(/^CSN/, 'CS').replace(/^ZQ\d?_?/, 'ZQ_'); };
const vOfName = n => { const m = String(n).toUpperCase().match(/(\d)V(\d{1,2})(?!\d)/); return m ? Number(m[1] + '.' + m[2]) : null; };
const kindOf = fn => String(fn).split(':')[0];
const isAct = name => /(_N|N|_B|#|\/)$|^N[A-Z]|_L$/.test(String(name).toUpperCase());
export function autoSchematic(res, opts) {
  const o = opts || {}, items = res.items.filter(i => SHEET_OF[i.role] && !i.uid.endsWith('#B')), lib = db().passives || {}, comps = [], nets = new Map(), checks = [], refs = {}, notes = [];
  const add = (sev, id, text) => checks.push({ sev, id, text });
  const ref = k => { refs[k] = (refs[k] || 0) + 1; return k + refs[k]; };
  const net = (name, cls) => { const nm = String(name).replace(/[^A-Za-z0-9_+\-./]/g, '_'); nets.has(nm) || nets.set(nm, { name: nm, cls: cls || 'Default', nodes: [] }); const n = nets.get(nm); cls && n.cls === 'Default' && (n.cls = cls); return n; };
  const join = (n, c, p) => { if (!p || p.net) return p && p.net; const N = typeof n === 'string' ? net(n) : n; N.nodes.push({ ref: c.ref, num: p.num, name: p.name, type: p.type }); p.net = N.name; return N.name; };
  const comp = (role, it, pm, extra) => { const pre = ['usbc', 'sim', 'conn_batt', 'conn_display', 'conn_cam', 'haptic', 'speaker', 'receiver', 'qi_coil', 'nfc_coil', 'dock_link'].includes(role) && role !== 'dock_link' ? 'J' : /^ant_/.test(role) ? 'AE' : /^btn_/.test(role) ? 'SW' : role === 'flash' ? 'D' : /^mic/.test(role) ? 'MK' : 'U', c = { ref: ref(pre), role, uid: it ? it.uid : null, it, part: it ? it.p : null, mpn: it ? it.p.mpn : '', mfr: it ? it.p.mfr : '', pm, pins: pm.pins.map(p => ({ ...p })), sheet: SHEET_OF[role] || 'power', ...(extra || {}) }; comps.push(c); return c; };
  const pas = (kind, value, a, b, opt) => { const x = opt || {}, pick = choose(kind, value, x.v || 6.3, lib), c = { ref: ref({ res: 'R', cap: 'C', ind: 'L', ferrite: 'FB', tvs: 'D', tp: 'TP', ntc: 'RT' }[kind] || 'X'), role: 'passive', kind, value, label: kind === 'tp' ? 'TP' : fmtVal(value, { res: 'Ω', ntc: 'Ω', cap: 'F', ind: 'H', ferrite: 'Ω' }[kind] || ''), mpn: pick.mpn, mfr: pick.mfr, size: pick.size, url: pick.url, note: pick.note || '', pattern: !!pick.pattern, why: x.why || '', near: x.near || null, sheet: x.sheet || 'power', dnp: !!x.dnp, pm: { src: 'passive', pins: [] }, pins: kind === 'tp' ? [P('1', '1', 'passive', '')] : [P('1', '1', 'passive', ''), P('2', '2', 'passive', '')] }; comps.push(c); a && join(a, c, c.pins[0]); b && c.pins[1] && join(b, c, c.pins[1]); return c; };
  const host = items.find(i => ['som', 'soc', 'mcu'].includes(i.role)), H = host ? comp(host.role, host, pinmap(host.p, host.role, host)) : null;
  const C = {}; items.filter(i => i !== host && !['display', 'display2', 'display_cover'].includes(i.role) && !['camera', 'camera_front'].includes(i.cat)).forEach(i => { const key = i.role + (C[i.role] ? '#' + C[i.role].length : ''); (C[i.role] = C[i.role] || []).push(comp(i.role, i, pinmap(i.p, i.role, i))); });
  const one = r => (C[r] || [])[0], hp = f => H ? H.pins.filter(p => p.fn === f && !p.net) : [], hports = kind => { const m = new Map(), put = (k, v) => { m.has(k) || m.set(k, []); m.get(k).some(x => x.num === v.num) || m.get(k).push(v); }; H && H.pins.forEach(p => { kindOf(p.fn) === kind && put(portOf(p.name, kind), p); String(p.name).toUpperCase().split('/').slice(1).forEach(sg => { const a = altOfSeg(sg); a && a.kind === kind && put(a.key, view(p, a.fn)); }); }); return [...m.entries()].sort((a, b) => String(a[0]).localeCompare(String(b[0]), 'en', { numeric: true })).map(([k, pins]) => ({ k, pins, used: false })); };
  const ports = {}; ['dsi', 'csi', 'usb', 'i2c', 'uart', 'spi', 'i2s', 'pdm', 'sdio', 'pcie', 'sim'].forEach(k => { ports[k] = hports(k); });
  const ctrl = k => String(k).replace(/_M\d+$/, ''), usedCtl = new Set(), takePort0 = (kind, need) => { const free = (ports[kind] || []).filter(x => !x.used && !usedCtl.has(kind + ':' + ctrl(x.k)) && x.pins.some(q => !q.net)), p = Array.isArray(need) ? free.map(x => ({ x, cov: need.filter(f => x.pins.some(q => q.fn === f && !q.net)).length })).sort((a, b) => b.cov - a.cov || a.x.pins.length - b.x.pins.length).map(o => o.x)[0] : free.find(x => !need || need(x)); p && (p.used = true, usedCtl.add(kind + ':' + ctrl(p.k))); return p; }, takePort = takePort0;
  const gpioPool = () => H ? H.pins.filter(p => !p.net && !p.nc && (/(^|\/)GPIO/i.test(p.name) || (p.fn === 'gpio' && ['io', 'in', 'out', 'od'].includes(p.type) && !/ADC|XIN|XOUT|TEST|^NC|OSC|VREF|TSADC/i.test(p.name)))).sort((a, b) => (a.fn !== 'gpio') - (b.fn !== 'gpio') || (/GPIO/i.test(b.name) - /GPIO/i.test(a.name))) : [];
  const gpio = (label, pinC, comp0, pull, optional) => { const g = gpioPool()[0], nm = (comp0.ref + '_' + label).toUpperCase(); if (!g) { if (optional) { pinC.type === 'in' || (pinC.nc = true); return null; } add('error', 'gpio-' + comp0.ref + label, `No free host GPIO for ${comp0.ref} ${pinC.name} (${label}); add a GPIO expander or free a pin.`); return null; } join(nm, comp0, pinC); join(nm, H, g); pull && pas('res', 10e3, nm, pull, { why: 'pull-up for ' + label, near: { ref: comp0.ref, num: pinC.num }, sheet: comp0.sheet }); return nm; };
  const comps0 = () => comps.filter(c => c.role !== 'passive' && c !== H);
  const VIO = 'VIO_1V8', railOf = (c, p) => { const f = p.fn, nm = String(p.name).toUpperCase(), rr = (c.pm.rails || []).find(r => r.fn === f), v = rr && Array.isArray(rr.v) ? rr.v : rr && fin(rr.v) ? [rr.v, rr.v] : null, inR = x => !v || (x >= v[0] - 0.05 && x <= v[1] + 0.05), batt = ['charger', 'fuel_gauge', 'protection', 'conn_batt'].includes(c.role);
    if (f === 'pwr:vbus') return 'VBUS'; if (f === 'pwr:vbat') return batt ? 'VBAT' : 'VSYS'; if (f === 'pwr:vsys') return 'VSYS'; if (f === 'pwr:vin') return ['charger', 'usb_pd'].includes(c.role) ? 'VBUS' : 'VSYS';
    if (f === 'pwr:1v8' || f === 'pwr:vddio') return inR(1.8) ? VIO : inR(3.3) ? 'V3V3' : VIO; if (f === 'pwr:3v3') return 'V3V3'; if (f === 'pwr:1v2') return inR(1.2) ? 'V1V2' : 'V1V1'; if (f === 'pwr:led') return 'VSYS';
    if (f === 'pwr:avdd') return c.role === 'conn_cam' ? 'V2V8_CAM' : inR(1.8) && !inR(3.3) ? VIO : inR(3.3) ? 'V3V3' : inR(2.8) ? 'V2V8' : VIO;
    if (f === 'pwr:vdd') return /AVDD/.test(nm) && inR(2.8) && !inR(1.8) ? 'V2V8' : inR(1.8) ? VIO : inR(3.3) ? 'V3V3' : inR(2.8) ? 'V2V8' : v && v[0] > 3 ? 'VSYS' : VIO;
    if (f === 'pwr:dram') return /VDDQ/.test(nm) ? 'DDR_VDDQ' : /VDD1\b|VDD1$/.test(nm) ? VIO : 'DDR_VDD2'; if (f === 'pwr:core') return 'SOC_' + nm.replace(/_?\d+$/, '').replace(/[^A-Z0-9]+/g, '_'); if (f === 'sim:vcc') return null;
    if (/^pwr:out:/.test(f)) { const t = f.slice(8).toLowerCase(); return t === '1v8' || t === 'vio' || t === 'vddio' ? VIO : t === '3v3' ? 'V3V3' : t === 'vsys' ? 'VSYS' : t === 'wpc' || t === 'vrect' || t === 'vout' ? (one('usbc') ? 'VIN_WPC' : 'VBUS') : c.ref + '_' + t.toUpperCase(); }
    return f.startsWith('pwr:') ? c.ref + '_' + f.slice(4).toUpperCase() : null; };
  const drv = new Set(), pmc = () => comps0().filter(c => c.role === 'soc_pmic'); [...(H ? [H] : []), ...pmc(), ...comps0().filter(c => c.role !== 'soc_pmic')].forEach(c => c.pins.forEach(p => { if (p.type === 'gnd' || p.fn === 'gnd') return join(net('GND', 'GND'), c, p); if (p.fn && (p.fn.startsWith('pwr:') || (p.type === 'power_in' && !p.fn))) { const r = p.fn ? railOf(c, p) : null; if (!r) return; if (p.type === 'power_out' && drv.has(r) && !c.pins.some(q => q !== p && q.net === r)) { p.nc = true; p.note = (p.note ? p.note + '; ' : '') + r + ' already driven: output left open'; return; } p.type === 'power_out' && drv.add(r); join(net(r, 'PWR'), c, p); } }));
  const hasDrv = n => n.nodes.some(x => x.type === 'power_out');
  const loads = {}; comps0().concat(H ? [H] : []).forEach(c => (c.pm.rails || []).forEach(r => { const p = c.pins.find(q => q.fn === r.fn && q.net); p && fin(r.ma_max) && (loads[p.net] = (loads[p.net] || 0) + r.ma_max); }));
  const DEFMA = { VIO_1V8: 150, V3V3: 300, V2V8: 100, V2V8_CAM: 120, V1V2: 300, V1V1: 300 };
  const icPm = ic => ({ src: 'datasheet', complete: !!ic.complete, doc: ic.doc || '', source: ic.source || [], package: ic.package || '', pins: (ic.pins || []).map(a => Array.isArray(a) ? P(a[0], a[1], a[2], a[3], a[4]) : P(a.num, a.name, a.type, a.fn, a.note)), rails: ic.rails || [], ext: [], i2c: null }), icBy = re => (lib.ics || []).find(x => re.test(x.mpn));
  const icComp = (ic, role, sheet, mpn) => { const c = { ref: ref(role === 'esd' ? 'D' : 'U'), role, uid: null, part: { id: ic.part || ic.mpn, mpn: mpn || ic.mpn, mfr: ic.mfr, name: ic.name, datasheet: ic.datasheet }, mpn: mpn || ic.mpn, mfr: ic.mfr, pm: icPm(ic), pins: [], sheet, price: ic.price_q1k_usd }; c.pins = c.pm.pins.map(p => ({ ...p })); comps.push(c); return c; };
  const esd = (list, sheet, why) => { const L = list.filter(n => nets.has(n)); if (!L.length) return; const cands = (lib.ics || []).filter(x => (x.pins || []).some(p => p[3] === 'esd:io')).map(x => ({ x, n: x.pins.filter(p => p[3] === 'esd:io').length })).filter(o => o.n >= L.length).sort((a, b) => a.n - b.n), pick = cands[0]; if (!pick) { L.length > 1 ? L.forEach(n => esd([n], sheet, why)) : pas('tvs', 0, L[0], 'GND', { why, sheet }); return; } const c = icComp(pick.x, 'esd', sheet); c.why = why; let k = 0; c.pins.forEach(p => { p.fn === 'esd:io' ? (L[k] ? join(L[k++], c, p) : (p.nc = true)) : p.fn === 'gnd' || p.type === 'gnd' ? join('GND', c, p) : p.type === 'nc' && (p.nc = true); }); c.near = L[0]; return c; };
  const vbusTvs = () => { const ic = icBy(/TVS2200/); if (!ic || !nets.has('VBUS')) return; const c = icComp(ic, 'esd', 'power'); c.why = 'VBUS surge clamp (22 V working voltage covers 20 V PD)'; c.pins.forEach(p => join(p.fn === 'pwr:vbus' ? 'VBUS' : 'GND', c, p)); };
  const reg = (railName, v) => { const N = nets.get(railName); if (!N || hasDrv(N)) return; const ma = Math.round((loads[railName] || 0) + (DEFMA[railName] || (/^SOC_/.test(railName) ? 1500 : 200))), buck = ma > 300 || (3.8 - v) * ma / 1000 > 0.25, fixedLdo = !buck && ma <= 300 && (Math.abs(v - 1.8) < 0.01 || Math.abs(v - 3.3) < 0.01), ic = buck ? icBy(/TPS62088/) : fixedLdo ? icBy(/TPS7A20/) : icBy(/TLV758/), R = ic ? icComp(ic, buck ? 'buck' : 'ldo', 'power', fixedLdo ? ic.mpn.replace(/TPS7A20(18|33)/, 'TPS7A20' + (v > 3 ? '33' : '18')) : null) : null;
    if (!R) { add('error', 'reg-' + railName, `No regulator in the library for ${railName}.`); return; }
    R.rail = railName; R.v = v; R.ma = ma; const eq = ic.equations || {}, vfb = fin(eq.vfb) ? eq.vfb : 0.6, f = re => R.pins.find(p => re.test(p.fn) || re.test(p.name)), vin = f(/^pwr:vin$|^(VIN|IN)$/), vout = f(/^pwr:out|^(VOUT|OUT)$/), fb = R.pins.find(p => p.fn === 'fb'), en = R.pins.find(p => p.fn === 'en'), sw = R.pins.find(p => p.fn === 'sw');
    vin && join(net('VSYS', 'PWR'), R, vin); vout && join(N, R, vout); R.pins.filter(p => (p.type === 'gnd' || p.fn === 'gnd') && !p.net).forEach(p => join(net('GND', 'GND'), R, p)); en && !en.net && join(net('VSYS', 'PWR'), R, en); let div = null;
    if (fb && !fixedLdo) { const r2 = nearestE(fin(eq.r2_max) ? Math.min(eq.r2_max, 100e3) : 100e3, E96, 'down'), r1 = nearestE(r2 * (v / vfb - 1), E96), vo = vfb * (1 + r1 / r2), fbN = R.ref + '_FB'; if (v <= vfb + 0.005) join(N, R, fb); else { join(fbN, R, fb); pas('res', r1, railName, fbN, { why: `feedback top: Vout = ${vfb}·(1 + R1/R2) = ${r3(vo)} V (${ic.mpn} ${eq.where || ''})`, near: { ref: R.ref, num: fb.num } }); pas('res', r2, fbN, 'GND', { why: 'feedback bottom' + (fin(eq.r2_max) ? ' (R2 ≤ ' + fmtVal(eq.r2_max, 'Ω') + ')' : ''), near: { ref: R.ref, num: fb.num } }); /C4|cff/i.test(String(eq.cff || '')) && pas('cap', nearestE(12e-6 / r2, E24), railName, fbN, { why: 'feed-forward C = 12 µs / R2 (datasheet)', near: { ref: R.ref, num: fb.num } }); div = { r1, r2, vo: r3(vo), err: r3((vo - v) / v * 100), vfb }; } }
    if (sw) { const swN = R.ref + '_SW', L = fin(eq.l_uh) ? eq.l_uh * 1e-6 : 1e-6; join(swN, R, sw); pas('ind', L, swN, railName, { why: `buck inductor ${fmtVal(L, 'H')} per ${ic.mpn} datasheet`, near: { ref: R.ref, num: sw.num } }); }
    const co = String(eq.cout_uf != null ? eq.cout_uf : ''), cm = co.match(/(\d+)\s*x\s*(\d+)/), cin = fin(eq.cin_uf) ? eq.cin_uf * 1e-6 : buck ? 10e-6 : 1e-6;
    pas('cap', cin, 'VSYS', 'GND', { v: 10, why: 'input capacitor (datasheet)', near: vin ? { ref: R.ref, num: vin.num } : null }); (cm ? Array.from({ length: Number(cm[1]) }, () => Number(cm[2]) * 1e-6) : [buck ? 22e-6 : 1e-6]).forEach(cv => pas('cap', cv, railName, 'GND', { v: 6.3, why: 'output capacitor (datasheet)', near: vout ? { ref: R.ref, num: vout.num } : sw ? { ref: R.ref, num: sw.num } : null }));
    R.pins.filter(p => !p.net && (p.fn === 'nc' || p.type === 'nc' || p.type === 'od')).forEach(p => { p.nc = true; });
    ma > 2000 && add('warn', 'reg-load-' + railName, `${railName} load estimate ${ma} mA exceeds the ${ic.mpn} 2 A rating: use a multiphase PMIC channel.`);
    R.calc = { rail: railName, v, ma, topo: buck ? 'buck' : 'LDO', why: buck ? `${ma} mA from VSYS: an LDO would dissipate ${r3((3.8 - v) * ma / 1000)} W` : `${ma} mA, LDO loss ${r3((3.8 - v) * ma / 1000)} W`, div, part: R.mpn }; return R; };
  const vReq = { VIO_1V8: 1.8, V3V3: 3.3, V2V8: 2.8, V2V8_CAM: 2.8, V1V2: 1.2, V1V1: 1.1 };
  const disp = res.items.filter(i => (i.cat === 'display' || i.cat === 'display_ref') && !i.uid.endsWith('#B')), cams = res.items.filter(i => i.cat === 'camera' || i.cat === 'camera_front'), cd = res.items.find(i => i.role === 'conn_display'), cc = res.items.find(i => i.role === 'conn_cam');
  const fpcComp = (src, conn, role, k) => { const pm0 = pinmap(src.p, role, src), pm = { ...pm0, pins: pm0.src === 'datasheet' ? pm0.pins.map(p => ({ ...p, type: 'passive' })) : pm0.pins }, c = comp(role, conn || src, pm, { sheet: role === 'conn_cam' ? 'camera' : 'display', mpn: conn ? conn.p.mpn : 'FPC', mfr: conn ? conn.p.mfr : '', panel: src.p, fpc: true }); c.uid = (conn ? conn.uid : src.uid) + '@' + k; (conn && conn.p && db().pinmaps && db().pinmaps[conn.p.id]) && ((db().pinmaps[conn.p.id].pins || []).length < pm.pins.length) && add('warn', 'fpc-count-' + c.ref, `${src.p.mpn} has ${pm.pins.length} FPC pins but ${conn.p.mpn} has ${db().pinmaps[conn.p.id].pins.length}: an adapter flex or a different connector is needed.`); c.pins.filter(p => p.fn === 'gnd' || /^GND/i.test(p.name)).forEach(p => join(net('GND', 'GND'), c, p)); c.pins.filter(p => p.fn && p.fn.startsWith('pwr:') && !p.net).forEach(p => { const r = railOf({ ...c, role: role }, p); r && join(net(r, 'PWR'), c, p); }); return c; };
  const DC = disp.map((d, k) => fpcComp(d, cd, 'conn_display', k)), CC = cams.map((cm, k) => fpcComp(cm, cc, 'conn_cam', k));
  const lanes = (c, kind) => c.pins.filter(p => kindOf(p.fn) === kind && /^.*:d\d[pn]$/.test(p.fn)).length / 2;
  const mipi = (c, kind, label) => { const L = lanes(c, kind), port = takePort(kind, x => x.pins.filter(p => /d\d[pn]$/.test(p.fn)).length / 2 >= L) || takePort(kind); if (!port) { add('error', kind + '-ports-' + c.ref, `No free host ${kind.toUpperCase()} port for ${label} (${L} lanes).`); return; } const have = port.pins.filter(p => /d\d[pn]$/.test(p.fn)).length / 2; have < L && add('error', kind + '-lanes-' + c.ref, `${label} needs ${L} ${kind.toUpperCase()} lanes; host port ${port.k} has ${have}.`); c.pins.filter(p => kindOf(p.fn) === kind).forEach(p => { const hpin = port.pins.find(q => q.fn === p.fn && !q.net); hpin && join(net(`${port.k}_${p.fn.split(':')[1].toUpperCase()}`, 'MIPI_100'), c, p) && join(nets.get(p.net), H, hpin); }); c.mipi = { kind, port: port.k, lanes: L, have }; };
  const dsiFree = (ports.dsi || []).length, muxIc = H && DC.length === dsiFree + 1 && dsiFree > 0 ? icBy(/TS5MP646/) || icBy(/TS5MP645/) : null, kB = disp.findIndex(x => x.role === 'display_cover'), kA = disp.findIndex(x => x.role === 'display');
  if (muxIc && kB >= 0 && kA >= 0) { const MX = icComp(muxIc, 'dsi_mux', 'display'); MX.why = `${disp.length} panels on ${dsiFree} DSI ports: the top inner panel and the cover panel are never lit together, so they share one port through a 2:1 MIPI switch`; const L = Math.max(lanes(DC[kA], 'dsi'), lanes(DC[kB], 'dsi')), port = takePort('dsi', x => x.pins.filter(p => /d\d[pn]$/.test(p.fn)).length / 2 >= L) || takePort('dsi'), side = q => /^(DA|CLKA)/.test(q.name) ? 'A' : /^(DB|CLKB)/.test(q.name) ? 'B' : 'C'; MX.pins.filter(q => kindOf(q.fn) === 'dsi').forEach(q => { const F = q.fn.split(':')[1].toUpperCase(), sd = side(q); if (sd === 'C') { const hpin = port && port.pins.find(x => x.fn === q.fn && !x.net); hpin ? (join(net(`${port.k}_${F}`, 'MIPI_100'), MX, q), join(`${port.k}_${F}`, H, hpin)) : (q.nc = true); } else { const dc = DC[sd === 'A' ? kA : kB], dp = dc.pins.find(x => x.fn === q.fn && !x.net); dp ? (join(net(`DSIMUX_${sd}_${F}`, 'MIPI_100'), MX, q), join(`DSIMUX_${sd}_${F}`, dc, dp)) : (q.nc = true); } }); MX.pins.forEach(q => { q.net || q.nc || (q.fn === 'gpio' ? gpio('SEL', q, MX, null) : q.fn === 'en' ? join('GND', MX, q) : q.fn.startsWith('pwr:') ? join(net(VIO, 'PWR'), MX, q) : q.type === 'gnd' ? join('GND', MX, q) : (q.nc = true)); }); [kA, kB].forEach(k => { DC[k].mipi = { kind: 'dsi', port: port ? port.k + ' via ' + MX.ref : null, lanes: lanes(DC[k], 'dsi'), have: 4 }; }); notes.push(MX.why + ` (${MX.mpn}, ${MX.ref}).`); add('warn', 'dsi-mux', `${MX.mpn} shares ${port ? port.k : 'a DSI port'} between ${disp[kA].p.mpn} and the cover ${disp[kB].p.mpn}; TI lists it NRND, so confirm stock or a successor.`); }
  DC.forEach((c, k) => { if (c.mipi) return; H && mipi(c, 'dsi', disp[k].p.mpn || disp[k].p.name); });
  CC.forEach((c, k) => H && mipi(c, 'csi', cams[k].p.mpn || cams[k].p.name));
  const i2cDevs = [...comps0(), ...DC, ...CC].filter((c, i, a) => a.indexOf(c) === i && !(['modem', 'wifi', 'ntn', 'gnss', 'uwb'].includes(c.role) && !(c.pm.i2c && c.pm.i2c.addr)) && c.pins.some(p => p.fn === 'i2c:scl') && c.pins.some(p => p.fn === 'i2c:sda') && !c.pins.find(p => p.fn === 'i2c:scl').net), buses = [];
  const addrOf = c => { const a = (c.pm.i2c && c.pm.i2c.addr) || []; return (Array.isArray(a) ? a : [a]).map(x => String(x).toLowerCase()); }, altOf = c => Object.keys((c.pm.i2c && c.pm.i2c.alt) || {}).map(x => x.toLowerCase());
  i2cDevs.forEach(c => { const own = addrOf(c), alts = altOf(c); let placed = false; for (const b of buses) { const use = own.find(a => !b.addr.has(a)) || (own.length ? null : '?') || alts.find(a => !b.addr.has(a)); if ((own.length && own.every(a => b.addr.has(a)) && !alts.some(a => !b.addr.has(a))) || b.devs.length >= 8) continue; const ad = own.find(a => !b.addr.has(a)) || alts.find(a => !b.addr.has(a)) || '?'; b.addr.add(ad); b.devs.push({ c, addr: ad, alt: !own.includes(ad) && ad !== '?' }); placed = true; break; } if (!placed) { const port = takePort('i2c'); if (!port) { add('error', 'i2c-bus-' + c.ref, `No free I²C bus for ${c.mpn} (address ${own.join('/') || 'unknown'} conflicts).`); return; } const b = { k: port.k, port, addr: new Set(), devs: [] }, ad = own[0] || '?'; b.addr.add(ad); b.devs.push({ c, addr: ad, alt: false }); buses.push(b); } });
  buses.forEach(b => { const scl = `${b.k}_SCL`, sda = `${b.k}_SDA`, hs = b.port.pins.find(p => p.fn === 'i2c:scl'), hd = b.port.pins.find(p => p.fn === 'i2c:sda'); hs && join(scl, H, hs); hd && join(sda, H, hd); b.devs.forEach(x => { join(scl, x.c, x.c.pins.find(p => p.fn === 'i2c:scl')); join(sda, x.c, x.c.pins.find(p => p.fn === 'i2c:sda')); x.alt && (x.c.pins.filter(p => /^strap:addr|^addr/i.test(p.fn + ' ' + p.name) && !p.net).forEach(p => join(VIO, x.c, p)), notes.push(`${x.c.mpn} moved to alternate address ${x.addr} on ${b.k}.`)); }); const nDev = b.devs.length, Cb = 10e-12 * (nDev + 1) + 15e-12, vdd = 1.8, rmax = 300e-9 / (0.8473 * Cb), rmin = (vdd - 0.4) / 3e-3, rp = Math.max(nearestE(Math.min(rmax, 10e3), E24, 'down'), nearestE(rmin, E24, 'up')); b.calc = { devices: nDev, cb_pf: Math.round(Cb * 1e12), rmax: Math.round(rmax), rmin: Math.round(rmin), rp, mode: 'Fast-mode 400 kHz, tr ≤ 300 ns', basis: 'NXP UM10204: Rp(max) = tr / (0.8473·Cb), Rp(min) = (VDD − VOL)/IOL; Cb ≈ 10 pF per device + 15 pF wiring' }; pas('res', rp, scl, VIO, { why: `${b.k} SCL pull-up (${b.calc.rmin}–${b.calc.rmax} Ω window)`, sheet: 'compute' }); pas('res', rp, sda, VIO, { why: `${b.k} SDA pull-up`, sheet: 'compute' }); pas('tp', 0, scl, null, { sheet: 'ui' }); pas('tp', 0, sda, null, { sheet: 'ui' }); });
  i2cDevs.forEach(c => { const all = addrOf(c); buses.forEach(b => { const same = b.devs.filter(x => x.addr !== '?' && x.addr === (b.devs.find(y => y.c === c) || {}).addr); same.length > 1 && add('error', 'i2c-conflict-' + b.k + c.ref, `${b.k} address ${same[0].addr} used by ${same.map(x => x.c.mpn).join(' and ')}.`); }); all.length || add('info', 'i2c-addr-' + c.ref, `${c.mpn}: I²C address not in the stored pin map.`); });
  const bus = (kind, c, label, pairs) => { if (!H || !c.pins.some(p => kindOf(p.fn) === kind && !p.net)) return; const grp = new Map(); c.pins.filter(p => kindOf(p.fn) === kind && !p.net).forEach(p => { const g = String(p.name).toUpperCase().split('/')[0].replace(/_?(TXD?|RXD?|RTS|CTS|RTSN|CTSN|CLK|CMD|D\d|DAT\d|SCK|MOSI|MISO|CSN?\d?|BCLK|LRCK|WS|DIN|DOUT|MCLK|SDI\d?|SDO\d?)(_?N)?$/, ''); grp.has(g) || grp.set(g, []); grp.get(g).push(p); }); const keys = [...grp.keys()], main = keys.find(g => c.role === 'wifi' && kind === 'uart' && /BT/.test(g)) || keys.find(g => !g || /^(UART|MAIN)?\d?$/.test(g)) || keys[0], mine = grp.get(main); keys.filter(g => g !== main).forEach(g => grp.get(g).forEach(p => { p.type === 'in' ? (p.skip = true) : (p.nc = true); })); const want = mine.map(p => (pairs && pairs[p.fn]) || p.fn), port = takePort(kind, want); if (!port) { const opt = (kind === 'i2s' && ['haptic_drv', 'flash_drv'].includes(c.role)) || (kind === 'uart' && ['dock_link', 'modem'].includes(c.role)) || (kind === 'spi' && c.role !== 'uwb') || (kind === 'pcie' && c.role === 'wifi' && c.pins.some(p => kindOf(p.fn) === 'sdio' && p.net)); add(opt ? 'info' : 'error', kind + '-' + c.ref, `No free host ${kind.toUpperCase()} for ${label}${opt ? ' (optional interface left unconnected)' : ''}.`); return; } mine.forEach(p => { const want = (pairs && pairs[p.fn]) || p.fn, hpin = port.pins.find(q => q.fn === want && !q.net) || port.pins.find(q => q.fn === want); if (!hpin) return; const nm = `${port.k}_${hpin.fn.split(':')[1].toUpperCase()}`; const N = nets.get(nm) || net(nm, kind === 'sdio' ? 'SDIO' : 'Default'); join(N, c, p); !hpin.net && join(N, H, hpin); }); };
  const X = { 'uart:tx': 'uart:rx', 'uart:rx': 'uart:tx', 'uart:rts': 'uart:cts', 'uart:cts': 'uart:rts' };
  comps0().filter(c => !c.fpc).forEach(c => { bus('uart', c, c.mpn, X); bus('sdio', c, c.mpn); bus('spi', c, c.mpn); bus('i2s', c, c.mpn); bus('pcie', c, c.mpn); });
  H && comps0().filter(c => ['lpddr', 'ufs'].includes(c.role)).forEach((c, k) => { const lp5 = /LPDDR5|LP5/i.test(JSON.stringify((c.part && c.part.specs) || {}) + (c.part && c.part.name)), pref = lp5 ? 'LP5_' : 'LP4X_', hk = new Map(); H.pins.filter(q => kindOf(q.fn) === 'ddr' && !q.net).forEach(q => { const key = ddrKey(q.name, pref); hk.has(key) || hk.set(key, q); }); c.pins.filter(p => /^(ddr|ufs):/.test(p.fn) && !p.net).forEach(p => { if (p.fn === 'ddr:zq') return pas('res', 240, join(c.ref + '_ZQ', c, p), 'DDR_VDDQ', { why: 'LPDDR ZQ calibration resistor 240 Ω ±1% to VDDQ (JEDEC)', near: { ref: c.ref, num: p.num }, sheet: 'compute' }); if (p.fn === 'ddr:odt') return join('DDR_VDD2', c, p); const key = kindOf(p.fn) === 'ddr' ? ddrKey(p.name) : null, hpin = key ? hk.get(key) : (H.pins.find(q => q.fn === p.fn && !q.net) || H.pins.find(q => q.fn === p.fn)); if (!hpin) return; const nm = hpin.net || 'DDR' + k + '_' + (key || p.fn.split(':')[1].toUpperCase()); hpin.type === 'in' && p.type === 'in' && (hpin.type = 'out'); join(net(nm, kindOf(p.fn) === 'ddr' ? 'DDR_40' : 'MIPI_100'), c, p); hpin.net || join(nm, H, hpin); }); H.pins.filter(q => q.fn === 'ddr:zq' && !q.net).forEach(q => pas('res', 240, join('SOC_' + q.name.replace(/[^A-Z0-9]+/gi, '_'), H, q), 'GND', { why: 'DDR PHY ZQ resistor 240 Ω ±1%', near: { ref: H.ref, num: q.num }, sheet: 'compute' })); });
  const mics = comps0().filter(c => /^mic/.test(c.role)); if (mics.length && H) { const hc = hp('pdm:clk')[0], hd = H.pins.filter(p => p.fn === 'pdm:data'); hc && join('PDM_CLK', H, hc); mics.forEach((m, k) => { const ck = m.pins.find(p => p.fn === 'pdm:clk'), dt = m.pins.find(p => p.fn === 'pdm:data'), sel = m.pins.find(p => /strap:lr|^(sel|lr|l\/r)$/i.test(p.fn + '|' + p.name)); ck && join('PDM_CLK', m, ck); const dn = 'PDM_DATA' + (k >> 1); dt && join(dn, m, dt); hd[k >> 1] && !hd[k >> 1].net && join(dn, H, hd[k >> 1]); sel && !sel.net && join(k % 2 ? VIO : 'GND', m, sel); }); hc && pas('res', 33, null, null, { why: 'PDM clock series termination (place at host)', dnp: true, sheet: 'audio' }); }
  const usbc = one('usbc'), pd = one('usb_pd'); if (usbc) { const g = f => usbc.pins.filter(p => p.fn === f), port = H ? takePort('usb') : null, dpN = port ? `${port.k}_DP` : 'USB_DP', dnN = port ? `${port.k}_DN` : 'USB_DN'; [...g('usbc:dp1'), ...g('usbc:dp2'), ...g('usb:dp')].forEach(p => join(net(dpN, 'USB_90'), usbc, p)); [...g('usbc:dn1'), ...g('usbc:dn2'), ...g('usb:dn')].forEach(p => join(net(dnN, 'USB_90'), usbc, p)); port && port.pins.forEach(p => p.fn === 'usb:dp' ? join(dpN, H, p) : p.fn === 'usb:dn' && join(dnN, H, p)); ['usbc:cc1', 'usbc:cc2'].forEach((f, k) => g(f).forEach(p => { const nm = 'USB_CC' + (k + 1); join(net(nm), usbc, p); const q = pd && pd.pins.find(x => x.fn === f && !x.net); q ? join(nm, pd, q) : pas('res', 5.1e3, nm, 'GND', { why: 'USB-C sink Rd = 5.1 kΩ (USB Type-C spec) because no PD controller is fitted', sheet: 'power' }); })); ['usbc:sbu1', 'usbc:sbu2'].forEach(f => g(f).forEach(p => { p.nc = true; })); vbusTvs(); esd([dpN, dnN, 'USB_CC1', 'USB_CC2'], 'power', 'IEC 61000-4-2 ESD on the USB-C connector'); }
  const chg = one('charger'), bat = one('conn_batt'); if (chg && bat) { const ts = bat.pins.find(p => p.fn === 'ts'), cts = chg.pins.find(p => p.fn === 'ts'); ts && cts && (join('BAT_NTC', bat, ts), join('BAT_NTC', chg, cts)); }
  const radio = one('modem') || (H && H.pins.some(p => kindOf(p.fn) === 'sim') ? H : null); ['sim', 'esim'].forEach(r => { const s = one(r); if (!s || !radio) return; s.pins.filter(p => kindOf(p.fn) === 'sim').forEach(p => { const hpin = radio.pins.find(q => q.fn === p.fn), nm = 'USIM_' + p.fn.split(':')[1].toUpperCase(); join(net(nm, p.fn === 'sim:vcc' ? 'PWR' : 'Default'), s, p); hpin && !hpin.net && join(nm, radio, hpin); }); });
  nets.has('USIM_VCC') && !nets.get('USIM_VCC').nodes.some(x => x.type === 'power_out') && (n => { n.nodes.forEach(x => { const c = comps.find(q => q.ref === x.ref), p = c && c.pins.find(q => q.num === x.num); p && p.type === 'power_out' && (x.type = 'power_out'); }); })(nets.get('USIM_VCC'));
  one('sim') && esd(['USIM_CLK', 'USIM_IO', 'USIM_RST', 'USIM_VCC'], 'radio', 'ESD on the SIM tray contacts');
  const ANT = { ant_main: ['modem', 'rf:ant'], ant_div: ['modem', 'rf:ant2'], ant_wifi: ['wifi', 'rf:ant'], ant_gnss: ['gnss', 'rf:gnss'] }; Object.entries(ANT).forEach(([r, [src, f]]) => (C[r] || []).forEach(a => { const s = one(src) || (r === 'ant_gnss' ? one('modem') || H : r === 'ant_main' ? one('ntn') || H : H); const sp = s && (s.pins.find(p => p.fn === f && !p.net) || s.pins.find(p => kindOf(p.fn) === 'rf' && !p.net)), fp = a.pins.find(p => kindOf(p.fn) === 'rf') || a.pins[0]; if (!sp || !fp) return; const nA = r.toUpperCase() + '_RF', nB = r.toUpperCase() + '_FEED'; join(net(nA, 'RF_50'), s, sp); join(net(nB, 'RF_50'), a, fp); pas('res', 0, nA, nB, { why: 'π-match series element (0 Ω until tuned on the antenna analyser)', sheet: 'radio', near: { ref: a.ref, num: fp.num } }); pas('cap', 1e-12, nA, 'GND', { why: 'π-match shunt (DNP until tuned)', dnp: true, sheet: 'radio' }); pas('cap', 1e-12, nB, 'GND', { why: 'π-match shunt (DNP until tuned)', dnp: true, sheet: 'radio' }); a.pins.filter(p => !p.net && p !== fp).forEach(p => join('GND', a, p)); }));
  const ntn = one('ntn'), ntA = ntn && ntn.pins.find(p => kindOf(p.fn) === 'rf' && !p.net); ntA && (C.ant_main || []).length && (join(net('NTN_RF', 'RF_50'), ntn, ntA), add('warn', 'ntn-ant', `${ntn.mpn} RF port needs its own antenna or an RF switch to share the main antenna; left as a separate NTN_RF net.`));
  const pairUp = (a, b, fa, fb, nm, why) => { const A = one(a), B = one(b); if (!A || !B) return; fa.forEach((f, k) => { const pa = A.pins.find(p => p.fn === f && !p.net), pb = B.pins.find(p => p.fn === fb[k] && !p.net) || B.pins.filter(p => !p.net && p.fn !== 'gnd')[k]; pa && pb && (join(nm + (k + 1), A, pa), join(nm + (k + 1), B, pb)); }); why && notes.push(why); };
  pairUp('qi_rx', 'qi_coil', ['coil:ac1', 'coil:ac2'], ['coil:ac1', 'coil:ac2'], 'QI_AC', 'Qi coil wired to the receiver AC pins; resonant caps per the receiver datasheet.');
  pairUp('nfc', 'nfc_coil', ['coil:ac1', 'coil:ac2'], ['coil:ac1', 'coil:ac2'], 'NFC_ANT', 'NFC coil matching network (EMC filter + series/parallel caps) must be tuned per NXP AN11756.');
  pairUp('haptic_drv', 'haptic', ['mot+', 'mot-'], ['mot+', 'mot-'], 'HAPTIC_', null);
  (one('codec') ? [['speaker', 'SPK'], ['receiver', 'RCV']] : []).forEach(([r, nm], k) => { const s = one(r), cd = one('codec'); if (!s) return; ['spk+', 'spk-'].forEach((f, j) => { const pa = cd.pins.filter(p => p.fn === f && !p.net)[0], pb = s.pins.find(p => p.fn === f && !p.net); pa && pb && (join(nm + (j ? '_N' : '_P'), cd, pa), join(nm + (j ? '_N' : '_P'), s, pb)); }); });
  ['speaker', 'receiver'].forEach(r => { const s = one(r); s && !one('codec') && s.pins.some(p => !p.net && p.fn !== 'gnd') && add('warn', 'amp-' + r, `${s.mpn}: no codec or smart amplifier in the design, so it is not driven. Add one in the Audio step.`); });
  const fd = one('flash_drv'), fl = one('flash'); fd && fl && (p => { const a = fd.pins.find(q => q.fn === 'led' && !q.net), b = fl.pins.find(q => q.fn === 'led'); a && b && (join('FLASH_LED', fd, a), join('FLASH_LED', fl, b)); fl.pins.filter(q => !q.net && (q.fn === 'gnd' || /K|CATH/i.test(q.name))).forEach(q => join('GND', fl, q)); })();
  ['btn_power', 'btn_up', 'btn_down'].forEach(r => (C[r] || []).forEach(s => { const k = s.pins.find(p => p.fn === 'key') || s.pins[0], hk = H && (r === 'btn_power' ? H.pins.find(p => (p.fn === 'pwrkey' || /PWRKEY|PWR_KEY|ONKEY/i.test(p.name)) && !p.net) : null), nm = { btn_power: 'KEY_PWR_N', btn_up: 'KEY_VOLUP_N', btn_down: 'KEY_VOLDN_N' }[r]; join(net(nm), s, k); s.pins.filter(p => !p.net).forEach(p => join('GND', s, p)); hk ? join(nm, H, hk) : (g => g && join(nm, H, g))(gpioPool()[0]); pas('res', 10e3, nm, VIO, { why: 'key pull-up', sheet: 'ui' }); esd([nm], 'ui', 'ESD on the key flex'); }));
  const RADIO = ['modem', 'wifi', 'ntn', 'gnss', 'uwb', 'nfc', 'dock_link'], ctl = [...comps0(), ...DC, ...CC]; ctl.forEach(c => c.pins.filter(p => !p.net).forEach(p => { const f = p.fn, kindC = f === 'en' || f === 'pwrkey' ? 'en' : f === 'rst_n' || f === 'pwdn' ? 'rst' : ['int', 'irq_n', 'wake'].includes(f) ? 'int' : null; if (RADIO.includes(c.role) && kindC && ((c.used = c.used || {})[kindC] || /EPHY|ETH|PCM|JTAG|DBG|BOOT|USB_|SD_|ADC|STATUS|NET_|AP_READY|SLEEP_IND|W_DISABLE/i.test(p.name))) return; RADIO.includes(c.role) && kindC && (c.used[kindC] = true); if (f === 'int' || f === 'irq_n' || f === 'wake') gpio(p.name, p, c, p.type === 'od' || f === 'irq_n' || isAct(p.name) ? VIO : null); else if (f === 'rst_n' || f === 'pwdn' || (f === 'en' && ['modem', 'wifi', 'ntn', 'gnss', 'uwb', 'nfc', 'conn_cam', 'conn_display', 'dock_link'].includes(c.role))) gpio(p.name, p, c, f === 'rst_n' ? VIO : null); else if (f === 'en') join(isAct(p.name) ? 'GND' : (c.pins.some(q => q.net === 'VBAT') ? 'VSYS' : VIO), c, p); else if (f === 'gpio' && c.fpc) gpio(p.name, p, c, null, true); else if (kindOf(f) === 'i2s' && f === 'i2s:mclk' && c.fpc && H) { const hm = H.pins.find(q => q.fn === 'i2s:mclk' && !q.net) || H.pins.find(q => /MCLK|CLKOUT/i.test(q.name) && !q.net); hm ? (join('CAM_MCLK' + c.ref, c, p), join('CAM_MCLK' + c.ref, H, hm)) : gpio('MCLK', p, c, null); } }));
  const derived = Object.keys(vReq).filter(r => nets.has(r) && !hasDrv(nets.get(r)));
  H && derived.includes(VIO) && (() => { const o18 = H.pins.find(p => p.type === 'power_out' && /1V8|1P8|VIO|VDDIO/i.test(p.name + p.fn)); o18 && !o18.net && join(VIO, H, o18); })();
  const pmicP = one('soc_pmic'); pmicP && [...nets.values()].filter(n => /^(SOC_|DDR_)/.test(n.name) && !hasDrv(n)).forEach(n => { const key = n.name.replace(/^SOC_/, '').replace(/^VDD_?/, ''), o = pmicP.pins.find(p => p.type === 'power_out' && !p.net && new RegExp(key.split('_')[0], 'i').test(p.name)); o && join(n, pmicP, o); });
  const regs = [...Object.keys(vReq).filter(r => nets.has(r) && !hasDrv(nets.get(r))).map(r => reg(r, vReq[r])), ...[...nets.values()].filter(n => /^(SOC_|DDR_)/.test(n.name) && !hasDrv(n)).map(n => { const v = /VDDQ/.test(n.name) ? 0.5 : /VDD2/.test(n.name) ? 1.05 : /LOGIC/.test(n.name) ? 0.75 : 0.8; add('warn', 'rail-' + n.name, `${n.name} (${v} V): no PMIC channel matched; a discrete buck is fitted. Check the SoC hardware guide for the real rail and sequence.`); v < 0.6 && add('warn', 'rail-min-' + n.name, `${n.name} needs ${v} V, below the 0.6 V feedback of the library buck: it must come from the SoC PMIC (set to 0.6 V here).`); return reg(n.name, Math.max(0.6, v)); })].filter(Boolean);
  const decap = (c, p, rn) => { const N = nets.get(rn); if (!N || rn === 'GND') return; pas('cap', 100e-9, rn, 'GND', { v: rn === 'VBUS' ? 25 : 6.3, why: `decoupling at ${c.ref}.${p.name}`, near: { ref: c.ref, num: p.num }, sheet: c.sheet }); };
  [...comps0(), ...(H ? [H] : [])].filter(c => c.role !== 'buck' && c.role !== 'ldo' && !c.fpc).forEach(c => { const done = new Set(), ext = c.pm.ext || []; ext.forEach(e => { const pins = (e.pins || []).map(nm => c.pins.find(p => p.name === nm || p.num === String(nm))).filter(Boolean), v = parseVal(e.value), qty = Math.max(1, Math.min(6, Number(e.qty) || 1)); if (!pins.length || !v) return; const kind = ['cap', 'res', 'ind', 'ferrite', 'ntc'].includes(e.kind) ? e.kind : null; if (!kind) return; for (let q = 0; q < qty; q++) { const a = pins[0], b = pins[1]; const an = a.net || (join(c.ref + '_' + a.name, c, a)), bn = b ? (b.net || join(c.ref + '_' + b.name, c, b)) : kind === 'cap' ? 'GND' : kind === 'ind' ? (c.pins.find(p => p.fn === 'pwr:vsys' || /^pwr:out/.test(p.fn)) || {}).net || 'VSYS' : /pull-?up|to v|vdd/i.test(e.why || '') ? VIO : 'GND'; an !== bn && pas(kind, v, an, bn, { v: parseV(e.rating) || (an === 'VBUS' ? 25 : 6.3), why: (e.why || 'datasheet') + (e.where ? ' (' + e.where + ')' : ''), near: { ref: c.ref, num: a.num }, sheet: c.sheet }); done.add(an); } }); c.pins.filter(p => p.type === 'power_in' && p.net && p.net !== 'GND').forEach(p => { c.pins.filter(q => q.net === p.net).indexOf(p) < (c === H ? 6 : done.has(p.net) ? 1 : 2) && decap(c, p, p.net); }); c.pins.some(p => p.net === 'VSYS' && p.type === 'power_in') && ['modem', 'ntn', 'som', 'soc_pmic', 'wifi'].includes(c.role) && pas('cap', c.role === 'modem' || c.role === 'ntn' ? 100e-6 : 22e-6, 'VSYS', 'GND', { v: 6.3, why: c.role === 'modem' || c.role === 'ntn' ? 'bulk for ≈2 A transmit bursts (module hardware design guide)' : 'bulk on the module supply', near: { ref: c.ref, num: (c.pins.find(p => p.net === 'VSYS') || {}).num }, sheet: c.sheet }); });
  [...nets.values()].filter(n => n.cls === 'PWR' || n.name === 'GND').forEach(n => pas('tp', 0, n.name, null, { sheet: 'ui', why: 'rail test point' }));
  const dbgU = H && takePort('uart'); dbgU && dbgU.pins.filter(p => !p.net && /uart:(tx|rx)$/.test(p.fn)).forEach(p => { const nm = `${dbgU.k}_${p.fn.split(':')[1].toUpperCase()}_DBG`; join(nm, H, p); pas('tp', 0, nm, null, { sheet: 'ui', why: 'debug console' }); });
  ctl.concat(H ? [H] : [], regs).forEach(c => c.pins.filter(p => !p.net && !p.nc).forEach(p => { const f = p.fn, t = p.type; if (t === 'in' && !/^(pdm|i2s|spi|sdio|uart|dsi|csi|usb|pcie)/.test(f) && c !== H) { const up = isAct(p.name) || f === 'en' || f === 'rst_n' || f === 'pwdn'; pas('res', 10e3, join(c.ref + '_' + p.name.replace(/[^A-Za-z0-9]/g, ''), c, p), up ? VIO : 'GND', { why: `${up ? 'pull-up' : 'pull-down'}: unused input ${p.name} tied to its inactive level`, near: { ref: c.ref, num: p.num }, sheet: c.sheet }); p.tied = true; } else p.nc = true; }));
  const ncCount = comps.reduce((s, c) => s + c.pins.filter(p => p.nc).length, 0);
  const sources = new Set(['VBUS', 'VBAT', 'GND', 'VIN_WPC']); [...nets.values()].forEach(n => { n.flag = (n.cls === 'PWR' || n.name === 'GND') && !hasDrv(n) && (sources.has(n.name) || n.nodes.some(x => x.type === 'passive')); });
  [...nets.values()].filter(n => (n.cls === 'PWR') && !hasDrv(n) && !n.flag && n.nodes.some(x => x.type === 'power_in')).forEach(n => add('error', 'undriven-' + n.name, `Power net ${n.name} has loads but no source.`));
  [...nets.values()].filter(n => new Set(n.nodes.filter(x => x.type === 'power_out').map(x => x.ref)).size > 1).forEach(n => add('error', 'multi-drive-' + n.name, `Power net ${n.name} is driven by ${[...new Set(n.nodes.filter(x => x.type === 'power_out').map(x => x.ref))].join(', ')}.`));
  [...nets.values()].filter(n => n.nodes.length === 1 && !comps.find(c => c.ref === n.nodes[0].ref && c.kind === 'tp')).forEach(n => { const x = n.nodes[0], c = comps.find(q => q.ref === x.ref); add('info', 'single-' + n.name, `${n.name} only reaches ${x.ref}.${x.name}; a test point is added.`); pas('tp', 0, n.name, null, { sheet: c ? c.sheet : 'ui' }); });
  H && H.pins.filter(p => p.type === 'in' && p.net).forEach(p => { const n = nets.get(p.net); n && !n.nodes.some(x => !(x.ref === H.ref && x.num === p.num) && x.type !== 'in') && (p.type = 'io', n.nodes.filter(x => x.ref === H.ref && x.num === p.num).forEach(x => { x.type = 'io'; }), p.note = (p.note ? p.note + '; ' : '') + 'direction set by pinmux'); });
  const floating = []; comps.forEach(c => c.pins.filter(p => p.type === 'in' && p.net).forEach(p => { const n = nets.get(p.net); n && !n.flag && n.name !== 'GND' && !n.nodes.some(x => x.ref !== c.ref || x.num !== p.num ? ['out', 'io', 'od', 'power_out', 'passive', 'power_in', 'bidirectional', 'gnd'].includes(x.type) || (comps.find(q => q.ref === x.ref) || {}).role === 'passive' : false) && floating.push(c.ref + '.' + p.name); }));
  floating.forEach(f => add('error', 'float-' + f, `Input ${f} has no driver.`));
  const powerPins = comps.reduce((s, c) => s + c.pins.filter(p => p.type === 'power_in' || p.type === 'gnd').length, 0), powerOpen = comps.flatMap(c => c.pins.filter(p => (p.type === 'power_in' || p.type === 'gnd') && !p.net).map(p => c.ref + '.' + p.name));
  powerOpen.forEach(x => add('error', 'power-open-' + x, `Power pin ${x} is not connected.`));
  const lanesRows = [...DC, ...CC].map(c => ({ ref: c.ref, part: c.panel.mpn, kind: c.mipi ? c.mipi.kind : c.sheet === 'display' ? 'dsi (mux)' : 'none', port: c.mipi ? c.mipi.port : null, lanes: c.mipi ? c.mipi.lanes : null, have: c.mipi ? c.mipi.have : null, ok: c.mipi ? c.mipi.have >= c.mipi.lanes : false }));
  const passives = comps.filter(c => c.role === 'passive'), synth = comps.filter(c => c.pm && c.pm.src === 'synth' && c.role !== 'passive').map(c => c.ref + ' ' + c.mpn);
  synth.length && add('warn', 'synth-pins', `${synth.length} parts use interface-level placeholder pins (no public pin map): ${synth.join(', ')}.`);
  const bomP = Object.values(passives.reduce((m, c) => { const k = c.kind + '|' + c.mpn + '|' + c.label + (c.dnp ? '|DNP' : ''); (m[k] = m[k] || { kind: c.kind, value: c.label, mpn: c.mpn, mfr: c.mfr, size: c.size, refs: [], dnp: c.dnp, url: c.url }).refs.push(c.ref); return m; }, {}));
  return { comps, nets: [...nets.values()], buses: buses.map(b => ({ k: b.k, devs: b.devs.map(x => ({ ref: x.c.ref, mpn: x.c.mpn, addr: x.addr, alt: x.alt })), calc: b.calc })), regs: regs.map(r => ({ ref: r.ref, ...r.calc })), lanes: lanesRows, checks, notes, bomP, stats: { comps: comps.length, ics: comps.filter(c => c.role !== 'passive').length, passives: passives.length, nets: nets.size, pins: comps.reduce((s, c) => s + c.pins.length, 0), powerPins, powerOpen: powerOpen.length, nc: ncCount, floating: floating.length, synth: synth.length, datasheet: comps.filter(c => c.pm && c.pm.src === 'datasheet').length, errors: checks.filter(c => c.sev === 'error').length, warns: checks.filter(c => c.sev === 'warn').length } };
}
export function choose(kind, value, vmin, lib) {
  const L = lib || db().passives || {}, series = L.series || [], caps = L.caps || [], ics = L.ics || [];
  if (kind === 'res' || kind === 'ntc') { const s = series.find(x => x.kind === 'res' && x.size === '0201') || series.find(x => x.kind === 'res'); const code = yageoCode(value); return s ? { mpn: value === 0 ? (s.zero_mpn || String(s.mpn_pattern || '').replace(/\{R\}|\{code\}/, '0R')) : String(s.mpn_pattern || '').replace(/\{R\}|\{code\}/, code), mfr: s.mfr, size: s.size, url: (s.source || [])[0] || null } : { mpn: 'RC0201FR-07' + code + 'L', mfr: 'Yageo', size: '0201', url: null }; }
  if (kind === 'cap') { const ok = caps.filter(c => fin(c.value_f) && (c.v || 0) >= vmin).sort((a, b) => Math.abs(Math.log(a.value_f / value)) - Math.abs(Math.log(b.value_f / value)) || (a.size || '').localeCompare(b.size || '')), c = ok.find(x => Math.abs(Math.log(x.value_f / value)) < 0.05) || (value >= 1e-7 ? ok.filter(x => x.value_f >= value * 0.999 && x.value_f <= value * (value <= 1e-6 ? 10 : 2.2)).sort((a, b) => a.value_f - b.value_f)[0] : null) || null, code = v => { const pf = Math.round(v / 1e-12 * 10) / 10; return pf < 10 ? pf.toFixed(1).replace('.', 'R') : String(Math.round(pf)).slice(0, 2) + (String(Math.round(pf)).length - 2); }; if (c) return { mpn: c.mpn, mfr: c.mfr, size: c.size, url: c.url || null, note: Math.abs(Math.log(c.value_f / value)) < 0.05 ? '' : 'next larger library value ' + fmtVal(c.value_f, 'F') }; if (value <= 1e-9 + 1e-15 && value >= 1e-12) { const v = nearestE(value, E24); return { mpn: 'GRM0335C1H' + code(v) + (v < 10e-12 ? 'C' : 'J') + 'A01D', mfr: 'Murata', size: '0201', url: null, pattern: true, note: 'C0G 50 V 0201 series ordering code (GRM0335C1H); verify stock' }; } if (value < 1e-7) { const v = nearestE(value, E24); return { mpn: 'GRM033R71C' + code(v) + 'KA01D', mfr: 'Murata', size: '0201', url: null, pattern: true, note: 'X7R 16 V 0201 series ordering code (GRM033R71C); verify stock' }; } return { mpn: null, mfr: '', size: value > 4.7e-6 ? '0603' : value > 1e-6 ? '0402' : '0201', url: null, note: 'no library part of this value: select one' }; }
  if (kind === 'ind' || kind === 'ferrite') { const s = series.find(x => x.kind === kind); const ex = s && (s.examples || []).find(e => Math.abs(Math.log((parseVal(e.value) || 1) / value)) < 0.1); return s ? { mpn: ex ? ex.mpn : null, mfr: s.mfr, size: s.size, url: ex ? ex.url : (s.source || [])[0] || null } : { mpn: null, mfr: '', size: '0805', url: null }; }
  if (kind === 'tvs') { const t = ics.find(x => /esd|tvs/i.test((x.name || '') + (x.kind || ''))); return t ? { mpn: t.mpn, mfr: t.mfr, size: t.package || '', url: t.datasheet || null } : { mpn: null, mfr: '', size: '0201', url: null }; }
  if (kind === 'tp') { const t = L.testpoint || {}; return { mpn: t.mpn || null, mfr: t.mfr || '', size: t.style || 'pad 1.0 mm', url: null }; }
  return { mpn: null, mfr: '', size: '', url: null };
}
