import { K } from './catalog.js';
import { db } from './parts.js';
import { pairForce, magnetModel, dipoleCloud, fieldAt } from './hinge.js';
const fin = v => typeof v === 'number' && Number.isFinite(v), r2 = v => Math.round(v * 100) / 100;
const EDGE_N = { E: [1, 0], W: [-1, 0], N: [0, 1], S: [0, -1] };
export function tileMatrix(t, tile, dims, tA) {
  const [w, l, th] = dims, gap = 0.4, rad = tile.rot * Math.PI / 180, c = Math.round(Math.cos(rad)), s = Math.round(Math.sin(rad)), fy = tile.face === 'down' ? -1 : 1;
  const z0 = tile.face === 'up' ? (tile.level === -1 ? -th : tile.level === 1 ? tA : 0) : (tile.level === -1 ? 0 : tile.level === 1 ? tA + th : th);
  const x0 = tile.gx * (w + gap), y0 = tile.gy * (l + gap);
  return { p: q => [x0 + c * q[0] - s * fy * q[1], y0 + s * q[0] + c * fy * q[1], z0 + fy * q[2]], v: q => [c * q[0] - s * fy * q[1], s * q[0] + c * fy * q[1], fy * q[2]], m: [c, s, 0, 0, -s * fy, c * fy, 0, 0, 0, 0, fy, 0, x0, y0, z0, 1], x0, y0, z0 };
}
const worldBox = (T, b) => { const pts = []; for (const x of [b[0], b[3]]) for (const y of [b[1], b[4]]) for (const z of [b[2], b[5]]) pts.push(T.p([x, y, z])); return [0, 1, 2].map(k => Math.min(...pts.map(p => p[k]))).concat([0, 1, 2].map(k => Math.max(...pts.map(p => p[k])))); };
const ovl = (a, b, tol) => a[0] < b[3] + tol && b[0] < a[3] + tol && a[1] < b[4] + tol && b[1] < a[4] + tol && a[2] < b[5] + tol && b[2] < a[5] + tol;
function magsWorld(res, T, roles) { return res.items.filter(i => i.cat === 'magnet' && roles.includes(i.role)).map(i => { const m = magnetModel(i), dir = [0, 0, 0]; dir[m.ax] = i.magSign || 1; const v = T.v(dir), ax = v.findIndex(x => Math.abs(x) > 0.5), dims = (q => [0, 1, 2].map(k => Math.abs(q[k])))(T.v(m.dims)); return { it: i, c: T.p(m.c), ax, sign: Math.sign(v[ax]), dims, J: m.J }; }); }
export function systemStudy(d, rA, rB) {
  const sy = d.system; if (!sy) return null;
  const R = { A: rA, B: rB || rA }, tA = rA.g.t, tiles = sy.tiles.map((t, i) => { const res = R[t.type], dims = [res.g.w, res.g.l, res.g.t]; return { i, ...t, res, dims, T: tileMatrix(null, t, dims, tA) }; });
  tiles.forEach(t => { t.box = [t.T.p([-t.dims[0] / 2, -t.dims[1] / 2, 0]), t.T.p([t.dims[0] / 2, t.dims[1] / 2, t.dims[2]])].reduce((a, p) => a ? [Math.min(a[0], p[0]), Math.min(a[1], p[1]), Math.min(a[2], p[2]), Math.max(a[3], p[0]), Math.max(a[4], p[1]), Math.max(a[5], p[2])] : [p[0], p[1], p[2], p[0], p[1], p[2]], null); });
  const contacts = [], clash = [];
  for (let i = 0; i < tiles.length; i++) for (let j = i + 1; j < tiles.length; j++) {
    const a = tiles[i], b = tiles[j], A = a.box, B = b.box, zOv = Math.min(A[5], B[5]) - Math.max(A[2], B[2]), xOv = Math.min(A[3], B[3]) - Math.max(A[0], B[0]), yOv = Math.min(A[4], B[4]) - Math.max(A[1], B[1]);
    if (xOv > 0.5 && yOv > 0.5 && zOv > 0.05) { clash.push([i, j]); continue; }
    const kind = zOv > 0.5 && xOv > -1 && xOv < 0.5 && yOv > 5 ? 'edge' : zOv > 0.5 && yOv > -1 && yOv < 0.5 && xOv > 5 ? 'edge' : Math.abs(zOv) < 0.6 && xOv > 5 && yOv > 5 ? 'face' : null;
    if (!kind) continue;
    const roles = kind === 'edge' ? ['dock_mag'] : ['dock_back'], ma = magsWorld(a.res, a.T, roles), mb = magsWorld(b.res, b.T, roles), pairs = [];
    ma.forEach(m => { const o = mb.filter(q => q.ax === m.ax).map(q => ({ q, lat: Math.hypot(...[0, 1, 2].filter(k => k !== m.ax).map(k => q.c[k] - m.c[k])), ax: Math.abs(q.c[m.ax] - m.c[m.ax]) })).filter(x => x.lat < Math.max(2, m.dims[(m.ax + 1) % 3] / 2) && x.ax < 12).sort((x, y) => x.lat - y.lat)[0]; if (!o) return; const f = pairForce({ c: m.c, dims: m.dims, ax: m.ax, J: m.J }, { c: o.q.c, dims: o.q.dims, ax: m.ax, J: o.q.J }), att = m.sign === o.q.sign; pairs.push({ a: m.it.uid, b: o.q.it.uid, gap: r2(f.gap), n: (att ? 1 : -1) * f.hold, attract: att, lat: r2(o.lat) }); });
    const net = pairs.reduce((s, p) => s + p.n, 0), la = a.res.items.filter(x => x.role === (kind === 'edge' ? 'dock_link' : 'dock_link')), lb = b.res.items.filter(x => x.role === 'dock_link'), linkA = la.map(x => ({ x, w: a.T.p([x.x, x.y, x.z]) })), linkB = lb.map(x => ({ x, w: b.T.p([x.x, x.y, x.z]) })), lp = linkA.flatMap(u => linkB.map(v => ({ u, v, dist: Math.hypot(u.w[0] - v.w[0], u.w[1] - v.w[1], u.w[2] - v.w[2]) }))).sort((x, y) => x.dist - y.dist)[0];
    const lk = lp && lp.dist < 15 ? lp.u.x.p : null, lkind = lk ? lk.n.kind : null, tol = lk && /pogo/.test(lkind || '') ? 0.5 : null;
    const halls = [[a, b], [b, a]].map(([s, o]) => { const hs = s.res.items.filter(x => x.role === 'dock_hall'), cloud = magsWorld(o.res, o.T, ['dock_mag', 'dock_back']).flatMap(m => dipoleCloud({ c: m.c, dims: m.dims, ax: m.ax, J: m.J, sign: m.sign })), best = hs.map(h => { const p = s.T.p([h.x, h.y, h.z + h.sz / 2]), own = s.res.items.filter(x => x.cat === 'magnet'), bOwn = Math.hypot(...fieldAt(magsWorld(s.res, s.T, ['dock_mag', 'dock_back']).flatMap(m => dipoleCloud({ c: m.c, dims: m.dims, ax: m.ax, J: m.J, sign: m.sign })), p)) * 1e6, bAll = Math.hypot(...fieldAt(cloud, p)) * 1e6; return { uid: h.uid, neighbour: bAll, own: bOwn, op: fin(h.p.n.bop) ? h.p.n.bop * 1000 : null }; }).sort((x, y) => y.neighbour - x.neighbour)[0]; return best || null; });
    contacts.push({ i, j, kind, pairs, net: r2(net), attract: pairs.filter(p => p.attract).length, repel: pairs.filter(p => !p.attract).length, link: lk ? { mpn: lk.mpn, kind: lkind, dist: r2(lp.dist), power: /pogo/.test(lkind || ''), rate: lk.n.rate } : null, tol, halls });
  }
  const shown = tiles.filter(t => t.face === 'up' && (t.level === 0 || !tiles.some(o => o !== t && o.level > t.level && ovl(o.box, [t.box[0], t.box[1], t.box[5] - 0.1, t.box[3], t.box[4], t.box[5] + 0.1], -1)))), act = shown.map(t => { const dsp = t.res.items.find(x => x.role === 'display'); if (!dsp) return null; const aw = dsp.p.n.aw || dsp.sx - 2, ah = dsp.p.n.ah || dsp.sy - 4, c = t.T.p([dsp.x, dsp.y, 0]), rot = t.rot % 180 ? [ah, aw] : [aw, ah]; return { i: t.i, x0: c[0] - rot[0] / 2, y0: c[1] - rot[1] / 2, x1: c[0] + rot[0] / 2, y1: c[1] + rot[1] / 2, area: aw * ah, res: dsp.p.n.res, ppi: dsp.p.n.ppi }; }).filter(Boolean);
  const ub = act.length ? [Math.min(...act.map(a => a.x0)), Math.min(...act.map(a => a.y0)), Math.max(...act.map(a => a.x1)), Math.max(...act.map(a => a.y1))] : null, seams = [];
  for (let i = 0; i < act.length; i++) for (let j = i + 1; j < act.length; j++) { const a = act[i], b = act[j], gx = Math.max(a.x0, b.x0) - Math.min(a.x1, b.x1), gy = Math.max(a.y0, b.y0) - Math.min(a.y1, b.y1); (gx > 0 && gy < 0) && seams.push(r2(gx)); (gy > 0 && gx < 0) && seams.push(r2(gy)); }
  const screen = { tiles: act.length, area: r2(act.reduce((s, a) => s + a.area, 0)), box: ub && [r2(ub[2] - ub[0]), r2(ub[3] - ub[1])], aspect: ub ? r2(Math.max(ub[2] - ub[0], ub[3] - ub[1]) / Math.max(1, Math.min(ub[2] - ub[0], ub[3] - ub[1]))) : null, diag: ub ? r2(Math.hypot(ub[2] - ub[0], ub[3] - ub[1]) / 25.4) : null, seams };
  const occl = [];
  tiles.forEach(t => t.res.items.filter(x => x.mount === 'back').forEach(cm => { const wb = worldBox(t.T, cm.box), blocked = tiles.some(o => o !== t && ovl(o.box, [wb[0], wb[1], wb[2] - 1.5, wb[3], wb[4], wb[5] + 1.5], -0.2) && !ovl(o.box, t.box, -0.2)); blocked && occl.push({ tile: t.i, uid: cm.uid, name: cm.name }); }));
  const rearOut = tiles.map(t => ({ t, cams: t.res.items.filter(x => x.role === 'cam_main' || x.role === 'cam_ultra') })), viewfinder = tiles.find(t => t.face === 'down' && t.level === -1 && t.res.items.some(x => x.role === 'display')), selfie = !!viewfinder && rearOut.some(x => x.t.face === 'up' && x.cams.length && x.cams.every(c => !occl.some(o => o.tile === x.t.i && o.uid === c.uid)));
  const fc = rA.items.find(x => x.role === 'cam_front'), fcSave = fc ? { cost: (fc.p.price && fc.p.price.q1 != null ? (rA.cost.rows.find(r => r.role === 'cam_front') || {}).usd : null), mass: fc.p.n.mass, z: fc.sz, mpn: fc.p.mpn } : null;
  const stereo = (() => { const cams = tiles.filter(t => t.face === 'up').flatMap(t => t.res.items.filter(x => x.role === 'cam_main').map(c => ({ t, c, w: t.T.p([c.x, c.y, 0]) }))).filter(x => !occl.some(o => o.tile === x.t.i && o.uid === x.c.uid)); if (cams.length < 2) return null; const a = cams[0], b = cams[1], B = Math.hypot(a.w[0] - b.w[0], a.w[1] - b.w[1]) / 1000, spec = a.c.p.specs || {}, mp = a.c.p.n.mp || 12, Wpx = Math.sqrt(mp * 1e6 * 4 / 3), dfov = fin(Number(spec.fov_deg)) ? Number(spec.fov_deg) : 80, hfov = 2 * Math.atan(Math.tan(dfov * Math.PI / 360) * 0.8), fpx = Wpx / 2 / Math.tan(hfov / 2), dd = 0.25, apart = sy.config === 'apart', Bm = apart ? sy.apartMm / 1000 : B, err = Z => Z * Z * dd / (fpx * Bm), docked = contacts.some(c => c.link && c.link.power), syncUs = docked ? 1 : 100; return { baselineMm: r2(Bm * 1000), fpx: Math.round(fpx), hfov: r2(hfov * 180 / Math.PI), dd, errAt: [0.5, 1, 3, 10].map(Z => ({ Z, mm: r2(err(Z) * 1000), pct: r2(err(Z) / Z * 100) })), syncUs, syncNote: docked ? 'Hardware trigger over a docked contact (assumed ≈1 µs; most phone sensors expose FSIN/XVS trigger pins).' : apart ? 'Apart: timestamp sync over UWB/Wi-Fi (assumed ≈100 µs); baseline from UWB ranging (FiRa ≈ ±10 cm), so absolute scale error ≈ ' + r2(0.1 / Bm * 100) + '%.' : 'Contactless dock: timestamp sync over the link (assumed ≈100 µs).', blurMm: r2(syncUs * 1e-6 * 1000 * 1), rolling: 'Rolling-shutter readout skew (typically 10–30 ms for 12–50 MP phone sensors) dominates sync error for moving scenes; a global-shutter sensor with a trigger pin removes it.', cams: cams.slice(0, 2).map(x => x.c.p.mpn), trigger: cams.slice(0, 2).map(x => { const pm = (db().pinmaps || {})[x.c.p.id], pin = pm && (pm.pins || []).find(q => /FSIN|XVS|VSYNC|FSYNC|TRIG/i.test(q[1])); return { mpn: x.c.p.mpn, pin: pin ? pin[1] : null, global: /global/i.test(String((x.c.p.specs || {}).shutter || x.c.p.name)), known: !!pm }; }) }; })();
  const wh = { A: rA.power.wh, B: (rB || rA).power.wh }, pOn = { A: rA.power.pOn, B: (rB || rA).power.pOn }, idle = { A: rA.power.pIdle, B: (rB || rA).power.pIdle }, rowsB = (rB || rA).power.rows, dispB = (rowsB.find(r => r.id === 'display') || { w: 0.3 }).w, linkW = contacts.reduce((s, c) => s + (c.link ? (c.link.kind === 'mmwave_60ghz' ? 0.13 : 0.02) : 0), 0), eta = contacts.some(c => c.link && c.link.power) ? 0.85 : 0, us = K.usable;
  const modes = { aloneA: wh.A * us / pOn.A, aloneB: wh.B * us / pOn.B, carry: (wh.A + wh.B * eta) * us / (pOn.A + idle.B), span: (wh.A + wh.B) * us / (pOn.A + dispB + idle.B * 2 + linkW), standbyDays: (wh.A + wh.B) * us / (idle.A + idle.B) / 24, standbyDaysOneAwake: (wh.A + wh.B * eta) * us / (idle.A + idle.B * 0.3) / 24 };
  const cost = rA.cost.unit + (rB || rA).cost.unit * (tiles.length - 1), mass = rA.mass + (rB || rA).mass * (tiles.length - 1);
  const dup = (rB || rA).cost.rows.filter(r => ['som', 'soc', 'soc_pmic', 'lpddr', 'ufs', 'modem', 'wifi', 'gnss', 'ntn', 'cam_main', 'cam_ultra', 'cam_front', 'charger', 'fuel_gauge', 'usb_pd', 'esim'].includes(r.role)).reduce((s, r) => s + (r.ext || 0), 0);
  const shell = res => { const g = res.g, ra = (w, l, r) => w * l - (4 - Math.PI) * r * r; return (ra(g.w, g.l, g.r) * g.t - ra(g.iw, g.il, g.ir) * (g.t - g.floor)) / 1000 + (g.w - 0.8) * (g.l - 0.8) * g.glassT / 1000; };
  const shellCm3 = shell(rA) + shell(rB || rA) * (tiles.length - 1);
  return { arch: sy.arch, config: sy.config, tiles: tiles.map(t => ({ i: t.i, type: t.type, gx: t.gx, gy: t.gy, rot: t.rot, face: t.face, level: t.level, m: t.T.m, box: t.box.map(r2) })), contacts, clash, screen, occl, selfie, fcSave, stereo, modes, cost, mass, dupCost: dup, shellCm3: r2(shellCm3), thickCarry: r2(rA.g.t + (rB || rA).g.t), pieces: tiles.length };
}
