const fs=require('fs'),path=require('path');
const src=fs.readFileSync(path.join(__dirname,'..','learn-app.js'),'utf8');
function slice(startMark,endMark){const s=src.indexOf(startMark);if(s<0)throw new Error('missing '+startMark);const e=src.indexOf(endMark,s);if(e<0)throw new Error('missing '+endMark);return src.slice(s,e);}
let pass=0,fail=0;
function assert(name,cond){cond?(pass++,console.log('PASS',name)):(fail++,console.error('FAIL',name));}
const chunkSrc=slice('function _chunkSpans(text)','\n  let _kkBlobCache');
const _chunkSpans=new Function('return ('+chunkSrc+')')();
const page='The little dog ran fast. Then he saw a big red ball in the yard and wagged his tail with joy. He barked twice. The end came soon after that day.';
const ch=_chunkSpans(page);
assert('first chunk is first sentence only',ch[0].t.trim()==='The little dog ran fast.');
assert('offsets contiguous',ch.every((c,i)=>i===0?c.s===0:c.s===ch[i-1].e)&&ch[ch.length-1].e===page.length);
assert('later chunks still merge',ch.length<=3&&ch.length>=2);
assert('reconstruction exact',ch.map(c=>c.t).join('')===page);
assert('no-punct text single chunk',_chunkSpans('hello there friend').length===1);
const batchSrc=slice('function _ttsBatch(arr)','\n  async function _hdSay');
const _ttsBatch=new Function('_chunkSpans','return ('+batchSrc+')')(_chunkSpans);
const phon=['This is the letter B.','Its sound is buh.','B says buh!','Buh, buh, ball.'];
const parts=_ttsBatch(phon);
assert('phonics items not joined',parts.length>=phon.length&&parts[0].trim()==='This is the letter B.');
const synthSrc=slice('let _synthCache=new Map();','\n  async function _synthRaw');
let rawCalls=0,rawFail=false;
const _synthRaw=t=>{rawCalls++;return rawFail?Promise.reject(new Error('boom')):Promise.resolve('wav:'+t);};
const _synthWav=new Function('_synthRaw',synthSrc+';return _synthWav;')(_synthRaw);
(async()=>{
  const [a,b]=await Promise.all([_synthWav('hi',0.95),_synthWav('hi',0.95)]);
  assert('concurrent calls dedupe to one synth',rawCalls===1&&a===b&&a==='wav:hi');
  await _synthWav('hi',0.95);
  assert('cache hit no re-synth',rawCalls===1);
  await _synthWav('hi',1);
  assert('speed keys separately',rawCalls===2);
  rawFail=true;
  await _synthWav('bad',1).catch(()=>{});
  await new Promise(r=>setTimeout(r,0));
  rawFail=false;
  await _synthWav('bad',1);
  assert('rejection not cached',rawCalls===4);
  const fetches=[];
  let fetchOk=true;
  const MAN={'hello|1':'v0001.ogg','world|0.95':'v0002.ogg'};
  const fakeFetch=u=>{fetches.push(u);return Promise.resolve(u.endsWith('manifest.json')?{ok:true,json:()=>Promise.resolve(MAN)}:{ok:fetchOk,blob:()=>Promise.resolve('OGG:'+u)});};
  const env2=new Function('fetch','_synthRaw',synthSrc+';return {synth:_synthWav,voiceHas:_voiceHas};')(fakeFetch,_synthRaw);
  await new Promise(r=>setTimeout(r,0));
  const preRaw=rawCalls;
  const m1=await env2.synth('hello',1);
  assert('manifest hit plays static file, no synth',m1==='OGG:assets/voice/v0001.ogg'&&rawCalls===preRaw);
  await env2.synth('offmanifest',1);
  assert('manifest miss falls back to synth',rawCalls===preRaw+1);
  fetchOk=false;
  await env2.synth('world',0.95);
  assert('static fetch failure falls back to synth',rawCalls===preRaw+2);
  assert('voiceHas true when all covered',env2.voiceHas(['hello'],1)===true);
  assert('voiceHas false on any gap',env2.voiceHas(['hello','nope'],1)===false);
  const wordSrc=slice('function speakWord(text, near){','\n  function initStorybook');
  const calls=[];
  function FakeAudio(){this.paused=false;this.pause=()=>{this.paused=true;calls.push('hd-pause');};this.play=()=>{this.paused=false;calls.push('hd-play');return Promise.resolve();};}
  const mk=(hdAudio,storyState,manual)=>{
    let live=null;
    const g={_hdAudio:hdAudio,_storyState:storyState,playCurrentPage:()=>calls.push('playCurrentPage'),setTimeout:f=>f(),window:{speechSynthesis:{}},speechSynthesis:{cancel:()=>{calls.push('ss-cancel');const u=live;live=null;u&&u.onend&&u.onend();},speak:u=>{calls.push('speak:'+u.text);manual?live=u:u.onend&&u.onend();},getVoices:()=>[]}};
    g.SpeechSynthesisUtterance=function(t){this.text=t;};
    const fn=new Function(...Object.keys(g),wordSrc+';return speakWord;')(...Object.values(g));
    return {tap:fn,end:()=>{const u=live;live=null;u&&u.onend&&u.onend();}};
  };
  calls.length=0;
  const hd=new FakeAudio();
  mk(hd,{autoplay:true,utterance:null,book:{}}).tap('ball',null);
  assert('hd path pauses page audio',calls[0]==='hd-pause');
  assert('hd path speaks word then resumes same audio',calls.includes('speak:ball')&&calls[calls.length-1]==='hd-play');
  assert('hd path never restarts page',!calls.includes('playCurrentPage'));
  calls.length=0;
  mk(null,{autoplay:true,utterance:{onend:null},book:{}}).tap('cat',null);
  assert('web path cancels and restarts page',calls.includes('ss-cancel')&&calls.includes('playCurrentPage'));
  calls.length=0;
  const pausedHd=new FakeAudio();pausedHd.paused=true;
  mk(pausedHd,{autoplay:false,utterance:null,book:{}}).tap('dog',null);
  assert('user-paused audio stays paused after word',!calls.includes('hd-play')&&calls.includes('speak:dog'));
  calls.length=0;
  const hd2=new FakeAudio();
  const st2={autoplay:true,utterance:null,book:{}};
  const sim=mk(hd2,st2,true);
  sim.tap('sun',null);
  assert('double-tap: word1 speaking, page paused, no resume yet',calls.join()==='hd-pause,speak:sun');
  sim.tap('moon',null);
  assert('double-tap: stale word1 end neither resumes nor restarts',!calls.includes('hd-play')&&!calls.includes('playCurrentPage'));
  sim.end();
  assert('double-tap: word2 end resumes page audio exactly once',calls.filter(c=>c==='hd-play').length===1&&!calls.includes('playCurrentPage'));
  assert('double-tap: autoplay survives for page flip',st2.autoplay===true);
  console.log(JSON.stringify({pass,fail}));
  if(fail)process.exit(1);
})();
