export const cents = n => n === null || n === '' || !Number.isFinite(+n) ? 0 : Math.round(+(+n * 100).toFixed(6))
export const toNum = (v, d = NaN) => { const n = typeof v === 'number' ? v : parseFloat(String(v ?? '').replace(/[$,\s]/g, '')); return Number.isFinite(n) ? n : d }
export const clampNum = (v, min, max, d) => { const n = toNum(v, d); return Number.isFinite(n) ? Math.min(max, Math.max(min, n)) : d }
export const parsePrice = v => { const n = toNum(v); return Number.isFinite(n) && n >= 0 && n < 1e7 ? cents(n) / 100 : null }
export const money = (x, dp = 2) => x == null || x === '' || !Number.isFinite(+x) ? '—' : (+x < 0 ? '-$' : '$') + Math.abs(+x).toLocaleString('en-US', { minimumFractionDigits: dp, maximumFractionDigits: dp })
export const lineTotal = (p, q) => p == null || p === '' || !Number.isFinite(+p) || !Number.isFinite(+q) ? null : cents(+p * +q) / 100
export const totals = (items, price) => { const t = { hd: 0, lowes: 0, miss: { hd: 0, lowes: 0 } }; for (const it of items) for (const s of ['hd', 'lowes']) { const l = lineTotal(price(it.id, s), it.qty); l == null ? t.miss[s]++ : t[s] += cents(l) } t.hd /= 100; t.lowes /= 100; t.best = t.miss.hd !== t.miss.lowes ? (t.miss.hd < t.miss.lowes ? 'hd' : 'lowes') : t.hd <= t.lowes ? 'hd' : 'lowes'; return t }
export const missNote = t => t.miss.hd || t.miss.lowes ? `<div class="warn" style="margin:10px 0">⚠ ${[['hd', 'Home Depot'], ['lowes', "Lowe's"]].filter(([k]) => t.miss[k]).map(([k, n]) => `${t.miss[k]} item${t.miss[k] > 1 ? 's have' : ' has'} no ${n} price`).join(' · ')}. Totals leave those lines out, so type a price in the empty cells before you quote this job.</div>` : ''
export const csvCell = v => { const s = v == null ? '' : String(v), g = typeof v === 'string' && /^[=+\-@\t\r]/.test(s) ? "'" + s : s; return /[",\n\r]/.test(g) ? `"${g.replace(/"/g, '""')}"` : g }
export const csv = rows => rows.map(r => r.map(csvCell).join(',')).join('\r\n')
export const toCSV = rows => '\ufeff' + csv(rows)
export const materialsCSV = (items, price, alts = []) => { const t = totals(items, price), f = x => x == null ? '' : (+x).toFixed(2), line = (it, note = '') => [it.desc + note, it.qty, f(price(it.id, 'hd')), f(lineTotal(price(it.id, 'hd'), it.qty)), f(price(it.id, 'lowes')), f(lineTotal(price(it.id, 'lowes'), it.qty))]; return toCSV([['Item', 'Qty', 'HD each', 'HD total', 'Lowes each', 'Lowes total'], ...items.map(it => line(it)), ['TOTAL', '', '', t.hd.toFixed(2), '', t.lowes.toFixed(2)], ...alts.map(it => line(it, ' (alternative, not in total)'))]) }
export const readJSON = (k, d) => { try { const v = JSON.parse(localStorage.getItem(k)); return v ?? d } catch { return d } }
export const writeJSON = (k, v) => { try { localStorage.setItem(k, JSON.stringify(v)); return true } catch { return false } }
export const isObj = v => !!v && typeof v === 'object' && !Array.isArray(v)
export const DECK_LIM = { length: [4, 40, 12], depth: [4, 20, 8], height: [8, 96, 16] }
export const sanitizeDeck = (c, def) => { const m = isObj(c) ? c : {}, o = { ...structuredClone(def), ...m }, poly = o.mode === 'poly' && Array.isArray(o.polygon) && o.polygon.length >= 3; for (const [k, [a, b, d]] of Object.entries(DECK_LIM)) o[k] = clampNum(o[k], a, poly && k !== 'height' ? 1e4 : b, d); o.spacing = [12, 16, 24].includes(+o.spacing) ? +o.spacing : 16; o.joist = ['2x6', '2x8', '2x10'].includes(o.joist) ? o.joist : '2x8'; o.attach = o.attach === 'free' ? 'free' : 'ledger'; o.foundation = ['footing', 'pier', 'deckblock'].includes(o.foundation) ? o.foundation : 'footing'; o.decking = o.decking === 'comp' ? 'comp' : 'pt'; o.mode = o.mode === 'poly' && Array.isArray(o.polygon) && o.polygon.length >= 3 && o.polygon.every(p => Array.isArray(p) && p.length >= 2 && p.every(Number.isFinite)) ? 'poly' : 'rect'; o.polygon = o.mode === 'poly' ? o.polygon : null; o.house_edge = Number.isInteger(+o.house_edge) ? +o.house_edge : 0; o.stairs = (Array.isArray(o.stairs) ? o.stairs : []).filter(isObj).map(s => ({ side: ['front', 'left', 'right'].includes(s.side) ? s.side : 'front', width: clampNum(s.width, 36, 96, 48), offset: clampNum(s.offset, -1, 480, -1) })); o.railing = { ...def.railing, ...(isObj(o.railing) ? o.railing : {}) }; o.railing.style = o.railing.style === 'alum' ? 'alum' : 'wood'; const dr = { ...def.door, ...(isObj(o.door) ? o.door : {}) }; o.door = { ...dr, pos: clampNum(dr.pos, -1, 40, -1), width: clampNum(dr.width, 30, 96, 60), rise: clampNum(dr.rise, 0, 24, 7), panels: Math.round(clampNum(dr.panels, 1, 4, 2)), count: Math.round(clampNum(dr.count, 1, 3, 1)), gap: clampNum(dr.gap, 0, 60, 0) }; return o }
export const DECK_FIX = [[/\s*\(below the Troy\/Cohoes frost line\)/g, ' (this plan assumes a 48 in frost line; dig to your local frost depth if it is deeper)'], [/Troy\/Cohoes NY frost depth ~48 in/g, 'Frost depth is assumed at ~48 in in this plan'], [/Troy generally wants one for attached decks/g, 'most towns want one for attached decks']]
export const localize = s => DECK_FIX.reduce((a, [r, t]) => a.replace(r, t), String(s))
export const fixPatio = out => !out?.bom || !out.calc ? out : { ...out, bom: out.bom.map(it => it.id === 'readymix' ? { ...it, qty: +(+out.calc.order_yd3).toFixed(2), desc: it.desc.replace(/\s*\([\d.]+ yd³ ordered\)/, '') + ' (yd³ ordered)' } : it.id === 'bags80' ? { ...it, alt: true, desc: '80 lb concrete mix, bag alternative to ready-mix (not in total)' } : it) }
export const POOL_ABOVE_DROP = new Set(['maindrain', 'coping'])
export const fixPool = (out, kind) => { if (!out?.bom) return out; const wet = +((out.bom.find(i => i.id === 'liner')?.desc || '').match(/~?([\d,.]+)\s*ft2/)?.[1]?.replace(/,/g, '') || 0) || (+out.bom.find(i => i.id === 'liner')?.qty || 0) * 100; return { ...out, calc: out.calc ? { ...out.calc, gallons: Math.round(+out.calc.gallons || 0) } : out.calc, bom: out.bom.filter(it => !(kind === 'above' && POOL_ABOVE_DROP.has(it.id))).map(it => it.id === 'rebar' && wet > 0 ? { ...it, qty: Math.ceil(wet * 2 / 20 * 1.1), desc: `#3 rebar 20 ft, shell steel at 12" grid each way + 10% lap (~${Math.round(wet)} ft²)` } : it) } }
export const DIRECT_SOW = { carrot: 400, lettuce: 250, bean: 60, onion: 80, garlic: 8 }
export const halfUp = x => Math.ceil(+(+x * 2).toFixed(6)) / 2
export const fixGarden = out => { if (!out?.bom || !out.calc) return out; const vol = +out.calc.soil_yd3 || 0, soil = halfUp(vol * 2 / 3 * 1.1), compost = halfUp(vol / 3 * 1.1), beds = Array.isArray(out.beds) ? out.beds : [], seedlings = beds.filter(b => !DIRECT_SOW[b.plant]).reduce((a, b) => a + (+b.plants || 0), 0), seed = beds.filter(b => DIRECT_SOW[b.plant]).reduce((a, b) => a + Math.ceil((+b.plants || 0) / DIRECT_SOW[b.plant]), 0), bom = out.bom.flatMap(it => it.id === 'soil' ? (soil ? [{ ...it, qty: soil, desc: 'Garden soil / topsoil, 2/3 of the fill + 10% settling (cu yd)' }] : []) : it.id === 'compost' ? (compost ? [{ ...it, qty: compost, desc: 'Compost, 1/3 of the fill + 10% settling (cu yd)' }] : []) : it.id === 'plants' && beds.length ? [...(seedlings ? [{ ...it, qty: seedlings, desc: 'Seedlings / transplants (per plant)' }] : []), ...(seed ? [{ id: 'seed', qty: seed, desc: 'Seed packets, onion sets or seed-garlic bulbs (direct-sown beds)' }] : [])] : [it]); return { ...out, bom, calc: { ...out.calc, soil_buy: soil, compost_buy: compost } } }
export const loadPrices = k => { const v = readJSON(k, {}); return isObj(v) ? Object.fromEntries(Object.entries(v).filter(([, x]) => parsePrice(x) != null).map(([n, x]) => [n, parsePrice(x)])) : {} }
export const esc = s => String(s ?? '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]))
export const storeLink = (store, q) => q ? `<a href="https://www.${store === 'hd' ? 'homedepot.com/s/' : 'lowes.com/search?searchTerm='}${encodeURIComponent(q)}" target="_blank" rel="noopener" aria-label="Search ${store === 'hd' ? 'Home Depot' : "Lowe's"}">↗</a>` : ''
export const priceRow = (it, price, cat = {}) => { const cell = s => { const p = price(it.id, s); return `<td><input inputmode="decimal" placeholder="price" aria-label="${s === 'hd' ? 'Home Depot' : "Lowe's"} price each, ${esc(it.desc)}" data-id="${esc(it.id)}" data-store="${s}" value="${p ?? ''}"> ${storeLink(s, s === 'hd' ? cat.hdq : cat.lq)}</td><td>${money(lineTotal(p, it.qty))}</td>` }; return `<tr${it.alt ? ' style="opacity:.72"' : ''}><td>${it.desc}</td><td>${it.qty}</td>${cell('hd')}${cell('lowes')}</tr>` }
export const totRow = (label, t, style = '') => `<tr><td class="tot" style="${style}">${label}</td><td></td><td></td><td class="tot ${style ? '' : t.best === 'hd' ? 'best' : ''}" style="${style}">${money(t.hd)}</td><td></td><td class="tot ${style ? '' : t.best === 'lowes' ? 'best' : ''}" style="${style}">${money(t.lowes)}</td></tr>`
export const bindPrices = (root, edits, save, rerender) => root.querySelectorAll('input[data-id]').forEach(i => i.onchange = () => { const v = parsePrice(i.value), k = `${i.dataset.id}.${i.dataset.store || i.dataset.st}`; v == null ? delete edits[k] : edits[k] = v; save(); rerender() })
export const priceBom = (bom, price) => { let th = 0, tl = 0; const rows = (bom || []).map(it => { const q = Math.max(0, +it.qty || 0), ph = price(it.id, 'hd'), pl = price(it.id, 'lowes'), ch = ph == null ? null : cents(ph * q), cl = pl == null ? null : cents(pl * q); th += ch || 0; tl += cl || 0; return { it, q, ph, pl, lh: ch == null ? null : ch / 100, ll: cl == null ? null : cl / 100 } }); return { rows, th: th / 100, tl: tl / 100 } }
export const bomCsv = (bom, price) => { const { rows, th, tl } = priceBom(bom, price), f = v => v == null ? '' : (cents(v) / 100).toFixed(2); return csv([['Item', 'Qty', 'HD each', 'HD total', 'Lowes each', 'Lowes total'], ...rows.map(r => [r.it.desc, r.q, f(r.ph), f(r.lh), f(r.pl), f(r.ll)]), ['TOTAL', '', '', f(th), '', f(tl)]]) }
export const fitNum = (raw, lim = {}, prev) => { const v = typeof raw === 'number' ? raw : String(raw ?? '').trim() === '' ? NaN : Number(raw), lo = lim.min === '' || lim.min == null ? -Infinity : +lim.min, hi = lim.max === '' || lim.max == null ? Infinity : +lim.max, st = +lim.step || 0, r = Number.isFinite(v) ? v : +prev; return Number.isFinite(r) ? Math.min(hi, Math.max(lo, st >= 1 ? Math.round(r) : r)) : Number.isFinite(lo) ? lo : 0 }
export const validPoly = p => Array.isArray(p) && p.length >= 3 && p.every(q => Array.isArray(q) && q.length >= 2 && Number.isFinite(+q[0]) && Number.isFinite(+q[1]) && q[0] !== null && q[1] !== null)
export const sanitizeCfg = (raw, def, enums = {}) => { const o = { ...def, ...(raw && typeof raw === 'object' && !Array.isArray(raw) ? raw : {}) }; Object.keys(def).forEach(k => { const d = def[k], v = o[k]; typeof d === 'number' ? o[k] = v !== null && v !== '' && typeof v !== 'boolean' && Number.isFinite(+v) ? +v : d : typeof d === 'boolean' ? o[k] = typeof v === 'boolean' ? v : d : enums[k] && !enums[k].includes(String(v)) && (o[k] = d) }); 'polygon' in def && (o.polygon = validPoly(o.polygon) ? o.polygon.map(q => [+q[0], +q[1]]) : null, o.mode === 'poly' && !o.polygon && (o.mode = 'rect'), 'house_edge' in def && (o.house_edge = o.mode === 'poly' ? (o.house_edge >= 0 && o.house_edge < o.polygon.length ? Math.round(o.house_edge) : -1) : o.house_edge >= 0 ? 0 : -1)); return o }
export const coreError = e => /invalid (type|value)|expected |missing field|EOF while|trailing/i.test(String(e)) ? 'One of the inputs is empty or out of range. Check the numbers on the left and try again.' : String(e || 'Could not build this estimate.')
export const hvacSize = a => { const tons = Math.max(1, Math.round((+a || 0) / 250) / 2); return { tons, cfm: tons * 400 } }
export const studSpec = h => h <= 8 ? { len: '92-5/8"', f: 1 } : h <= 9 ? { len: '104-5/8"', f: 104.625 / 92.625 } : h <= 10 ? { len: '116-5/8"', f: 116.625 / 92.625 } : { len: h <= 11.5 ? '12 ft' : '14 ft', f: (h <= 11.5 ? 144 : 168) / 92.625 }
export const studBom = (bom, h) => { const s = studSpec(+h || 8); return s.f === 1 ? bom : bom.map(it => /^stud6?$/.test(it.id) ? { ...it, desc: it.desc.replace(/\(precut 92-5\/8\)/, s.len.endsWith('ft') ? `(${s.len}, cut to length)` : `(precut ${s.len})`) } : it) }
export const sanitizeRooms = (rooms, kinds, def) => { const r = (Array.isArray(rooms) ? rooms : def).filter(x => x && typeof x === 'object').map((x, i) => ({ ...x, name: typeof x.name === 'string' ? x.name.slice(0, 40) : `Room ${i + 1}`, kind: kinds.includes(x.kind) ? x.kind : 'other', w: fitNum(x.w, { min: 3, max: 80 }, 10), d: fitNum(x.d, { min: 3, max: 80 }, 10) })); return r.length || !Array.isArray(rooms) ? r : [] }
export const escXml = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c])
export const unXml = s => String(s ?? '').replace(/&(amp|lt|gt|quot|#39);/g, (m, k) => ({ amp: '&', lt: '<', gt: '>', quot: '"', '#39': "'" })[k])
export const rectHip = (out, w, d) => { const run = Math.min(+w, +d) / 2, hip = 4 * run * Math.sqrt(2 + (+out.calc.pitch / 12) ** 2), lf = (+out.calc.ridge_ft || 0) + hip, qty = Math.ceil(lf / 33); return { ...out, calc: { ...out.calc, hip_ft: hip }, bom: out.bom.map(b => b.id === 'ridgecap' ? { ...b, qty, desc: b.desc.replace(/\(\d+ lf\)/, `(${Math.round(lf)} lf)`) } : b), warnings: (out.warnings || []).map(s => s.replace(/\d+ ridge\/hip cap bundles/, `${qty} ridge/hip cap bundles`)) } }
