var BP=(function(){
var W=750,EF='"Apple Color Emoji","Segoe UI Emoji","Noto Color Emoji",sans-serif',TF='Archivo,"Trebuchet MS",Arial,sans-serif',CUT='10 7';
var TH=[
{name:'Dinosaur Day',m:'🦕',bg:'#eaf6e3',ac:'#3f8a2e',sky:'#cdeefd',gr:'#b9dc8e',deco:['🌴','🌋','🌿','☁️','🌳','🪨'],maze:[['🦕','🥚','dinosaur','egg'],['🦖','🦴','T. rex','bone'],['🐢','🌴','turtle','palm tree']],items:[['🦕','DINO','green'],['🦖','REX','green'],['🥚','EGG'],['🌋','LAVA','red'],['🌴','PALM','green'],['🦴','BONE'],['🐊','CROC','green'],['🐢','TURTLE','green'],['🌿','LEAF','green'],['🪨','ROCK'],['🐉','DRAGON','green'],['🦎','LIZARD','green'],['🌳','TREE','green'],['☄️','COMET']]},
{name:'Ocean Day',m:'🐠',bg:'#e3f3fb',ac:'#1d78a8',sky:'#8fd3f4',gr:'#f3dfa2',deco:['🌊','☀️','🐚','⛵','☁️','🏝️'],maze:[['🐠','🐚','fish','shell'],['🐢','🏝️','turtle','island'],['🦀','🐚','crab','shell']],items:[['🐠','FISH','yellow'],['🐙','OCTOPUS'],['🦀','CRAB','red'],['🐢','TURTLE','green'],['🐬','DOLPHIN','blue'],['🐳','WHALE','blue'],['🦈','SHARK'],['🦑','SQUID'],['🐚','SHELL'],['🦞','LOBSTER','red'],['🦐','SHRIMP'],['🐡','PUFFER'],['⚓','ANCHOR'],['🦭','SEAL']]},
{name:'Farm Day',m:'🐄',bg:'#fdf3dc',ac:'#a95f1c',sky:'#cdeefd',gr:'#a8d672',deco:['🌻','🌾','☀️','🏡','☁️','🌳'],maze:[['🐄','🌾','cow','hay'],['🐖','🍎','pig','apple'],['🐓','🌽','hen','corn']],items:[['🐄','COW'],['🐖','PIG','pink'],['🐑','SHEEP'],['🐓','HEN'],['🐴','HORSE','brown'],['🐐','GOAT'],['🦆','DUCK'],['🐇','BUNNY'],['🚜','TRACTOR'],['🌽','CORN','yellow'],['🥚','EGG'],['🐶','DOG'],['🐈','CAT'],['🌻','FLOWER','yellow']]},
{name:'Fruit Day',m:'🍓',bg:'#fdebea',ac:'#c0392b',sky:'#fff3c4',gr:'#c9e59a',deco:['🧺','🌳','☀️','🍃','☁️'],maze:[['🐛','🍎','caterpillar','apple'],['🐒','🍌','monkey','banana'],['🐻','🍓','bear','berry']],items:[['🍎','APPLE','red'],['🍌','BANANA','yellow'],['🍇','GRAPES','purple'],['🍓','BERRY','red'],['🍊','ORANGE','orange'],['🍉','MELON'],['🍐','PEAR','green'],['🍒','CHERRY','red'],['🍍','PINEAPPLE'],['🥝','KIWI','green'],['🍑','PEACH','orange'],['🍋','LEMON','yellow'],['🥭','MANGO'],['🫐','BLUEBERRY','blue'],['🥥','COCONUT','brown']]},
{name:'Veggie Garden',m:'🥕',bg:'#eef7e2',ac:'#4f8a23',sky:'#dff3ff',gr:'#a47551',deco:['🌱','🧺','☀️','🌿','☁️'],maze:[['🐰','🥕','bunny','carrot'],['🐌','🥬','snail','lettuce'],['🐛','🥦','caterpillar','broccoli']],items:[['🥕','CARROT','orange'],['🥦','BROCCOLI','green'],['🌽','CORN','yellow'],['🍅','TOMATO','red'],['🥒','CUKE','green'],['🍆','EGGPLANT','purple'],['🫑','PEPPER','green'],['🥔','POTATO','brown'],['🧄','GARLIC'],['🥬','LETTUCE','green'],['🍄','MUSHROOM'],['🌶️','CHILI','red'],['🧅','ONION'],['🥜','PEANUT','brown']]},
{name:'Things That Go',m:'🚗',bg:'#e8eefc',ac:'#2f55c9',sky:'#d6ecff',gr:'#b8bec6',deco:['🚦','☁️','🌳','🏠','☀️'],maze:[['🚗','🏠','car','house'],['🚒','🔥','fire truck','fire'],['🚂','🚉','train','station']],items:[['🚗','CAR','red'],['🚌','BUS'],['🚒','TRUCK','red'],['🚓','POLICE'],['🚑','AMBULANCE'],['🚜','TRACTOR'],['🚂','TRAIN'],['✈️','PLANE'],['🚁','COPTER'],['🚀','ROCKET'],['🚲','BIKE'],['⛵','BOAT'],['🚚','VAN'],['🛴','SCOOTER']]},
{name:'Space Day',m:'🚀',bg:'#ece8fb',ac:'#5b3fc4',sky:'#cfc8f7',gr:'#8f92b3',deco:['⭐','✨','🌟','🪐','☄️'],maze:[['🚀','🌙','rocket','moon'],['👽','🛸','alien','spaceship'],['👩‍🚀','🚀','astronaut','rocket']],items:[['🚀','ROCKET'],['🌙','MOON','yellow'],['⭐','STAR','yellow'],['🪐','PLANET'],['☀️','SUN','yellow'],['🌍','EARTH','blue'],['👽','ALIEN','green'],['🛸','UFO'],['☄️','COMET'],['🔭','SCOPE'],['🌟','SHINE','yellow'],['👩‍🚀','ASTRONAUT'],['🛰️','SATELLITE'],['🌕','MOON','yellow']]},
{name:'Bug Day',m:'🐞',bg:'#f3f9e1',ac:'#5e8a12',sky:'#e3f6ff',gr:'#9fd67a',deco:['🌸','🌿','☀️','🌷','🍃'],maze:[['🐝','🌻','bee','flower'],['🐛','🍃','caterpillar','leaf'],['🐞','🌷','ladybug','tulip']],items:[['🐞','LADYBUG','red'],['🐝','BEE','yellow'],['🦋','BUTTERFLY'],['🐛','WORM','green'],['🐜','ANT'],['🕷️','SPIDER'],['🐌','SNAIL'],['🦗','CRICKET','green'],['🪲','BEETLE'],['🌸','FLOWER','pink'],['🌻','SUNFLOWER','yellow'],['🍃','LEAF','green'],['🕸️','WEB'],['🌷','TULIP','pink']]},
{name:'Pet Day',m:'🐶',bg:'#fdf0e6',ac:'#b8601a',sky:'#ffeede',gr:'#e8c9a0',deco:['🏠','🐾','🌳','☀️','🧸'],maze:[['🐶','🦴','dog','bone'],['🐱','🧶','cat','yarn'],['🐭','🧀','mouse','cheese'],['🐰','🥕','bunny','carrot']],items:[['🐶','DOG'],['🐱','CAT'],['🐰','BUNNY'],['🐹','HAMSTER'],['🐠','FISH','yellow'],['🐦','BIRD','blue'],['🐢','TURTLE','green'],['🐭','MOUSE'],['🦎','GECKO','green'],['🦴','BONE'],['🧶','YARN'],['🐾','PAWS'],['🐕','PUPPY','brown'],['🐈','KITTY']]},
{name:'Jungle Day',m:'🦁',bg:'#e6f4ea',ac:'#1e7a45',sky:'#d9f2d0',gr:'#7fbf6a',deco:['🌴','🌳','🌿','☀️','🌺'],maze:[['🐒','🍌','monkey','banana'],['🐘','💧','elephant','water'],['🦜','🌴','parrot','tree']],items:[['🦁','LION'],['🐘','ELEPHANT'],['🦒','GIRAFFE'],['🦓','ZEBRA'],['🐒','MONKEY','brown'],['🐯','TIGER','orange'],['🦛','HIPPO'],['🐊','CROC','green'],['🦜','PARROT'],['🐍','SNAKE','green'],['🦏','RHINO'],['🍌','BANANA','yellow'],['🦥','SLOTH','brown'],['🐆','LEOPARD']]},
{name:'Bird Day',m:'🐥',bg:'#e9f5fb',ac:'#2a7fa6',sky:'#d8f0ff',gr:'#b7e0a0',deco:['🌳','☁️','☀️','🌸','🌿'],maze:[['🐥','🥚','chick','egg'],['🐦','🌳','bird','tree'],['🦆','🌊','duck','pond']],items:[['🦜','PARROT'],['🦆','DUCK'],['🦉','OWL','brown'],['🐧','PENGUIN'],['🦩','FLAMINGO','pink'],['🐓','ROOSTER'],['🦅','EAGLE','brown'],['🕊️','DOVE'],['🐦','BIRD','blue'],['🦚','PEACOCK','green'],['🐥','CHICK','yellow'],['🥚','EGG'],['🦢','SWAN'],['🪶','FEATHER']]},
{name:'Bakery Day',m:'🧁',bg:'#fdeaf3',ac:'#b83b76',sky:'#fff0f6',gr:'#f5d0a9',deco:['🎈','🎉','🍭','☁️','🎀'],maze:[['🐻','🍯','bear','honey'],['🐭','🍪','mouse','cookie'],['🐜','🍰','ant','cake']],items:[['🧁','CUPCAKE','pink'],['🍪','COOKIE','brown'],['🍩','DONUT','pink'],['🍭','LOLLY'],['🍦','CONE'],['🍰','CAKE'],['🥐','CROISSANT','brown'],['🍞','BREAD','brown'],['🥞','PANCAKE'],['🍫','CHOCOLATE','brown'],['🧇','WAFFLE'],['🍯','HONEY'],['🍓','BERRY','red'],['🥛','MILK']]},
{name:'Fall Fun',m:'🍂',bg:'#fdf0e0',ac:'#b8501a',sky:'#ffe9c7',gr:'#d98c4a',deco:['🍂','🍁','🌳','☀️','☁️'],maze:[['🐿️','🌰','squirrel','acorn'],['🦔','🍎','hedgehog','apple'],['🦊','🍂','fox','leaves']],items:[['🍂','LEAF','orange'],['🍁','MAPLE','red'],['🎃','PUMPKIN','orange'],['🌰','ACORN','brown'],['🦔','HEDGEHOG','brown'],['🍄','MUSHROOM'],['🍎','APPLE','red'],['🦃','TURKEY'],['🌽','CORN','yellow'],['🐿️','SQUIRREL','brown'],['🦊','FOX','orange'],['🥧','PIE'],['🧣','SCARF'],['🦉','OWL','brown']]},
{name:'Snow Day',m:'⛄',bg:'#eef6fd',ac:'#3a6ea5',sky:'#dbeeff',gr:'#ffffff',deco:['❄️','🌲','☁️','🏔️','⛄'],maze:[['🐧','🐟','penguin','fish'],['🦌','🌲','deer','tree'],['⛄','🥕','snowman','carrot']],items:[['⛄','SNOWMAN'],['❄️','SNOW','blue'],['🧤','MITTEN'],['🧣','SCARF'],['🛷','SLED'],['🐧','PENGUIN'],['🦌','DEER','brown'],['🌲','TREE','green'],['☕','COCOA'],['🎿','SKI'],['🐻‍❄️','BEAR'],['🧊','ICE','blue'],['🏔️','MOUNTAIN'],['🦭','SEAL']]}];
var TOG=[['🐄','🥛'],['🐓','🥚'],['🐝','🍯'],['🐑','🧶'],['🌧️','☂️'],['🐶','🦴'],['🐰','🥕'],['🐒','🍌'],['🐭','🧀'],['🔑','🔒'],['🦶','🧦'],['🪥','🦷'],['✋','🧤'],['🚗','⛽'],['⚽','🥅'],['🎂','🕯️'],['😎','☀️'],['🛏️','😴'],['🐿️','🌰'],['🔥','🚒'],['🎨','🖌️'],['🥣','🥄'],['✉️','📮'],['🌱','💧'],['🐟','🎣'],['🌙','⭐'],['👑','🤴'],['🍪','🥛']];
var COL={red:['#e53935',['🍎','🍓','🍒','🚒','🐞','🍅','❤️','🌹']],orange:['#fb8c00',['🍊','🥕','🎃','🦊','🏀','🧡','🍑']],yellow:['#f9c80e',['🍌','⭐','🌻','🐥','🍋','🌽','🧀','💛']],green:['#43a047',['🥦','🐸','🥒','🌲','🍀','🍏','🦖','💚']],blue:['#1e88e5',['🫐','🐳','💧','🧢','💙','🐋','👖','🧊']],purple:['#8e24aa',['🍇','🍆','🔮','💜','🟣','👾']],pink:['#ec407a',['🌸','🐷','🦩','🍩','💗','🎀','🌷']],brown:['#8d6e63',['🐻','🍪','🌰','🥔','🐴','🍫','🪵','🥐']]};
var G={A:'M0 100 L30 0 L60 100 M12 60 L48 60',B:'M0 0 L0 100 M0 0 L34 0 C58 0 58 48 34 48 L0 48 M34 48 C62 48 62 100 34 100 L0 100',C:'M58 20 C50 -5 0 -5 0 50 C0 105 50 105 58 80',D:'M0 0 L0 100 M0 0 L24 0 C66 0 66 100 24 100 L0 100',E:'M58 0 L0 0 L0 100 L58 100 M0 50 L44 50',F:'M58 0 L0 0 L0 100 M0 50 L44 50',G:'M58 20 C50 -5 0 -5 0 50 C0 105 58 105 58 60 L32 60',H:'M0 0 L0 100 M60 0 L60 100 M0 50 L60 50',I:'M30 0 L30 100 M10 0 L50 0 M10 100 L50 100',J:'M16 0 L58 0 M44 0 L44 72 C44 104 2 104 0 78',K:'M0 0 L0 100 M58 0 L0 58 M18 42 L60 100',L:'M0 0 L0 100 L56 100',M:'M0 100 L0 0 L30 62 L60 0 L60 100',N:'M0 100 L0 0 L60 100 L60 0',O:'M30 0 C-10 0 -10 100 30 100 C70 100 70 0 30 0',P:'M0 100 L0 0 L34 0 C62 0 62 52 34 52 L0 52',Q:'M30 0 C-10 0 -10 100 30 100 C70 100 70 0 30 0 M36 70 L62 104',R:'M0 100 L0 0 L34 0 C62 0 62 52 34 52 L0 52 M28 52 L60 100',S:'M56 16 C48 -4 4 -4 4 24 C4 50 56 46 56 74 C56 104 8 104 2 84',T:'M0 0 L60 0 M30 0 L30 100',U:'M0 0 L0 68 C0 104 60 104 60 68 L60 0',V:'M0 0 L30 100 L60 0',W:'M0 0 L14 100 L30 40 L46 100 L60 0',X:'M0 0 L60 100 M60 0 L0 100',Y:'M0 0 L30 50 L60 0 M30 50 L30 100',Z:'M0 0 L60 0 L0 100 L60 100',0:'M30 0 C-4 0 -4 100 30 100 C64 100 64 0 30 0',1:'M16 18 L34 0 L34 100',2:'M4 22 C8 -6 56 -6 56 26 C56 52 0 78 0 100 L60 100',3:'M4 12 C20 -6 56 0 56 24 C56 44 36 48 24 48 C40 48 60 56 60 76 C60 104 12 106 2 86',4:'M44 100 L44 0 L0 70 L60 70',5:'M56 0 L8 0 L4 44 C20 32 58 34 58 68 C58 104 12 106 2 86',6:'M52 6 C30 -4 2 10 2 60 C2 104 58 104 58 70 C58 40 12 40 4 64',7:'M0 0 L60 0 L22 100',8:'M30 48 C4 48 4 0 30 0 C56 0 56 48 30 48 C0 48 0 100 30 100 C60 100 60 48 30 48',9:'M56 36 C56 70 4 70 4 36 C4 0 56 0 56 36 L50 100'};
var rg=function(a,b){var r=[];for(var i=a;i<=b;i++)r.push(i);return r;};
var esc=function(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');};
var em=function(e,x,y,s,x2){return '<text x="'+x.toFixed(1)+'" y="'+y.toFixed(1)+'" font-size="'+s.toFixed(1)+'" text-anchor="middle" dominant-baseline="central" font-family=\''+EF+'\''+(x2||'')+'>'+e+'</text>';};
var tx=function(s,x,y,z,o){o=o||{};return '<text x="'+x.toFixed(1)+'" y="'+y.toFixed(1)+'" font-size="'+z+'" font-family=\''+TF+'\' font-weight="'+(o.w||700)+'" fill="'+(o.f||'#1d2433')+'" text-anchor="'+(o.a||'start')+'"'+(o.x||'')+'>'+esc(s)+'</text>';};
var rc=function(x,y,w,h,o){o=o||{};return '<rect x="'+x.toFixed(1)+'" y="'+y.toFixed(1)+'" width="'+w.toFixed(1)+'" height="'+h.toFixed(1)+'" rx="'+(o.r==null?14:o.r)+'" fill="'+(o.f||'none')+'" stroke="'+(o.s||'#555')+'" stroke-width="'+(o.sw||3)+'"'+(o.d?' stroke-dasharray="'+o.d+'"':'')+(o.x||'')+'/>';};
var dot=function(x,y,r,f){return '<circle cx="'+x.toFixed(1)+'" cy="'+y.toFixed(1)+'" r="'+r+'" fill="'+f+'"/>';};
var ln=function(x1,y1,x2,y2,o){o=o||{};return '<line x1="'+x1.toFixed(1)+'" y1="'+y1.toFixed(1)+'" x2="'+x2.toFixed(1)+'" y2="'+y2.toFixed(1)+'" stroke="'+(o.s||'#555')+'" stroke-width="'+(o.sw||3)+'" stroke-linecap="round"'+(o.d?' stroke-dasharray="'+o.d+'"':'')+'/>';};
var sil=function(c){return ' filter="url(#'+c.id+'s)"';};
var wrap=function(s,n){var out=[''];s.split(' ').forEach(function(w){(out[out.length-1]+' '+w).trim().length>n?out.push(w):out[out.length-1]=(out[out.length-1]+' '+w).trim();});return out;};
var gl=function(ch,x,y,h,o){o=o||{};var d=G[ch];if(!d)return '';var k=h/100,m=/M(-?[\d.]+) (-?[\d.]+)/.exec(d),sw=(o.w||6)/k;return '<path d="'+d+'" transform="translate('+x.toFixed(1)+' '+y.toFixed(1)+') scale('+k.toFixed(3)+')" fill="none" stroke="'+(o.c||'#8d95a3')+'" stroke-width="'+sw.toFixed(2)+'" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="'+(0.1/k).toFixed(3)+' '+((o.gap||13)/k).toFixed(2)+'"/>'+dot(x+m[1]*k,y+m[2]*k,Math.max(5,h*.055),'#2fa860');};
var word=function(s,x,y,h,o){return s.split('').map(function(ch,i){return gl(ch,x+i*h*.9,y,h,o);}).join('');};
var guide=function(x,y,w,h){return ln(x,y,x+w,y,{s:'#b9bec7',sw:2})+ln(x,y+h/2,x+w,y+h/2,{s:'#cfd3da',sw:2,d:'8 8'})+ln(x,y+h,x+w,y+h,{s:'#7d8595',sw:2.5});};
var lane=function(k,x0,x1,y,a){var w=x1-x0,d='M'+x0+' '+y,i,n,s;if(k==='wave'||k==='hill'){n=k==='hill'?3:6;s=w/n;for(i=0;i<n;i++)d+=' Q'+(x0+s*i+s/2).toFixed(1)+' '+(y+(k==='hill'?-1.7*a:i%2?a:-a)).toFixed(1)+' '+(x0+s*(i+1)).toFixed(1)+' '+y;return d;}if(k==='zig'){for(i=1;i<=8;i++)d+=' L'+(x0+w*i/8).toFixed(1)+' '+(i===8?y:y+(i%2?-a:a)).toFixed(1);return d;}if(k==='step'){s=w/8;for(i=0;i<8;i++)d+=' L'+(x0+s*i).toFixed(1)+' '+(y+(i%2?a:-a)*.8).toFixed(1)+' L'+(x0+s*(i+1)).toFixed(1)+' '+(y+(i%2?a:-a)*.8).toFixed(1);return d+' L'+x1+' '+y;}if(k==='bump'){n=6;s=w/n;for(i=0;i<n;i++)d+=' A'+(s/2).toFixed(1)+' '+(s/2).toFixed(1)+' 0 0 1 '+(x0+s*(i+1)).toFixed(1)+' '+y;return d;}return d+' L'+x1+' '+y;};
var head=function(c,title,instr){var ls=wrap(instr,66).slice(0,2);return rc(0,0,W,88,{f:c.th.bg,s:c.th.ac,sw:3,r:22})+em(c.th.m,48,45,48)+tx(title,90,42,31,{w:800})+tx(c.th.name+' · Page '+c.pg+' of '+c.tot,91,71,15,{f:c.th.ac})+tx('Name',512,38,15,{w:600,f:'#555'})+ln(560,41,732,41,{s:'#888',sw:2})+tx('Date',512,70,15,{w:600,f:'#555'})+ln(560,73,732,73,{s:'#888',sw:2})+ls.map(function(l,i){return tx(l,6,120+i*25,20,{w:600,f:'#333'});}).join('');};
var foot=function(){return tx('amni-scient.com/learn · Toddler Busy Pack · print, cut, glue & play',375,993,12,{a:'middle',f:'#8a8f99',w:500});};
var cutGrid=function(o){var n=o.list.length,rows=o.rows||(n>6?2:1),cols=Math.ceil(n/rows),cw=o.w/cols,ch=o.h/rows,ar=o.ar||1,ih=Math.min(ch,cw/ar)-10;ih=o.mx?Math.min(ih,o.mx):ih;var iw=ih*ar,out=tx('✂ Cut out',o.x,o.y-10,16,{f:'#666'});o.list.forEach(function(it,i){var r=Math.floor(i/cols),k=i%cols,rowN=Math.min(cols,n-r*cols),cx=o.x+(o.w-rowN*cw)/2+k*cw+cw/2,cy=o.y+r*ch+ch/2;out+=rc(cx-iw/2,cy-ih/2,iw,ih,{d:CUT,s:'#666',sw:2.5,r:8})+o.draw(it,cx,cy,iw,ih);});return out;};
var scene=function(c,id,hero,w,h){var d=pickN(c.rnd,c.th.deco,3);return '<g id="'+id+'"><defs><linearGradient id="'+id+'g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="'+c.th.sky+'"/><stop offset="1" stop-color="#ffffff"/></linearGradient></defs><rect width="'+w+'" height="'+h+'" fill="url(#'+id+'g)"/><rect y="'+(h*.74).toFixed(1)+'" width="'+w+'" height="'+(h*.26).toFixed(1)+'" fill="'+c.th.gr+'"/>'+em(d[0],w*.13,h*.2,h*.19)+em(d[1],w*.87,h*.2,h*.17)+em(d[2],w*.12,h*.8,h*.2)+em(hero[0],w*.5,h*.5,h*.6)+em(hero[1],w*.86,h*.78,h*.22)+'</g>';};
var bowl=function(cx,cy,w,hex,name){var d=w*.5;return '<path d="M'+(cx-w/2)+' '+cy+' Q'+(cx-w/2)+' '+(cy+d*1.25)+' '+cx+' '+(cy+d*1.25)+' Q'+(cx+w/2)+' '+(cy+d*1.25)+' '+(cx+w/2)+' '+cy+' Z" fill="'+hex+'" fill-opacity=".14" stroke="'+hex+'" stroke-width="5"/><ellipse cx="'+cx+'" cy="'+cy+'" rx="'+w/2+'" ry="'+(w*.1).toFixed(1)+'" fill="#fff" stroke="'+hex+'" stroke-width="10"/>'+tx(name.toUpperCase(),cx,cy+d*1.25+38,24,{a:'middle',f:hex,w:800});};
var T={
countCut:{a:[1,6],g:'cut',t:'Count & Cut',f:function(c){var R=c.age<=2?3:c.age<=4?4:5,mx=c.age<=2?3:c.age<=4?5:8,ns=pickN(c.rnd,rg(1,mx),R),its=c.take(R),top=160,rh=(770-top)/R,bx=Math.min(112,rh-22),b=head(c,'Count & Cut','Count the pictures in each row. Cut out the numbers and glue each one in its box.');ns.forEach(function(n,i){var y=top+i*rh,cy=y+rh/2,sp=Math.min(92,520/n),s=Math.min(70,rh*.6,sp*.92);b+=rc(0,y+6,W,rh-12,{s:'#c3c7cf',sw:2,r:16})+rg(0,n-1).map(function(k){return em(its[i][0],30+sp/2+k*sp,cy,s);}).join('')+rc(W-bx-22,cy-bx/2,bx,bx,{s:'#333',sw:3,r:12});});return b+cutGrid({x:20,y:815,w:710,h:145,list:pickN(c.rnd,ns,R),mx:bx-6,draw:function(n,cx,cy,s){return tx(String(n),cx,cy+s*.14,s*.58,{a:'middle',w:800})+rg(0,n-1).map(function(k){return dot(cx+(k-(n-1)/2)*Math.min(12,s*.8/n),cy+s*.36,Math.min(4.5,s*.04),'#555');}).join('');}});}},
shadowMatch:{a:[1,6],g:'cut',t:'Match the Shadows',f:function(c){var n=c.age<=2?4:c.age<=4?6:8,its=c.take(n),cols=n<=4?2:n<=6?3:4,gw=W/cols,gh=390/2,s=Math.min(118,gw*.6),b=head(c,'Match the Shadows','Cut out the pictures and glue each one right on top of its shadow.');its.forEach(function(it,i){var cx=gw*(i%cols)+gw/2,cy=165+gh*Math.floor(i/cols)+gh/2;b+=rc(cx-gw/2+10,cy-gh/2+8,gw-20,gh-16,{s:'#d0d4da',sw:2,r:18})+em(it[0],cx,cy,s,sil(c));});return b+cutGrid({x:20,y:600,w:710,h:355,rows:n>4?2:1,list:pickN(c.rnd,its,n),mx:s*1.3,draw:function(it,cx,cy){return em(it[0],cx,cy,s);}});}},
drawLines:{a:[1,6],g:'lines',t:'Draw a Line',f:function(c){var n=c.age<=2?3:c.age<=4?4:5,vs=(c.age<=2?['same','shadow']:['same','shadow','together','together']).filter(function(v){return v!=='shadow'||c.kinds.indexOf('shadowMatch')<0;}),v=vs[Math.floor(c.rnd()*vs.length)],th=c.th.maze.map(function(m){return [m[0],m[1]];}),seen={},pairs=v==='together'?pickN(c.rnd,th,2).concat(pickN(c.rnd,TOG,TOG.length)).filter(function(p){var ok=!seen[p[0]]&&!seen[p[1]];seen[p[0]]=seen[p[1]]=1;return ok;}).slice(0,n):c.take(n).map(function(it){return [it[0],it[0]];}),rs=pickN(c.rnd,rg(0,n-1),n),top=170,rh=(960-top)/n,s=Math.min(104,rh*.66);while(rs.every(function(x,i){return x===i;}))rs=pickN(c.rnd,rg(0,n-1),n);var b=head(c,v==='together'?'What Goes Together?':v==='shadow'?'Find the Shadow':'Find the Match',v==='together'?'Draw a line from each picture to the one that goes with it.':v==='shadow'?'Draw a line from each picture to its shadow.':'Draw a line to join the pictures that are the same.');pairs.forEach(function(p,i){var yl=top+i*rh+rh/2,yr=top+rs.indexOf(i)*rh+rh/2;b+=em(p[0],140,yl,s)+dot(250,yl,12,c.th.ac)+dot(500,yr,12,c.th.ac)+em(p[1],610,yr,s,v==='shadow'?sil(c):'');});return b;}},
prewrite:{a:[1,3],g:'trace',t:'Trace the Lines',f:function(c){var mz=c.maze(),ks=c.age<=1?['line','hill','line','wave','hill']:pickN(c.rnd,['line','wave','zig','bump','step','hill'],5),top=170,rh=790/5,b=head(c,'Trace the Lines','Help the '+mz[2]+' get to the '+mz[3]+'! Trace each dotted line with a finger, then a crayon.');ks.forEach(function(k,i){var y=top+i*rh+rh/2;b+=em(mz[0],52,y,66)+'<path d="'+lane(k,108,642,y,rh*.26)+'" fill="none" stroke="#8d95a3" stroke-width="8" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="0.1 15"/>'+dot(108,y,10,'#2fa860')+em(mz[1],698,y,66);});return b;}},
letters:{a:[3,6],g:'trace',t:'Letter Tracing',f:function(c){var ws=c.th.items.filter(function(it){return /^[A-Z]{2,6}$/.test(it[1]);}),it=pickN(c.rnd,ws,1)[0],L=it[1][0],h=c.age<=3?100:90,b=head(c,'Letter '+L,'Trace the big letter with a finger. Then trace the dotted letters with a crayon.');b+=rc(15,160,720,310,{s:c.th.ac,sw:3,r:24,f:c.th.bg})+gl(L,85,185,255,{w:10,gap:17})+em(it[0],500,280,150)+tx(L+' is for '+it[1],500,425,36,{a:'middle',w:800,f:c.th.ac});var rows=c.age<=3?[L,L,L]:[L,L,c.name||it[1]],y=505;rows.forEach(function(r){b+=guide(20,y,710,h);var mx=Math.floor(690/(h*.9)),unit=r.length>1?rg(1,Math.max(1,Math.floor((mx+1)/(r.length+1)))).map(function(){return r;}).join(' '):rg(1,mx).map(function(){return r;}).join('');b+=word(unit,32,y,h);y+=h+52;});return b;}},
numbers:{a:[3,6],g:'trace',t:'Number Tracing',f:function(c){var ns=c.age<=3?[1,2,3,4,5]:pickN(c.rnd,rg(1,9),5).sort(function(a,b){return a-b;}),its=c.take(5),rh=158,b=head(c,'Trace the Numbers','Count the pictures. Trace each number with a finger, then with a crayon.');ns.forEach(function(n,i){var y=165+i*rh,cols=n<=5?n:Math.ceil(n/2),rows=n<=5?1:2,s=Math.min(54,250/cols*.88,(rh-34)/rows*.8);b+=rc(10,y+6,730,rh-12,{s:'#c3c7cf',sw:2,r:16});rg(0,n-1).forEach(function(k){b+=em(its[i][0],30+(k%cols)*(270/cols)+135/cols,y+rh/2+(rows===2?(Math.floor(k/cols)-.5)*(rh-40)/2:0),s);});b+=gl(String(n),330,y+24,110,{w:9,gap:15})+[455,555,655].map(function(x){return gl(String(n),x,y+44,80);}).join('');});return b;}},
shapes:{a:[2,5],g:'trace',t:'Shape Tracing',f:function(c){var ks=['circle','square','triangle','star','heart','zigzag'],its=c.take(6),cw=250,ch=392,b=head(c,'Trace the Shapes','Trace around each shape. Start at the green dot. Say the shape name out loud!');ks.forEach(function(k,i){var x=(i%3)*cw,y=165+Math.floor(i/3)*ch,z=k==='zigzag'?100:200;b+=rc(x+8,y+8,cw-16,ch-16,{s:'#d0d4da',sw:2,r:18})+shapeSVG(k,z).replace('<svg ','<svg x="'+(x+(cw-(k==='zigzag'?z*2:z))/2)+'" y="'+(y+(k==='zigzag'?120:50))+'" ')+(k==='zigzag'?em(its[i][0],x+cw/2,y+80,56):em(its[i][0],x+cw/2,y+50+z*(k==='triangle'?.62:k==='heart'?.46:.5),k==='star'?40:64))+tx(k==='zigzag'?'ZIG-ZAG':k.toUpperCase(),x+cw/2,y+ch-40,24,{a:'middle',w:800,f:c.th.ac});});return b;}},
scissors:{a:[2,5],g:'trace',t:'Cutting Practice',f:function(c){var mz=c.maze(),ks=c.age<=2?['line','hill','line','hill','line']:c.age<=3?['line','hill','wave','zig','line']:pickN(c.rnd,['line','wave','zig','step','hill','bump'],5),rh=158,b=head(c,'Snip Snip!','Cut along each dashed line, from the edge of the paper all the way to the '+mz[3]+'.');ks.forEach(function(k,i){var y=165+i*rh+rh/2;b+=tx('✂',8,y-14,26,{f:'#555'})+'<path d="'+lane(k,0,648,y,rh*.24)+'" fill="none" stroke="#333" stroke-width="4" stroke-dasharray="16 10" stroke-linecap="round"/>'+em(mz[1],700,y,62);});return b;}},
maze:{a:[1,6],g:'maze',t:'Maze',f:function(c){var mz=c.maze(),n=[4,4,5,6,7,8][c.age-1],S=560,cell=S/n,ox=(W-S)/2,oy=250,eq=function(a,b){return Math.abs(a-b)<.01;},ls=mazeLines(c.rnd,n,cell).filter(function(l){return !(eq(l[0],0)&&eq(l[1],0)&&eq(l[2],cell)&&eq(l[3],0))&&!(eq(l[0],(n-1)*cell)&&eq(l[1],S)&&eq(l[3],S));}),sw=c.age<=2?10:7,d=pickN(c.rnd,c.th.deco,4),b=head(c,'Maze Time','Help the '+mz[2]+' find the '+mz[3]+'! Draw a line through the maze.');b+='<g transform="translate('+ox+','+oy+')">'+ls.map(function(l){return ln(l[0],l[1],l[2],l[3],{s:'#3a3f4a',sw:sw});}).join('')+'</g>'+em(mz[0],ox+cell/2,oy-48,Math.min(72,cell*.95))+'<path d="M'+(ox+cell/2)+' '+(oy-10)+' l-10 -14 l20 0 z" fill="#2fa860"/>'+em(mz[1],ox+S-cell/2,oy+S+50,Math.min(72,cell*.95))+em(d[0],60,oy+S/2,54)+em(d[1],690,oy+S/2,54)+em(d[2],80,930,44)+em(d[3],670,190,44);return b;}},
colorSort:{a:[1,5],g:'cut',t:'Fill the Bowls',f:function(c){var k=c.age<=2?3:4,per=c.age<=2?2:3,cs=pickN(c.rnd,Object.keys(COL),k),b=head(c,'Fill the Bowls','Cut out the pictures. Glue each one into the bowl that is the same color.'),list=[];cs.forEach(function(cn,i){var mine=c.th.items.filter(function(it){return it[2]===cn;}).map(function(it){return it[0];}),pool=pickN(c.rnd,mine,2).concat(pickN(c.rnd,COL[cn][1],COL[cn][1].length)).filter(function(e,j,a){return a.indexOf(e)===j;});list=list.concat(pool.slice(0,per));b+=k===3?bowl(128+i*247,300,215,COL[cn][0],cn):bowl(i%2?560:190,205+Math.floor(i/2)*265,270,COL[cn][0],cn);});return b+cutGrid({x:20,y:715,w:710,h:245,rows:2,list:pickN(c.rnd,list,list.length),mx:108,draw:function(e,cx,cy,s){return em(e,cx,cy,s*.72);}});}},
puzzle:{a:[1,6],g:'cut',t:'Picture Puzzle',f:function(c){var gs=c.age<=2?[2,2]:c.age<=4?[3,2]:[3,3],w=600,h=360,x=75,y1=178,y2=590,id=c.id+'p',b=head(c,'Picture Puzzle','Cut the picture on the dashed lines. Mix up the pieces, then glue them back together in the frame.');b+='<defs>'+scene(c,id,c.take(2).map(function(i){return i[0];}),w,h)+'</defs><use href="#'+id+'" x="'+x+'" y="'+y1+'"/>'+rc(x,y1,w,h,{d:CUT,s:'#333',sw:3,r:0})+rg(1,gs[0]-1).map(function(i){return ln(x+w*i/gs[0],y1,x+w*i/gs[0],y1+h,{s:'#333',sw:3,d:CUT});}).join('')+rg(1,gs[1]-1).map(function(i){return ln(x,y1+h*i/gs[1],x+w,y1+h*i/gs[1],{s:'#333',sw:3,d:CUT});}).join('')+tx('✂',x-40,y1+22,28,{f:'#555'})+(c.age<=3?'<use href="#'+id+'" x="'+x+'" y="'+y2+'" opacity=".13"/>':'')+rc(x,y2,w,h,{s:c.th.ac,sw:5,r:0})+rg(1,gs[0]-1).map(function(i){return ln(x+w*i/gs[0],y2,x+w*i/gs[0],y2+h,{s:'#9aa1ab',sw:2});}).join('')+rg(1,gs[1]-1).map(function(i){return ln(x,y2+h*i/gs[1],x+w,y2+h*i/gs[1],{s:'#9aa1ab',sw:2});}).join('')+tx('Glue the pieces here',375,y2-12,17,{a:'middle',f:c.th.ac});return b;}},
numberOrder:{a:[2,6],g:'cut',t:'Number Order',f:function(c){var k=[3,3,4,5,5,6][c.age-1],w=650,h=350,x=50,y1=172,y2=590,id=c.id+'n',sw=w/k,b=head(c,'Number Order','Cut the strips apart. Mix them up, then glue them in order: 1, 2, 3...');b+='<defs>'+scene(c,id,c.take(2).map(function(i){return i[0];}),w,h)+'</defs><use href="#'+id+'" x="'+x+'" y="'+y1+'"/>'+rc(x,y1+h-54,w,54,{f:'#fff',s:'none',sw:0,r:0})+rg(0,k-1).map(function(i){return tx(String(i+1),x+sw*i+sw/2,y1+h-13,40,{a:'middle',w:800});}).join('')+rc(x,y1,w,h,{d:CUT,s:'#333',sw:3,r:0})+rg(1,k-1).map(function(i){return ln(x+sw*i,y1,x+sw*i,y1+h,{s:'#333',sw:3,d:CUT});}).join('')+tx('✂',x-38,y1+22,28,{f:'#555'})+rc(x,y2,w,h,{s:c.th.ac,sw:5,r:0})+rg(0,k-1).map(function(i){return (i?ln(x+sw*i,y2,x+sw*i,y2+h,{s:'#9aa1ab',sw:2}):'')+tx(String(i+1),x+sw*i+sw/2,y2+h-18,52,{a:'middle',w:800,f:'#dde0e5'});}).join('')+tx('Glue the strips here in order',375,y2-12,17,{a:'middle',f:c.th.ac});return b;}},
halves:{a:[2,6],g:'cut',t:'Match the Halves',f:function(c){var n=[3,3,4,4,6,6][c.age-1],cols=n<=3?1:2,rows=Math.ceil(n/cols),its=c.take(n),gw=W/cols,gh=500/rows,s=Math.min(150,gh*.8),fs=s*.86,b=head(c,'Match the Halves','Cut out the missing halves. Glue each one next to the half that matches.');var half=function(e,x,y,right){return '<svg x="'+x.toFixed(1)+'" y="'+y.toFixed(1)+'" width="'+(s/2).toFixed(1)+'" height="'+s.toFixed(1)+'" viewBox="'+(right?s/2:0).toFixed(1)+' 0 '+(s/2).toFixed(1)+' '+s.toFixed(1)+'">'+em(e,s/2,s/2,fs)+'</svg>';};its.forEach(function(it,i){var cx=gw*(i%cols)+gw/2,cy=165+gh*Math.floor(i/cols)+gh/2;b+=rc(cx-gw/2+12,cy-gh/2+6,gw-24,gh-12,{s:'#d0d4da',sw:2,r:18})+half(it[0],cx-s/2,cy-s/2,0)+rc(cx,cy-s/2,s/2,s,{d:'6 6',s:'#a7adb7',sw:2,r:4});});return b+cutGrid({x:20,y:705,w:710,h:255,rows:1,ar:.5,mx:s,list:pickN(c.rnd,its,n),draw:function(it,cx,cy,iw,ih){return half(it[0],cx-s/4,cy-s/2,1);}});}},
sizeSort:{a:[1,4],g:'cut',t:'Big & Small',f:function(c){var two=c.age<=2,R=two?2:3,its=c.take(R),lab=two?['BIG','SMALL']:['BIG','MEDIUM','SMALL'],sz=two?[.86,.42]:[.86,.6,.36],top=165,rh=(620-top)/R,bw=two?220:185,bh=rh-44,b=head(c,'Big & Small',two?'Cut out the pictures. Glue the big one on BIG and the small one on SMALL.':'Cut out the pictures. Glue them in order: big, medium, small.'),list=[];its.forEach(function(it,i){var cy=top+i*rh+bh/2+6;lab.forEach(function(l,j){var cx=W/2+(j-(lab.length-1)/2)*(bw+34);b+=rc(cx-bw/2,cy-bh/2,bw,bh,{s:c.th.ac,sw:3,r:16})+tx(l,cx,cy+bh/2+24,17,{a:'middle',f:c.th.ac,w:800});});sz.forEach(function(z){list.push([it[0],z]);});});return b+cutGrid({x:20,y:665,w:710,h:295,rows:2,mx:bh-6,list:pickN(c.rnd,list,list.length),draw:function(p,cx,cy,s){return em(p[0],cx,cy,s*p[1]);}});}},
patterns:{a:[3,6],g:'cut',t:'What Comes Next?',f:function(c){var ks=c.age<=3?['AB']:c.age<=4?['AB','AAB','ABB']:['AB','AAB','ABB','ABC','AABB'],top=165,rh=118,cell=88,x0=(W-7*(cell+10))/2,ans=[],b=head(c,'What Comes Next?','Look at each row. Cut out the picture that comes next and glue it in the empty box.');rg(0,3).forEach(function(i){var k=ks[Math.floor(c.rnd()*ks.length)],its=c.take(3),y=top+i*rh+rh/2;rg(0,6).forEach(function(j){var e=its[k.charCodeAt(j%k.length)-65][0],cx=x0+j*(cell+10)+cell/2;j<6?b+=em(e,cx,y,cell*.78):(ans.push(e),b+=rc(cx-cell/2,y-cell/2,cell,cell,{d:'8 6',s:c.th.ac,sw:3,r:10})+tx('?',cx,y+14,40,{a:'middle',f:'#c9cdd4',w:800}));});b+=ln(20,top+(i+1)*rh,730,top+(i+1)*rh,{s:'#e1e4e8',sw:2});});return b+cutGrid({x:20,y:690,w:710,h:170,rows:1,mx:cell,list:pickN(c.rnd,ans,4),draw:function(e,cx,cy,s){return em(e,cx,cy,s*.8);}});}},
countTally:{a:[2,6],g:'other',t:"Let's Count",f:function(c){var K=c.age<=2?2:3,mx=c.age<=2?4:c.age<=4?6:9,its=c.take(K),ns=its.map(function(){return 1+Math.floor(c.rnd()*mx);}),cols=8,rows=5,cw=700/cols,ch=420/rows,sl=pickN(c.rnd,rg(0,cols*rows-1),ns.reduce(function(a,b){return a+b;},0)),q=0,b=head(c,"Let's Count!",'Count each kind of picture. Then circle the right number in its row.');b+=rc(15,160,720,430,{s:c.th.ac,sw:3,r:22,f:c.th.bg});its.forEach(function(it,i){for(var j=0;j<ns[i];j++){var p=sl[q++];b+=em(it[0],25+(p%cols)*cw+cw/2+(c.rnd()-.5)*cw*.3,165+Math.floor(p/cols)*ch+ch/2+(c.rnd()-.5)*ch*.25,Math.min(60,ch*.72));}});var rh=350/K,sp=600/mx;its.forEach(function(it,i){var y=615+i*rh+rh/2;b+=em(it[0],62,y,Math.min(64,rh*.6))+rg(1,mx).map(function(n){var x=130+(n-1)*sp+sp/2;return '<circle cx="'+x.toFixed(1)+'" cy="'+y.toFixed(1)+'" r="'+Math.min(30,sp*.42).toFixed(1)+'" fill="none" stroke="#9aa1ab" stroke-width="2.5"/>'+tx(String(n),x,y+11,30,{a:'middle',w:800});}).join('');});return b;}},
oddOne:{a:[2,6],g:'other',t:'Odd One Out',f:function(c){var R=c.age<=2?3:c.age<=4?4:5,N=c.age<=2?3:c.age<=4?4:5,top=165,rh=790/R,s=Math.min(100,rh*.62,560/N*.8),b=head(c,'Odd One Out','Look at each row. Circle the one that is different.');rg(0,R-1).forEach(function(i){var p=c.take(2),at=Math.floor(c.rnd()*N),y=top+i*rh+rh/2;b+=rc(10,y-rh/2+8,730,rh-16,{s:'#d0d4da',sw:2,r:18})+rg(0,N-1).map(function(j){return em((j===at?p[1]:p[0])[0],W/2+(j-(N-1)/2)*(680/N),y,s);}).join('');});return b;}},
iSpy:{a:[2,6],g:'other',t:'Find & Color',f:function(c){var cols=c.age<=2?4:5,rows=c.age<=2?3:4,K=c.age<=2?3:4,its=c.take(K),tgt=its[0][0],want=2+Math.floor(c.rnd()*(c.age<=2?3:5)),n=cols*rows,cells=pickN(c.rnd,rg(0,n-1),n),grid=[],cw=700/cols,ch=580/rows,b=head(c,'Find & Color','Find every picture that matches the one in the box. Color it in, then count them!');cells.forEach(function(p,i){grid[p]=i<want?tgt:its[1+Math.floor(c.rnd()*(K-1))][0];});b+=rc(275,150,200,120,{s:c.th.ac,sw:4,r:18,f:c.th.bg})+em(tgt,375,210,86);grid.forEach(function(e,p){var x=25+(p%cols)*cw+cw/2,y=300+Math.floor(p/cols)*ch+ch/2;b+=rc(x-cw/2+6,y-ch/2+6,cw-12,ch-12,{s:'#dfe2e6',sw:2,r:12})+em(e,x,y,Math.min(84,ch*.62));});return b+tx('How many did you find?',230,948,24,{a:'middle',w:800})+rc(440,905,110,70,{s:'#333',sw:3,r:12});}}};
var plan=function(age,rnd){var ok=Object.keys(T).filter(function(k){return age>=T[k].a[0]&&age<=T[k].a[1];}),by=function(g,n){return pickN(rnd,ok.filter(function(k){return T[k].g===g;}),n);},p=['maze'].concat(by('trace',1),by('lines',1),by('cut',2));return pickN(rnd,p.concat(pickN(rnd,ok.filter(function(k){return p.indexOf(k)<0;}),7-p.length)),7);};
var theme=function(nonce){var d=new Date(),day=Math.floor(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())/864e5),ord=pickN(mulberry32(20260928),rg(0,TH.length-1),TH.length);return TH[ord[((day+nonce)%TH.length+TH.length)%TH.length]];};
var render=function(age,nonce,o){o=o||{};var th=theme(nonce),rnd=mulberry32(xmur3(todayStr()+'|busy|'+age+'|'+nonce)()),ks=o.only||plan(age,rnd),nm=(o.name||'').toUpperCase().replace(/[^A-Z]/g,'').slice(0,7);return {theme:th,html:ks.map(function(k,i){var c={age:age,rnd:rnd,th:th,kinds:ks,name:nm.length>=2?nm:'',pg:i+1,tot:ks.length,id:'bp'+(i+1),take:function(n){return pickN(rnd,th.items,n);},maze:function(){return th.maze[Math.floor(rnd()*th.maze.length)];}};return '<div class="page-sep">Page '+(i+1)+' of '+ks.length+' — '+T[k].t+'</div><div class="bp-page" data-kind="'+k+'"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 750 1000" class="bp-svg" role="img" aria-label="'+esc(th.name+': '+T[k].t)+'"><defs><filter id="'+c.id+'s" color-interpolation-filters="sRGB"><feColorMatrix type="matrix" values="0 0 0 0 .6 0 0 0 0 .62 0 0 0 0 .66 0 0 0 1 0"/></filter></defs>'+T[k].f(c)+foot()+'</svg></div>';}).join('')};};
return {render:render,types:T,themes:TH};
})();
