name = "amni-beta"
main = "worker.mjs"
compatibility_date = "2026-09-01"
workers_dev = true
preview_urls = false
[vars]
ALLOWED_ORIGINS = "https://amni-scient.com,https://www.amni-scient.com"
[[d1_databases]]
binding = "DB"
database_name = "amni-beta"
database_id = "343b7196-cf4e-4a1c-833d-c87167982ce4"
[[kv_namespaces]]
binding = "RL"
id = "9af34c7df2c04fc389f8863967518fe9"
[observability]
enabled = false
