/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_4451: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_675: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_6860: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_8255: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_11121: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_6861: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_11130: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_676: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_676_2: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_8256: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_8256_5: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11122: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11122_8: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11122_9: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11122_10: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11122_11: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11122_12: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11122_13: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11122_14: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_4452: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_11132: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
