/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_672: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_4425: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_6834: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_8228: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_11094: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_6835: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_11103: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_673: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_673_1: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_8229: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_8229_5: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11095: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11095_8: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11095_9: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11095_10: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11095_11: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11095_12: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11095_13: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11095_14: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_4426: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_11105: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
