/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_4364: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_6774: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_8168: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_11034: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_670: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_6775: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_11043: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_8169: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_8169_3: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11035: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11035_6: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11035_7: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11035_8: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11035_9: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11035_10: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11035_11: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11035_12: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_671: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_671_15: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_4365: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_11045: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
