export const toCents = n => Number.isFinite(+n) && n !== null && n !== '' ? Math.round(+(+n * 100).toFixed(6)) : 0
export const money = (n, dp = 2) => (+n < 0 ? '-$' : '$') + Math.abs(dp ? toCents(n) / 100 : Math.round(+n || 0)).toLocaleString('en-US', { minimumFractionDigits: dp, maximumFractionDigits: dp })
export const parsePrice = s => { const t = String(s ?? '').replace(/[$,\s]/g, ''), v = t === '' ? NaN : Number(t); return Number.isFinite(v) && v >= 0 ? toCents(v) / 100 : null }
export const priceBom = (bom, price) => { let th = 0, tl = 0; const rows = (bom || []).map(it => { const q = Math.max(0, +it.qty || 0), ph = price(it.id, 'hd'), pl = price(it.id, 'lowes'), ch = ph == null ? null : toCents(ph * q), cl = pl == null ? null : toCents(pl * q); th += ch || 0; tl += cl || 0; return { it, q, ph, pl, lh: ch == null ? null : ch / 100, ll: cl == null ? null : cl / 100 } }); return { rows, th: th / 100, tl: tl / 100 } }
export const csvCell = v => { const s = v == null ? '' : String(v); return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s }
export const csv = rows => rows.map(r => r.map(csvCell).join(',')).join('\r\n')
export const bomCsv = (bom, price) => { const { rows, th, tl } = priceBom(bom, price), f = v => v == null ? '' : (toCents(v) / 100).toFixed(2); return csv([['Item', 'Qty', 'HD each', 'HD total', 'Lowes each', 'Lowes total'], ...rows.map(r => [r.it.desc, r.q, f(r.ph), f(r.lh), f(r.pl), f(r.ll)]), ['TOTAL', '', '', f(th), '', f(tl)]]) }
export const fitNum = (raw, lim = {}, prev) => { const v = typeof raw === 'number' ? raw : String(raw ?? '').trim() === '' ? NaN : Number(raw), lo = lim.min === '' || lim.min == null ? -Infinity : +lim.min, hi = lim.max === '' || lim.max == null ? Infinity : +lim.max, st = +lim.step || 0, r = Number.isFinite(v) ? v : +prev; return Number.isFinite(r) ? Math.min(hi, Math.max(lo, st >= 1 ? Math.round(r) : r)) : Number.isFinite(lo) ? lo : 0 }
export const validPoly = p => Array.isArray(p) && p.length >= 3 && p.every(q => Array.isArray(q) && q.length >= 2 && Number.isFinite(+q[0]) && Number.isFinite(+q[1]) && q[0] !== null && q[1] !== null)
export const sanitizeCfg = (raw, def, enums = {}) => { const o = { ...def, ...(raw && typeof raw === 'object' && !Array.isArray(raw) ? raw : {}) }; Object.keys(def).forEach(k => { const d = def[k], v = o[k]; typeof d === 'number' ? o[k] = v !== null && v !== '' && typeof v !== 'boolean' && Number.isFinite(+v) ? +v : d : typeof d === 'boolean' ? o[k] = typeof v === 'boolean' ? v : d : enums[k] && !enums[k].includes(String(v)) && (o[k] = d) }); 'polygon' in def && (o.polygon = validPoly(o.polygon) ? o.polygon.map(q => [+q[0], +q[1]]) : null, o.mode === 'poly' && !o.polygon && (o.mode = 'rect'), 'house_edge' in def && (o.house_edge = o.mode === 'poly' ? (o.house_edge >= 0 && o.house_edge < o.polygon.length ? Math.round(o.house_edge) : -1) : o.house_edge >= 0 ? 0 : -1)); return o }
export const coreError = e => /invalid (type|value)|expected |missing field|EOF while|trailing/i.test(String(e)) ? 'One of the inputs is empty or out of range. Check the numbers on the left and try again.' : String(e || 'Could not build this estimate.')
export const hvacSize = a => { const tons = Math.max(1, Math.round((+a || 0) / 250) / 2); return { tons, cfm: tons * 400 } }
export const studSpec = h => h <= 8 ? { len: '92-5/8"', f: 1 } : h <= 9 ? { len: '104-5/8"', f: 104.625 / 92.625 } : h <= 10 ? { len: '116-5/8"', f: 116.625 / 92.625 } : { len: h <= 11.5 ? '12 ft' : '14 ft', f: (h <= 11.5 ? 144 : 168) / 92.625 }
export const studBom = (bom, h) => { const s = studSpec(+h || 8); return s.f === 1 ? bom : bom.map(it => /^stud6?$/.test(it.id) ? { ...it, desc: it.desc.replace(/\(precut 92-5\/8\)/, s.len.endsWith('ft') ? `(${s.len}, cut to length)` : `(precut ${s.len})`) } : it) }
export const sanitizeRooms = (rooms, kinds, def) => { const r = (Array.isArray(rooms) ? rooms : def).filter(x => x && typeof x === 'object').map((x, i) => ({ ...x, name: typeof x.name === 'string' ? x.name.slice(0, 40) : `Room ${i + 1}`, kind: kinds.includes(x.kind) ? x.kind : 'other', w: fitNum(x.w, { min: 3, max: 80 }, 10), d: fitNum(x.d, { min: 3, max: 80 }, 10) })); return r.length || !Array.isArray(rooms) ? r : [] }
export const escXml = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c])
export const unXml = s => String(s ?? '').replace(/&(amp|lt|gt|quot|#39);/g, (m, k) => ({ amp: '&', lt: '<', gt: '>', quot: '"', '#39': "'" })[k])
export const rectHip = (out, w, d) => { const run = Math.min(+w, +d) / 2, hip = 4 * run * Math.sqrt(2 + (+out.calc.pitch / 12) ** 2), lf = (+out.calc.ridge_ft || 0) + hip, qty = Math.ceil(lf / 33); return { ...out, calc: { ...out.calc, hip_ft: hip }, bom: out.bom.map(b => b.id === 'ridgecap' ? { ...b, qty, desc: b.desc.replace(/\(\d+ lf\)/, `(${Math.round(lf)} lf)`) } : b), warnings: (out.warnings || []).map(s => s.replace(/\d+ ridge\/hip cap bundles/, `${qty} ridge/hip cap bundles`)) } }
