/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_677: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_5053: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_7466: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_8861: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_11727: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_7467: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_11736: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_678: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_678_1: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_8862: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_8862_5: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11728: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11728_8: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11728_9: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11728_10: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11728_11: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11728_12: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11728_13: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11728_14: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_5054: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_11738: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
