/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_677: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_5118: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_7531: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_8927: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_11793: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_7532: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_11802: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_678: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_678_1: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_8928: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_8928_5: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11794: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11794_8: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11794_9: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11794_10: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11794_11: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11794_12: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11794_13: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_11794_14: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_5119: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_11804: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
